package parsercov

// propose.go — the deterministic catalog-row drafter.
//
// WHAT THIS IS. Given ONE mined template, it renders (a) a `rules:` row for
// telemetry-catalog/events.yaml and (b) a fixture line for
// fixtures/syslog_events.jsonl, as TEXT. Same template in, same bytes out —
// there is no model, no randomness and no clock in this path (§15: no LLM
// anywhere near it; the drafting is string assembly over the mined shape).
//
// WHAT THIS IS NOT. It applies nothing. It does not write events.yaml, does not
// call bake_rules.py, does not touch parser_rules.py and does not reload the
// engine. "Adding a symptom is a ROW plus a fixture" (telemetry-catalog/
// README.md) and both of those are landed by a human through a pull request,
// where the bake validates them and CI replays the fixture. This route removes
// the transcription, not the review.
//
// WHY THE DRAFT SITS AT THE BOTTOM OF BOTH LADDERS.
//
//	fidelity_status: doc_claimed — nothing has been captured that proves this
//	    grammar. Claiming lab_validated for a shape mined out of production
//	    would be exactly the "reads as covered and fails silently" failure the
//	    catalog exists to prevent.
//	shadow: true — an A8 shadow rule is evaluated and COUNTED
//	    (corr_parser_shadow_hits_total{rule_id}) and emits nothing. So a landed
//	    draft earns its promotion on measured production traffic instead of on
//	    a reviewer's guess, and a wrong draft cannot produce evidence in the
//	    meantime.
//	kind: device_alarm — the generic keystone (#80 §4), which every signature
//	    template already knows. Inventing a new kind would make the rule emit
//	    inert evidence nothing correlates on.
//
// THE ROW SHAPE IS THE BAKE'S SHAPE. Keys, required fields, the enumerations
// and the pattern_src/guard tie are all mirrored from
// telemetry-catalog/bake_rules.py's validate_row; `bake_rules.py` has no
// --validate mode (only --check, a drift guard over the whole file), so the
// obligation is discharged Go-side by the structural checker in
// propose_test.go, which re-derives those same rules.

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
)

// Proposal is the POST .../propose body (services/api.ts CatalogProposal).
type Proposal struct {
	ProposalID string `json:"proposal_id"`
	Status     string `json:"status"`
	CatalogRow string `json:"catalog_row"`
	Fixture    string `json:"fixture"`
}

const (
	// maxPatternBytes bounds the generated regex. A device can put an
	// arbitrarily long line on the wire; the drafted pattern must not inherit
	// that (§9), and a 2 KB regex is already past anything reviewable.
	maxPatternBytes = 2048
	// draftKind is the generic-alarm keystone the draft emits (see above).
	draftKind = "device_alarm"
)

// ProposalID is the stable identity of a draft: a hash of the template id, so
// the same shape always drafts under the same id and two operators drafting the
// same shape are looking at the same proposal.
func ProposalID(templateID string) string {
	h := sha256.Sum256([]byte(templateID))
	return "prop-" + hex.EncodeToString(h[:])[:8]
}

// BuildProposal renders the draft for one mined item. Pure and total: an item
// with no appname and no mnemonic still produces a valid, if unanchored, row.
func BuildProposal(it Item) Proposal {
	rid := draftRuleID(it)
	pattern := patternFromTemplate(it.Template)
	marker := markerToken(it.Mnemonic)

	var b strings.Builder
	b.WriteString("# DRAFT — generated by Correlix from an unrecognized syslog shape.\n")
	b.WriteString("# NOTHING HAS BEEN APPLIED. To land it:\n")
	b.WriteString("#   1. paste this row into telemetry-catalog/events.yaml under `rules:`\n")
	b.WriteString("#   2. append the fixture line to telemetry-catalog/fixtures/syslog_events.jsonl\n")
	b.WriteString("#   3. run `python3 bake_rules.py` then `python3 -m pytest -q` in telemetry-catalog/\n")
	b.WriteString("#\n")
	b.WriteString("# It is drafted at the WEAKEST rung of both ladders on purpose:\n")
	b.WriteString("#   fidelity_status: doc_claimed  — no capture proves this grammar yet.\n")
	b.WriteString("#   shadow: true                  — counted (corr_parser_shadow_hits_total),\n")
	b.WriteString("#                                   emits nothing, so it earns promotion on\n")
	b.WriteString("#                                   real traffic before it makes evidence.\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Observed: %d line(s) from %d device(s), %s .. %s (template %s).\n",
		it.Count, it.Devices, orDash(it.FirstSeen), orDash(it.LastSeen), it.TemplateID)
	fmt.Fprintf(&b, "# Template: %s\n", yamlComment(it.Template))

	fmt.Fprintf(&b, "- rule_id: %s\n", rid)
	b.WriteString("  lane: syslog\n")
	b.WriteString("  source: syslog\n")
	fmt.Fprintf(&b, "  kind: %s\n", draftKind)
	b.WriteString("  entity_type: device\n")
	b.WriteString("  family: null\n")
	b.WriteString("  vendors: []\n")
	if marker != "" {
		fmt.Fprintf(&b, "  markers: [%s]\n", yamlSingle(marker))
	} else {
		b.WriteString("  markers: []\n")
	}
	fmt.Fprintf(&b, "  pattern_src: %s\n", yamlSingle(pattern))
	b.WriteString("  fidelity_status: doc_claimed\n")
	b.WriteString("  shadow: true\n")
	b.WriteString("  guard:\n")
	if marker != "" {
		b.WriteString("    all:\n")
		fmt.Fprintf(&b, "      - {contains: [ctoken, %s]}\n", yamlSingle(marker))
		fmt.Fprintf(&b, "      - {re: [msg, %s, '']}\n", yamlSingle(pattern))
	} else {
		fmt.Fprintf(&b, "    re: [msg, %s, '']\n", yamlSingle(pattern))
	}
	b.WriteString("  extract:\n")
	b.WriteString("    text: {var: msg, slice: 256}\n")
	b.WriteString("  emit:\n")
	fmt.Fprintf(&b, "    kind: %s\n", draftKind)
	fmt.Fprintf(&b, "    metric: %s\n", draftKind)
	b.WriteString("    modality: control_plane\n")
	b.WriteString("    entity: {type: device, id: '{host}'}\n")
	b.WriteString("    severity: {from_severity_num: true}\n")
	fmt.Fprintf(&b, "    native_id: '{host}|alarm|%s|{ts_ms}'\n", rid)
	b.WriteString("    content_tag: msg\n")
	b.WriteString("    tokens: [{t: '{host}'}]\n")
	b.WriteString("    attrs:\n")
	b.WriteString("      tag: {var: tag}\n")
	b.WriteString("      text: {var: text}\n")
	fmt.Fprintf(&b, "      draft_template_id: {const: %s}\n", yamlSingle(it.TemplateID))

	return Proposal{
		ProposalID: ProposalID(it.TemplateID),
		Status:     "drafted",
		CatalogRow: b.String(),
		Fixture:    fixtureLine(it),
	}
}

// fixtureLine renders the observed sample in the catalog's fixture shape
// (fixtures/syslog_events.jsonl: hostname / appname / message / timestamp).
//
// `_expect` is deliberately ABSENT. In test_events.py a fixture with no
// `_expect` asserts the line does NOT parse to a canonical event — which is
// exactly true of this draft: `family: null` means the conformance reader skips
// it, and `shadow: true` means the runtime emits nothing. The reviewer fills
// `_expect` in when they attach the row to a real family, and that edit is the
// moment the claim is made.
//
// `hostname` is a PLACEHOLDER, not the observed device. The sample line is the
// tenant's own data and stays in the tenant's own response, but a fixture is a
// repository artifact that leaves the deployment in a pull request — putting a
// real device name in it would leak estate topology into a public diff (§8: no
// PII/identifiers in artifacts that travel).
func fixtureLine(it Item) string {
	row := map[string]string{
		"hostname": "device-1",
		"appname":  it.AppName,
		"message":  it.Sample,
	}
	if it.LastSeen != "" {
		row["timestamp"] = it.LastSeen
	}
	// Marshalling a map[string]string sorts the keys, so the line is byte-stable
	// across runs and across processes.
	b, err := json.Marshal(row)
	if err != nil {
		// Unreachable: map[string]string always marshals. Reported rather than
		// swallowed (§10: no silent failures).
		return fmt.Sprintf("{\"error\": %q}", err.Error())
	}
	return string(b)
}

// draftRuleID builds `draft.<appname>.<mnemonic>`, falling back to the template
// id when the shape carries neither. The `draft.` prefix keeps it out of the
// namespace any shipped rule uses, so a pasted row cannot collide with the
// baked corpus (the bake refuses duplicates anyway — this makes it not happen).
func draftRuleID(it Item) string {
	app := slug(it.AppName)
	mn := slug(it.Mnemonic)
	switch {
	case app != "" && mn != "":
		return "draft." + app + "." + mn
	case app != "":
		return "draft." + app
	case mn != "":
		return "draft." + mn
	default:
		// template ids are `t-<10 hex>`; the hex tail is a legal id segment.
		return "draft.unclassified." + strings.TrimPrefix(it.TemplateID, "t-")
	}
}

// markerToken renders a mnemonic as an ingest-screen marker. The bake refuses a
// marker that is not UPPER-CASE (the screen matches an upper-cased
// classification token), and the value is device-derived text, so it is
// restricted to the marker alphabet [A-Z0-9_] rather than merely upper-cased.
// An empty result means "no marker", and the draft falls back to a
// pattern-only guard.
func markerToken(mnemonic string) string {
	var b strings.Builder
	for i := 0; i < len(mnemonic); i++ {
		c := mnemonic[i]
		switch {
		case c >= 'a' && c <= 'z':
			b.WriteByte(c - ('a' - 'A'))
		case c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '_':
			b.WriteByte(c)
		}
	}
	return b.String()
}

// slug reduces a vendor token to the id alphabet [a-z0-9_]. Empty in, empty
// out — the caller decides what an empty slug means.
func slug(s string) string {
	var b strings.Builder
	last := byte('_')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'A' && c <= 'Z':
			c += 'a' - 'A'
			fallthrough
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
			b.WriteByte(c)
			last = c
		default:
			if last != '_' && b.Len() > 0 {
				b.WriteByte('_')
				last = '_'
			}
		}
	}
	return strings.Trim(b.String(), "_")
}

// patternFromTemplate compiles a mined template into the message regex the
// drafted guard tests: literal tokens are quoted, `<*>` becomes `\S+`, and the
// gaps become `\s+` so whitespace runs in the original line do not defeat it.
//
// The output is deliberately UNANCHORED — the guard's `re` node searches the
// message, and anchoring a mined shape would break on any vendor that prefixes
// its own header.
//
// regexp.QuoteMeta escapes exactly the characters that are metacharacters in
// Python's `re` as well, and its escapes are valid Python, so the emitted
// pattern means the same thing on both sides of the bake.
func patternFromTemplate(template string) string {
	toks := strings.Fields(template)
	parts := make([]string, 0, len(toks))
	for _, t := range toks {
		if t == Wildcard {
			parts = append(parts, `\S+`)
			continue
		}
		parts = append(parts, regexp.QuoteMeta(t))
	}
	pat := strings.Join(parts, `\s+`)
	if len(pat) > maxPatternBytes {
		pat = pat[:maxPatternBytes]
		// A truncated regex may end mid-escape; drop a dangling backslash so
		// the emitted pattern is still syntactically valid.
		pat = strings.TrimRight(pat, `\`)
	}
	return pat
}

// yamlSingle renders a single-quoted YAML scalar. Single quotes are the right
// style for a regex: YAML performs NO escape processing inside them, so a
// backslash means a backslash. The only escape is a doubled quote.
func yamlSingle(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// yamlComment flattens a value onto one comment line. A device-supplied string
// reaching a comment must not be able to introduce a newline and forge YAML
// structure below it.
func yamlComment(s string) string {
	s = strings.NewReplacer("\r", " ", "\n", " ").Replace(s)
	return truncate(s, 200)
}

func orDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}
