// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Correlix

package metering

// report.go — the SIGNED USAGE REPORT.
//
// The owner's requirement is one sentence: "the customer and Correlix must
// derive the same counts independently". Everything in this file exists to make
// that literally true rather than a matter of trust.
//
//	1. the report carries the DAILY ROWS, not just a total, so the arithmetic
//	   can be redone by hand;
//	2. its bytes are CANONICAL, so two encoders produce the same signature
//	   input;
//	3. it is SIGNED by a per-installation key whose PUBLIC half travels in the
//	   report, so `correlix-licence usage-verify` needs nothing but the file;
//	4. nothing is sent anywhere. There is no phone-home in this package or in
//	   anything that calls it: the report is a file the customer downloads and
//	   chooses to share.
//
// # Canonicalisation (pinned by the golden test in report_test.go)
//
//	* JSON, UTF-8, NO whitespace between tokens;
//	* every object's keys SORTED by byte order, at every depth;
//	* no HTML escaping — `<`, `>` and `&` are written literally;
//	* numbers keep the exact literal Go's encoder produced for them;
//	* the `signature` field is absent from the signed bytes (a signature
//	  cannot cover itself).
//
// Sorted keys rather than a field-order mirror is a deliberate difference from
// the licence document. A licence has seven fields and one shape; a report
// grows a meter whenever the vocabulary does, and a hand-maintained mirror
// would silently stop covering the new one. Sorting is total over whatever the
// struct holds, so a field added tomorrow is signed tomorrow with no second
// place to remember.

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"
)

// ReportVersion identifies the document format. A verifier that does not know
// a version refuses rather than guessing at its meaning.
const ReportVersion = "correlix.usage-report/1"

// ReportScope names which of the two documents this is: the whole
// installation's usage, or one tenant's.
const (
	ReportScopePlatform = "platform"
	ReportScopeTenant   = "tenant"
)

// ReportKeyView is the signing identity, embedded in the report so the
// document verifies against itself.
//
// This is NOT the licence signing key. The licence key lives offline on
// Correlix's signing host and does not exist on a customer machine; this one is
// generated ON the installation at first use and never leaves it. They answer
// different questions — "did Correlix issue this licence" and "did this
// installation produce this report" — and using one key for both would mean a
// customer host holding the key that issues licences.
type ReportKeyView struct {
	// ID is the key fingerprint (licence.KeyID's construction: the first 8
	// bytes of the SHA-256, hex).
	ID string `json:"id"`
	// Base64 is the standard-base64 ed25519 public key.
	Base64 string `json:"base64"`
	// CreatedAt is when this installation generated the key.
	CreatedAt time.Time `json:"created_at"`
	// Note says what the key is and, more usefully, what it is not.
	Note string `json:"note"`
}

// ReportKeyNote is the sentence beside the key everywhere it is shown.
const ReportKeyNote = "Generated by this installation the first time a usage report was produced, and never sent anywhere. " +
	"It signs usage reports only; it is not the key Correlix signs licences with, and that key does not exist on this host."

// ReportLicence is the entitlement context a report is read against — enough to
// compare usage with what was bought, and nothing more.
type ReportLicence struct {
	Tier string `json:"tier"`
	// Customer and LicenceID identify the commercial agreement. PLATFORM SCOPE
	// ONLY: a tenant's report carries neither, because the customer's name and
	// their licence id are the provider's commercial terms, not the tenant's
	// (§3a rule 3 applied to the payload, not only to the gate).
	Customer  string `json:"customer,omitempty"`
	LicenceID string `json:"licence_id,omitempty"`
	// Devices is the monitored-device ceiling in force, so the primary meter
	// can be read against it without a second lookup. -1 means unlimited.
	Devices int `json:"device_ceiling"`
}

// Report is the downloadable document.
type Report struct {
	Version string `json:"version"`
	// Scope is ReportScopePlatform or ReportScopeTenant.
	Scope string `json:"scope"`
	// Tenant is set in a tenant-scoped report.
	Tenant string `json:"tenant,omitempty"`
	// GeneratedAt is when the document was produced (UTC).
	GeneratedAt time.Time `json:"generated_at"`
	// From and To are the inclusive UTC day bounds of the period.
	From string `json:"from"`
	To   string `json:"to"`
	// Licence is the entitlement context.
	Licence ReportLicence `json:"licence"`
	// Meters is the vocabulary as this build declares it, so a report read in
	// two years explains its own columns without the software that made it.
	Meters []ReportMeter `json:"meter_definitions"`
	// Days are the daily rows, in day then tenant order.
	Days []DailyRecord `json:"days"`
	// Totals is the period roll-up, using each meter's own aggregation.
	Totals Totals `json:"totals"`
	// Notes are the honest statements that belong with the numbers.
	Notes []string `json:"notes"`
	// Key is the signing identity.
	Key ReportKeyView `json:"key"`
	// Signature is standard base64 of the ed25519 signature over
	// CanonicalReportPayload. Absent from the signed bytes.
	Signature string `json:"signature,omitempty"`
}

// ReportMeter is one meter's definition as carried in the document.
type ReportMeter struct {
	Name        string      `json:"name"`
	Label       string      `json:"label"`
	Unit        string      `json:"unit"`
	Kind        Kind        `json:"kind"`
	Aggregation Aggregation `json:"aggregation"`
	Scope       Scope       `json:"scope"`
	Doc         string      `json:"doc"`
}

// ReportMeters returns the vocabulary in the document's shape.
func ReportMeters() []ReportMeter {
	out := make([]ReportMeter, 0, len(meters))
	for _, d := range meters {
		out = append(out, ReportMeter{
			Name: d.Name, Label: d.Label, Unit: d.Unit,
			Kind: d.Kind, Aggregation: d.Agg, Scope: d.Scope, Doc: d.Doc,
		})
	}
	return out
}

// The standing notes every report carries. They are part of the document
// because a number without them can be misread, and the person reading a
// report a year from now will not have this package to consult.
const (
	NoteConfigured  = "Monitored devices are counted from configuration — a device with at least one collector enabled — and never from recent telemetry. A device that stopped answering still counts; discovery does not consume the monitoring allowance."
	NoteNoPhoneHome = "Nothing in this report was sent anywhere. It was produced on the installation, signed by that installation's own key, and shared only if someone chose to share it."
	NoteDiagnostic  = "Diagnostic meters are recorded because they are useful, not because anything is charged for them. On-premises telemetry ingestion is not metered for money."
	NoteNotMeasured = "A meter with no value was NOT measured, and says why. It is never reported as zero: a zero means we counted and found none."
)

// StandingNotes returns the notes every report carries, in a fixed order.
func StandingNotes() []string {
	return []string{NoteConfigured, NoteNotMeasured, NoteDiagnostic, NoteNoPhoneHome}
}

// ─────────────────────────────────────────────────────────────────────────────
// Canonicalisation
// ─────────────────────────────────────────────────────────────────────────────

// CanonicalReportPayload is the exact byte sequence a signature covers: the
// report with its signature removed, encoded canonically (see the file header).
func CanonicalReportPayload(r Report) ([]byte, error) {
	r.Signature = ""
	return CanonicalJSON(r)
}

// CanonicalJSON encodes v with sorted object keys, no whitespace, UTF-8 and no
// HTML escaping.
//
// It works in two passes on purpose. The first marshals v the ordinary way; the
// second re-encodes the resulting generic tree, at which point every object is
// a map and Go's encoder sorts map keys for us. json.Number keeps each number's
// literal from the first pass, so a float never changes shape between the two.
func CanonicalJSON(v any) ([]byte, error) {
	first, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	dec := json.NewDecoder(bytes.NewReader(first))
	dec.UseNumber()
	var tree any
	if err := dec.Decode(&tree); err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(tree); err != nil {
		return nil, err
	}
	// Encode appends a newline; the canonical form has no trailing whitespace.
	return bytes.TrimRight(buf.Bytes(), "\n"), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Signing and verification
// ─────────────────────────────────────────────────────────────────────────────

// Errors a verifier distinguishes. They are separate values because "this file
// was modified" and "this file was signed by a key you do not have" are
// different problems with different answers.
var (
	// ErrReportMalformed — the bytes are not a well-formed usage report.
	ErrReportMalformed = errors.New("metering: malformed usage report")
	// ErrReportVersion — the document names a format this build does not know.
	ErrReportVersion = errors.New("metering: unknown usage-report version")
	// ErrReportSignature — the document did not authenticate against its key.
	ErrReportSignature = errors.New("metering: usage report signature does not verify")
	// ErrReportKeyMismatch — the embedded key id is not the fingerprint of the
	// embedded key, so the document is internally inconsistent.
	ErrReportKeyMismatch = errors.New("metering: usage report key id does not match its public key")
)

// SignReport signs r with priv and returns the completed document. The key view
// is filled from the private key's public half, so a report can never claim a
// key it was not signed with.
func SignReport(r Report, priv ed25519.PrivateKey, createdAt time.Time) (Report, error) {
	if len(priv) != ed25519.PrivateKeySize {
		return r, errors.New("metering: report signing key is not an ed25519 private key")
	}
	pub, ok := priv.Public().(ed25519.PublicKey)
	if !ok {
		return r, errors.New("metering: report signing key has no ed25519 public half")
	}
	r.Version = ReportVersion
	r.Key = ReportKeyView{
		ID:        Fingerprint(pub),
		Base64:    base64.StdEncoding.EncodeToString(pub),
		CreatedAt: createdAt.UTC(),
		Note:      ReportKeyNote,
	}
	payload, err := CanonicalReportPayload(r)
	if err != nil {
		return r, err
	}
	r.Signature = base64.StdEncoding.EncodeToString(ed25519.Sign(priv, payload))
	return r, nil
}

// VerifyReport parses and authenticates a report's bytes.
//
// It verifies against the key EMBEDDED in the document unless `pub` is
// supplied, in which case that key must be the one that signed it. Both modes
// matter: the embedded key proves the file is internally consistent and
// unmodified, and an out-of-band key proves it came from the installation you
// think it did. `correlix-licence usage-verify` offers both and says which one
// it used.
func VerifyReport(raw []byte, pub ed25519.PublicKey) (Report, error) {
	var r Report
	if err := json.Unmarshal(raw, &r); err != nil {
		return Report{}, fmt.Errorf("%w: %w", ErrReportMalformed, err)
	}
	if r.Version != ReportVersion {
		return r, fmt.Errorf("%w: %q (this build reads %q)", ErrReportVersion, r.Version, ReportVersion)
	}
	embedded, err := base64.StdEncoding.DecodeString(r.Key.Base64)
	if err != nil || len(embedded) != ed25519.PublicKeySize {
		return r, fmt.Errorf("%w: the embedded public key is not a %d-byte ed25519 key", ErrReportMalformed, ed25519.PublicKeySize)
	}
	if Fingerprint(embedded) != r.Key.ID {
		return r, ErrReportKeyMismatch
	}
	check := ed25519.PublicKey(embedded)
	if len(pub) == ed25519.PublicKeySize {
		if !bytes.Equal(pub, embedded) {
			return r, fmt.Errorf("%w: the report was signed by key %s, not by the key supplied", ErrReportSignature, r.Key.ID)
		}
		check = pub
	}
	sig, err := base64.StdEncoding.DecodeString(r.Signature)
	if err != nil {
		return r, fmt.Errorf("%w: the signature is not base64", ErrReportMalformed)
	}
	payload, err := CanonicalReportPayload(r)
	if err != nil {
		return r, err
	}
	if !ed25519.Verify(check, payload, sig) {
		return r, ErrReportSignature
	}
	return r, nil
}

// RecomputeTotals re-derives a report's period roll-up from its own daily rows.
//
// This is the independence check: a verifier does not have to trust the
// `totals` block, it recomputes it from the days and compares. A report whose
// totals do not follow from its own rows is a report nobody should act on, and
// saying which meter disagrees is more useful than a bare refusal.
func RecomputeTotals(r Report) ([]MeterValue, []string) {
	want := RollUp(r.Days)
	byName := make(map[string]MeterValue, len(want))
	for _, mv := range want {
		byName[mv.Meter] = mv
	}
	var disagree []string
	for _, got := range r.Totals.Meters {
		exp, ok := byName[got.Meter]
		switch {
		case !ok:
			disagree = append(disagree, got.Meter+": in the totals but not derivable from the daily rows")
		case (exp.Value == nil) != (got.Value == nil):
			disagree = append(disagree, got.Meter+": measured in one of the totals and the rows but not the other")
		case exp.Value != nil && *exp.Value != *got.Value:
			disagree = append(disagree, fmt.Sprintf("%s: totals say %v, the daily rows give %v", got.Meter, *got.Value, *exp.Value))
		}
	}
	sort.Strings(disagree)
	return want, disagree
}
