package metering

// report_test.go — the signed document.
//
// The GOLDEN TEST below is the load-bearing one. It pins the exact canonical
// bytes for a fixed document, so a future change to a struct tag, a field
// order, an encoder setting or a Go version that altered them would fail here
// rather than silently invalidating every report a customer already holds.

import (
	"crypto/ed25519"
	"encoding/json"
	"strings"
	"testing"
	"time"
)

// deterministicKey is a fixed ed25519 key derived from a constant seed. Tests
// need a stable signature; production never uses this path (ReportKey draws
// from crypto/rand).
func deterministicKey() ed25519.PrivateKey {
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i + 1)
	}
	return ed25519.NewKeyFromSeed(seed)
}

func sampleReport() Report {
	one, two := 12.0, 25.0
	return Report{
		Version: ReportVersion, Scope: ReportScopePlatform,
		GeneratedAt: day("2026-09-05T12:00:00Z"),
		From:        "2026-09-04", To: "2026-09-05",
		Licence: ReportLicence{Tier: "team", Customer: "Acme <Networks> & Co", LicenceID: "lic-1", Devices: 250},
		Meters:  nil, // pinned separately: the vocabulary grows, the envelope must not
		Days: []DailyRecord{{
			Day: "2026-09-05", TenantID: "acme", Samples: 2,
			UpdatedAt: day("2026-09-05T02:00:00Z"),
			Meters: map[string]MeterValue{
				MeterMonitoredDevicesUnique: {Meter: MeterMonitoredDevicesUnique, Value: &one, Unit: UnitDevices, Source: SourceConfiguration, Samples: 2},
				MeterTraceSpans:             {Meter: MeterTraceSpans, Unit: UnitRecords, Source: SourceNotMeasured, Reason: "no trace pipeline is configured"},
			},
		}},
		Totals: Totals{From: "2026-09-04", To: "2026-09-05", Days: 1, Meters: []MeterValue{
			{Meter: MeterMonitoredDevicesPeak, Value: &two, Unit: UnitDevices, Source: SourceConfiguration, Samples: 2},
		}},
		Notes: StandingNotes(),
	}
}

// goldenCanonical is the exact signed byte sequence for sampleReport().
//
// DO NOT REGENERATE THIS TO MAKE A TEST PASS. If it changes, the format
// changed, and every report already in a customer's hands stopped verifying —
// which is a new ReportVersion, not an edit to this constant.
const goldenCanonical = `{"days":[{"day":"2026-09-05","meters":{"monitored_devices_unique":{"meter":"monitored_devices_unique","samples":2,"source":"configuration","unit":"monitored_devices","value":12},"trace_accepted_spans":{"meter":"trace_accepted_spans","reason":"no trace pipeline is configured","samples":0,"source":"not_measured","unit":"records","value":null}},"samples":2,"tenant_id":"acme","updated_at":"2026-09-05T02:00:00Z"}],"from":"2026-09-04","generated_at":"2026-09-05T12:00:00Z","key":{"base64":"ebVWLo/mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ=","created_at":"2026-09-05T00:00:00Z","id":"65b60673d6ed884b","note":"Generated by this installation the first time a usage report was produced, and never sent anywhere. It signs usage reports only; it is not the key Correlix signs licences with, and that key does not exist on this host."},"licence":{"customer":"Acme <Networks> & Co","device_ceiling":250,"licence_id":"lic-1","tier":"team"},"meter_definitions":null,"notes":["Monitored devices are counted from configuration — a device with at least one collector enabled — and never from recent telemetry. A device that stopped answering still counts; discovery does not consume the monitoring allowance.","A meter with no value was NOT measured, and says why. It is never reported as zero: a zero means we counted and found none.","Diagnostic meters are recorded because they are useful, not because anything is charged for them. On-premises telemetry ingestion is not metered for money.","Nothing in this report was sent anywhere. It was produced on the installation, signed by that installation's own key, and shared only if someone chose to share it."],"scope":"platform","to":"2026-09-05","totals":{"days":1,"from":"2026-09-04","meters":[{"meter":"monitored_devices_peak","samples":2,"source":"configuration","unit":"monitored_devices","value":25}],"to":"2026-09-05"},"version":"correlix.usage-report/1"}`

func TestCanonicalPayloadIsPinned(t *testing.T) {
	signed, err := SignReport(sampleReport(), deterministicKey(), day("2026-09-05T00:00:00Z"))
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	got, err := CanonicalReportPayload(signed)
	if err != nil {
		t.Fatalf("canonicalise: %v", err)
	}
	if string(got) != goldenCanonical {
		t.Fatalf("the canonical form changed.\n got: %s\nwant: %s\n\n"+
			"Do NOT update the constant to match. A changed canonical form means every "+
			"usage report already issued has stopped verifying, which is a new "+
			"ReportVersion and a migration, not an edit to a test.", got, goldenCanonical)
	}
}

func TestCanonicalisationRules(t *testing.T) {
	got := string(mustCanonical(t, sampleReport()))
	// No whitespace BETWEEN tokens. Checked structurally rather than by
	// scanning for spaces, because the prose inside the notes is full of them.
	if strings.ContainsAny(got, "\n\t") {
		t.Errorf("the canonical form contains a newline or a tab")
	}
	if strings.Contains(got, `":`+" ") || strings.Contains(got, `,`+" \"") {
		t.Errorf("the canonical form pads its separators")
	}
	// No HTML escaping: the escape SEQUENCES must be absent and the literal
	// characters present.
	for _, esc := range []string{`\u003c`, `\u003e`, `\u0026`} {
		if strings.Contains(got, esc) {
			t.Errorf("the canonical form HTML-escaped a string (%s); `<`, `>` and `&` are written literally", esc)
		}
	}
	if !strings.Contains(got, `"Acme <Networks> & Co"`) {
		t.Errorf("the literal `<` and `&` did not survive canonicalisation")
	}
	// Sorted keys at every depth: `days` precedes `from` precedes `generated_at`.
	di, fi, gi := strings.Index(got, `"days"`), strings.Index(got, `"from"`), strings.Index(got, `"generated_at"`)
	if !(di < fi && fi < gi) {
		t.Errorf("top-level object keys are not sorted (days=%d from=%d generated_at=%d)", di, fi, gi)
	}
	// And the signature is never in the signed bytes.
	if strings.Contains(got, `"signature"`) {
		t.Errorf("the canonical payload includes the signature field — a signature cannot cover itself")
	}
}

func TestCanonicalisationIsStableUnderReformatting(t *testing.T) {
	signed, err := SignReport(sampleReport(), deterministicKey(), day("2026-09-05T00:00:00Z"))
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	pretty, err := json.MarshalIndent(signed, "", "\t")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	// An operator who pretty-printed the file, or whose editor reordered the
	// keys, must still be able to verify it.
	if _, err := VerifyReport(pretty, nil); err != nil {
		t.Fatalf("a re-formatted report did not verify: %v", err)
	}
}

func TestVerifyRejectsATamperedReport(t *testing.T) {
	signed, err := SignReport(sampleReport(), deterministicKey(), day("2026-09-05T00:00:00Z"))
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	raw, err := json.Marshal(signed)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	tampered := strings.Replace(string(raw), `"value":12`, `"value":2`, 1)
	if tampered == string(raw) {
		t.Fatalf("the tamper did not change the document — the test proves nothing")
	}
	if _, err := VerifyReport([]byte(tampered), nil); err == nil {
		t.Fatalf("a report whose numbers were edited still verified")
	}
}

func TestVerifyRejectsAnInconsistentKeyAndAnUnknownVersion(t *testing.T) {
	signed, _ := SignReport(sampleReport(), deterministicKey(), day("2026-09-05T00:00:00Z"))

	bad := signed
	bad.Key.ID = "0000000000000000"
	raw, _ := json.Marshal(bad)
	if _, err := VerifyReport(raw, nil); err == nil {
		t.Errorf("a report whose key id does not match its key verified")
	}

	old := signed
	old.Version = "correlix.usage-report/0"
	raw, _ = json.Marshal(old)
	if _, err := VerifyReport(raw, nil); err == nil {
		t.Errorf("a report in an unknown format verified")
	}
}

func TestVerifyAgainstAnOutOfBandKey(t *testing.T) {
	priv := deterministicKey()
	signed, _ := SignReport(sampleReport(), priv, day("2026-09-05T00:00:00Z"))
	raw, _ := json.Marshal(signed)

	pub, ok := priv.Public().(ed25519.PublicKey)
	if !ok {
		t.Fatalf("no public half")
	}
	if _, err := VerifyReport(raw, pub); err != nil {
		t.Fatalf("verification against the correct out-of-band key failed: %v", err)
	}
	otherSeed := make([]byte, ed25519.SeedSize)
	otherSeed[0] = 99
	otherPub, ok := ed25519.NewKeyFromSeed(otherSeed).Public().(ed25519.PublicKey)
	if !ok {
		t.Fatalf("no public half")
	}
	if _, err := VerifyReport(raw, otherPub); err == nil {
		t.Errorf("verification against the WRONG out-of-band key succeeded")
	}
}

func TestRecomputeTotalsIsTheIndependenceCheck(t *testing.T) {
	rows := []DailyRecord{}
	for _, d := range []string{"2026-09-04", "2026-09-05"} {
		row := DailyRecord{Day: d, TenantID: "acme"}
		row, err := Fold(row, []Reading{Counted(MeterDEMChecks, "acme", 100)}, day(d+"T01:00:00Z"))
		if err != nil {
			t.Fatalf("fold: %v", err)
		}
		rows = append(rows, row.Seal())
	}
	good := Report{Days: rows, Totals: Totals{Meters: RollUp(rows)}}
	if _, bad := RecomputeTotals(good); len(bad) != 0 {
		t.Fatalf("an honest report disagreed with itself: %v", bad)
	}

	wrong := 1.0
	tampered := good
	tampered.Totals = Totals{Meters: []MeterValue{{Meter: MeterDEMChecks, Value: &wrong, Unit: UnitChecks, Source: SourceCounter}}}
	_, disagree := RecomputeTotals(tampered)
	if len(disagree) == 0 {
		t.Fatalf("a report whose totals do not follow from its rows was accepted")
	}
	if !strings.Contains(disagree[0], MeterDEMChecks) {
		t.Errorf("the disagreement does not name the meter: %q", disagree[0])
	}
}

func TestReportFileNameIsDeterministic(t *testing.T) {
	p := Report{Scope: ReportScopePlatform, From: "2026-08-01", To: "2026-08-31"}
	if got, want := ReportFileName(p), "correlix-usage-2026-08-01_2026-08-31.json"; got != want {
		t.Errorf("platform report name = %q, want %q", got, want)
	}
	tt := Report{Scope: ReportScopeTenant, Tenant: "Acme/Corp", From: "2026-08-01", To: "2026-08-31"}
	if got, want := ReportFileName(tt), "correlix-usage-2026-08-01_2026-08-31-acme-corp.json"; got != want {
		t.Errorf("tenant report name = %q, want %q", got, want)
	}
}

func mustCanonical(t *testing.T, r Report) []byte {
	t.Helper()
	signed, err := SignReport(r, deterministicKey(), day("2026-09-05T00:00:00Z"))
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	got, err := CanonicalReportPayload(signed)
	if err != nil {
		t.Fatalf("canonicalise: %v", err)
	}
	return got
}

var _ = time.Time{}
