// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Correlix

package tac

// templatedefaults.go — the CORRELIX DEFAULT command templates.
//
// "We provide some defaults model. But give flexibility to customer and change
// how they want to build that." (owner, 2026-09-05). This file is the defaults
// half: it DERIVES them from the authored plans that already exist rather than
// re-typing a second copy of the same knowledge, so a plan change and its
// default template can never drift apart.
//
// GENERATION, exactly:
//
//	for each dialect that has an authored plan:
//	  · one BASELINE template — the dialect's own `baseline:` intent list, in
//	    authoring order, one step per BOUND intent whose rendered command carries
//	    no unfilled placeholder.
//	  · one template per ISSUE CLASS that binds at least one deep-dive intent on
//	    that dialect — the baseline steps followed by the class's bound intents,
//	    which is the plan an operator would have got for that class with no
//	    target supplied.
//
// WHAT IS DELIBERATELY LEFT OUT of a default, and why:
//
//	· CONSENT commands (`admin tech-support`, `display diagnostic-information`).
//	  The vendor says they are not routine; a default template that carried one
//	  would be Correlix pre-approving something only a human may approve.
//	· OPTIONAL commands (`show tech-support`). They are off by default in the
//	  plan for size and time; a default template must not turn them on.
//	· TARGETED commands — a binding whose template still holds a `{peer}` /
//	  `{prefix}` / `{if}` placeholder after rendering with an EMPTY target. A
//	  template is a saved command set, not a plan: it has no incident to take an
//	  interface name from, and shipping `show ip bgp neighbors` with the peer
//	  silently dropped would be a different command than the one the plan runs.
//	· Session-scoped setters (they carry a Teardown). They are admitted only as
//	  a read PLUS its teardown, which the collector pairs; a flat command list
//	  cannot express the pair, so a default never carries one.
//
// DETERMINISM is a property this file must have and a test asserts: the same
// catalog always yields the same templates, in the same order, with the same
// ids. A default's id is `correlix:<dialect>:<class-or-baseline>` — stable
// across builds, so a tenant template that forked one can still name its parent
// after an upgrade.

import "strings"

// DefaultTemplateVersion is the version stamped on every Correlix default. It is
// 1 and stays 1: a default is not edited in place, it is REPLACED by the next
// release's generation, and the release is identified by the plan version each
// template carries in its description. Incrementing it here would imply an
// upgrade path that does not exist.
const DefaultTemplateVersion = 1

// defaultTemplatePrefix is the id namespace. A tenant id can never collide with
// it: tplIDRE admits the colon, but the store REFUSES a tenant write whose
// id it did not mint itself.
const defaultTemplatePrefix = "correlix:"

// DefaultTemplates generates the read-only Correlix templates from a catalog, in
// a stable order (dialect, then baseline, then class in taxonomy order).
//
// A nil catalog yields no templates rather than an error: the caller has already
// been told the catalog is unavailable, and a second error at this seam would
// only obscure the first.
func (c *Catalog) DefaultTemplates() []Template {
	out := []Template{}
	if c == nil {
		return out
	}
	for _, dialect := range c.planOrder {
		dp := c.plans[dialect]
		if dp == nil {
			continue
		}
		base := c.defaultSteps(dp, dp.Baseline)
		if len(base) > 0 {
			out = append(out, Template{
				ID:      defaultTemplatePrefix + dialect + ":baseline",
				Dialect: dialect,
				Name:    dp.Display + " — TAC baseline",
				Description: "The outputs every " + dp.Display + " TAC case starts from: version, inventory, " +
					"environment, interface state, routing summary and recent logs. Generated by Correlix from " +
					"the authored plan " + dp.Version + ".",
				Source:  SourceCorrelixDefault,
				Steps:   base,
				Version: DefaultTemplateVersion,
			})
		}
		for _, classID := range c.classOrder {
			cl := c.classes[classID]
			deep := c.defaultSteps(dp, cl.Intents)
			if len(deep) == 0 {
				continue
			}
			steps := make([]TemplateStep, 0, len(base)+len(deep))
			seen := map[string]bool{}
			for _, s := range append(append([]TemplateStep{}, base...), deep...) {
				k := normCommandKey(s.Command)
				if seen[k] {
					continue
				}
				seen[k] = true
				steps = append(steps, s)
			}
			desc := "Correlix's " + dp.Display + " command set for " + strings.ToLower(cl.Title) +
				": the vendor baseline plus the class deep dive. Generated from the authored plan " + dp.Version + "."
			if cl.TACFirstLook != "" {
				desc += " What TAC opens first: " + cl.TACFirstLook
			}
			out = append(out, Template{
				ID:          defaultTemplatePrefix + dialect + ":" + classID,
				Dialect:     dialect,
				Name:        dp.Display + " — " + cl.Title,
				Description: clip(desc, maxTemplateTextBytes),
				Source:      SourceCorrelixDefault,
				Steps:       steps,
				Version:     DefaultTemplateVersion,
			})
		}
	}
	return out
}

// defaultSteps renders the bound, untargeted, non-consent, non-teardown subset
// of an intent list into template steps.
func (c *Catalog) defaultSteps(dp *DialectPlan, intents []string) []TemplateStep {
	out := []TemplateStep{}
	seen := map[string]bool{}
	for _, intent := range intents {
		if seen[intent] {
			continue
		}
		seen[intent] = true
		b, ok := dp.Bound(intent)
		if !ok || b.Consent || b.Teardown != "" {
			continue
		}
		cmd := renderCommand(b.Command, dp.Dialect, Target{})
		if cmd == "" || hasUnfilledPlaceholder(b.Command) {
			continue
		}
		title := intent
		if in, ok := c.Intent(intent); ok && in.Title != "" {
			title = in.Title
		}
		sec := SectionDeepDive
		for _, base := range dp.Baseline {
			if base == intent {
				sec = SectionBaseline
				break
			}
		}
		out = append(out, TemplateStep{Intent: intent, Title: title, Command: cmd, Section: sec})
	}
	return out
}

// hasUnfilledPlaceholder reports a template that needs an argument this default
// cannot supply. It checks the CLOSED placeholder vocabulary rather than any
// `{…}` run, because a literal brace is a literal (tac.go: an unknown token is
// treated as text, so a typo fails closed rather than opening a wildcard).
func hasUnfilledPlaceholder(tmpl string) bool {
	for ph := range placeholders {
		if strings.Contains(tmpl, ph) {
			return true
		}
	}
	return false
}

// IsDefaultTemplateID reports whether an id names a Correlix default. It is the
// one place the namespace rule is written down.
func IsDefaultTemplateID(id string) bool { return strings.HasPrefix(id, defaultTemplatePrefix) }

// DefaultTemplate looks one default up by id.
func (c *Catalog) DefaultTemplate(id string) (Template, bool) {
	for _, t := range c.DefaultTemplates() {
		if t.ID == id {
			return t, true
		}
	}
	return Template{}, false
}

// DefaultTemplatesFor returns the defaults for one dialect. An unknown dialect
// yields an empty list, which is the honest answer: Correlix has authored no
// commands for that platform, so it ships no default set for it.
func (c *Catalog) DefaultTemplatesFor(dialect string) []Template {
	out := []Template{}
	for _, t := range c.DefaultTemplates() {
		if t.Dialect == dialect {
			out = append(out, t)
		}
	}
	return out
}

// TemplateDiff is one difference between a tenant template and the default it
// was forked from. It is what the Knowledge view renders.
type TemplateDiff struct {
	Kind    EditKind `json:"kind"`
	Command string   `json:"command"`
	Intent  string   `json:"intent,omitempty"`
}

// DiffAgainstDefault compares a tenant template with its parent default. A
// template with no parent (or a parent this build no longer ships) returns
// ok=false — an honest "nothing to compare", never an empty diff that would read
// as "identical".
func (c *Catalog) DiffAgainstDefault(t Template) ([]TemplateDiff, bool) {
	if t.BasedOn == "" {
		return nil, false
	}
	parent, ok := c.DefaultTemplate(t.BasedOn)
	if !ok {
		return nil, false
	}
	inParent := map[string]TemplateStep{}
	parentOrder := make([]string, 0, len(parent.Steps))
	for _, s := range parent.Steps {
		k := normCommandKey(s.Command)
		if _, dup := inParent[k]; !dup {
			parentOrder = append(parentOrder, k)
		}
		inParent[k] = s
	}
	mine := map[string]bool{}
	out := []TemplateDiff{}
	for _, s := range t.Steps {
		k := normCommandKey(s.Command)
		mine[k] = true
		if _, ok := inParent[k]; !ok {
			out = append(out, TemplateDiff{Kind: EditAdded, Command: s.Command, Intent: s.Intent})
		}
	}
	for _, k := range parentOrder {
		if !mine[k] {
			s := inParent[k]
			out = append(out, TemplateDiff{Kind: EditRemoved, Command: s.Command, Intent: s.Intent})
		}
	}
	return out, true
}
