#!/usr/bin/env python3
"""Generate the Reference pages that must never drift from the code.

Three pages are machine-written from the source of truth and must not be edited
by hand:

    docs/reference/api.md            <- src/backend/internal/openapi/openapi.go
    docs/reference/feature-flags.md  <- the FEATURE_*/ENABLE_* reads in src/backend
                                        plus the defaults in the shipped compose file
    docs/reference/alert-rules.md    <- src/config/rules.yaml, rules-scale-slo.yaml

Run it from anywhere:

    python3 docs-portal/scripts/generate-reference.py

It rewrites the three pages in place and prints what changed. It reads only
checked-in source; it never contacts a running stack.
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PORTAL = ROOT / "docs-portal" / "docs" / "reference"
OPENAPI = ROOT / "src" / "backend" / "internal" / "openapi" / "openapi.go"
COMPOSE = ROOT / "deployment" / "docker" / "docker-compose.yml"
BACKEND = ROOT / "src" / "backend"
RULES = [ROOT / "src" / "config" / "rules.yaml",
         ROOT / "src" / "config" / "rules-scale-slo.yaml"]

BANNER = ("<!-- GENERATED by docs-portal/scripts/generate-reference.py. "
          "Do not edit by hand; rerun the script. -->")


# ─────────────────────────────── API reference ──────────────────────────────

ROUTE_RE = re.compile(
    r'\{"(GET|POST|PUT|PATCH|DELETE)",\s*"([^"]+)",\s*"([^"]+)",\s*'
    r'((?:"(?:[^"\\]|\\.)*"\s*\+?\s*)+)\}',
    re.S,
)
STRING_RE = re.compile(r'"((?:[^"\\]|\\.)*)"')


def go_strings(chunk: str) -> str:
    """Join a Go concatenated-string literal into one Python string."""
    parts = [m.group(1) for m in STRING_RE.finditer(chunk)]
    return "".join(parts).replace('\\"', '"').replace("\\\\", "\\")


def read_routes() -> list[tuple[str, str, str, str]]:
    src = OPENAPI.read_text(encoding="utf-8")
    start = src.index("var apiRoutes")
    end = src.index("\n}\n", start)
    body = src[start:end]
    routes = []
    for m in ROUTE_RE.finditer(body):
        routes.append((m.group(1), m.group(2), m.group(3), go_strings(m.group(4))))
    if not routes:
        sys.exit("no routes parsed out of openapi.go — the literal shape changed")
    return routes


def md_cell(text: str) -> str:
    """One table cell, safe for MDX.

    Docusaurus parses Markdown through MDX, which reads a bare `{...}` as a
    JavaScript expression. Alert summaries carry `{{ $value }}` and route
    summaries carry `{framework_id, enabled}`, so braces and angle brackets
    OUTSIDE inline code are escaped to HTML entities. Braces inside backticks are left alone: MDX does
    not parse expressions there, and escaping them would print the entity.
    """
    text = text.replace("|", "\\|").replace("\n", " ").strip()
    out, in_code = [], False
    for ch in text:
        if ch == "`":
            in_code = not in_code
            out.append(ch)
        elif ch == "{" and not in_code:
            out.append("&#123;")
        elif ch == "}" and not in_code:
            out.append("&#125;")
        elif ch == "<" and not in_code:
            # MDX reads a bare `<` as the start of a JSX tag, and rule
            # expressions carry things like `z<-3`.
            out.append("&lt;")
        elif ch == ">" and not in_code:
            out.append("&gt;")
        else:
            out.append(ch)
    return "".join(out)


def gen_api(routes) -> str:
    by_tag: dict[str, list] = {}
    for method, path, tag, summary in routes:
        by_tag.setdefault(tag, []).append((method, path, summary))

    out = ["---", "title: REST API reference",
           "description: Every documented operation on the Correlix REST API, "
           "generated from the same route table the server publishes at "
           "/api/openapi.json.",
           "page_type: reference",
           "sidebar_position: 20", "---", "", BANNER, "",
           "# REST API reference", "",
           f"Correlix publishes {len(routes)} documented operations across "
           f"{len(by_tag)} groups. The table below is generated from the route "
           "table the server itself serves, so it cannot drift from the running "
           "API.", "",
           "Fetch the machine-readable document from your own deployment:", "",
           "```bash",
           'curl -s -H "Authorization: Bearer $TOKEN" \\',
           "  http://localhost:8000/api/openapi.json",
           "```", "",
           "## Authentication", "",
           "Every operation takes one of two credentials in the "
           "`Authorization` header:", "",
           "| Credential | Header | Obtained from |",
           "|---|---|---|",
           "| Access token (JWT) | `Authorization: Bearer <jwt>` | "
           "`POST /api/auth/login` |",
           "| API key | `Authorization: Bearer ntk_…` or `X-API-Key: ntk_…` | "
           "**Administration → API Access** |", "",
           "A request without a credential is refused with `401` and the body "
           "`{\"error\":\"missing bearer token\"}`.", ""]

    for tag in sorted(by_tag):
        out += [f"## {tag}", "", "| Method | Path | What it does |", "|---|---|---|"]
        for method, path, summary in sorted(by_tag[tag], key=lambda r: (r[1], r[0])):
            out.append(f"| `{method}` | `{md_cell(path)}` | {md_cell(summary)} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# ────────────────────────────── Feature flags ───────────────────────────────

FLAG_READ_RE = re.compile(
    r'(?:os\.Getenv|envBool)\("((?:FEATURE|ENABLE)_[A-Z_0-9]+)"\)')
FLAG_CONST_RE = re.compile(
    r'Env\w*\s*=\s*"((?:FEATURE|ENABLE)_[A-Z_0-9]+)"')


def read_flags() -> list[str]:
    found: set[str] = set()
    for path in BACKEND.rglob("*.go"):
        if path.name.endswith("_test.go"):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        found.update(FLAG_READ_RE.findall(text))
        found.update(FLAG_CONST_RE.findall(text))
    return sorted(found)


def compose_defaults() -> dict[str, str]:
    text = COMPOSE.read_text(encoding="utf-8", errors="replace")
    out: dict[str, str] = {}
    for m in re.finditer(
            r'^\s+((?:FEATURE|ENABLE)_[A-Z_0-9]+):\s*\$\{[A-Z_0-9]+:-([^}]*)\}',
            text, re.M):
        out.setdefault(m.group(1), m.group(2) or "(empty)")
    return out


FLAG_NOTES = {
    "ENABLE_BGPLS_DISCOVERY": "Learn topology from BGP-LS.",
    "ENABLE_CDP_DISCOVERY": "Learn neighbours from CDP.",
    "ENABLE_GNMI_COLLECTION": "Subscribe to gNMI streaming telemetry.",
    "ENABLE_LLDP_DISCOVERY": "Learn neighbours from LLDP.",
    "ENABLE_NETCONF_COLLECTION": "Poll device state over NETCONF.",
    "ENABLE_REPORT_SCHEDULER": "Run scheduled reports.",
    "ENABLE_SEAM_BOOTSTRAP": "Seed the seam catalogue on first start.",
    "ENABLE_SNMP_COLLECTION": "Poll devices over SNMP v2c and v3.",
    "ENABLE_SNMP_DISCOVERY": "Sweep subnets for SNMP-speaking devices.",
    "ENABLE_SNMP_METRICS": "Collect the SNMP metric families.",
    "ENABLE_TUNNEL_DISCOVERY": "Discover IPsec, GRE and SD-WAN tunnels.",
    "ENABLE_VENDOR_DETECTION": "Identify vendor and OS from sysObjectID.",
    "FEATURE_ACTIVE_PROBE": "Send STAMP active-measurement probes.",
    "FEATURE_ACTIVE_VERIFICATION": "Verify a recovery before closing a case.",
    "FEATURE_AI": "Master switch for the Iris assistant.",
    "FEATURE_AI_TOOLS": "Let Iris call read-only platform tools.",
    "FEATURE_BGP_ALERTS": "Evaluate the BGP watchlist and raise routing alerts.",
    "FEATURE_BGP_BOGON_FEED": "Add the Team Cymru full-bogons feed to the "
                              "embedded IANA special-purpose blocks.",
    "FEATURE_BGP_LIVE_FEED": "Keep a bounded per-tenant ring of live BGP updates.",
    "FEATURE_BMP": "Accept BMP sessions from routers that push their Adj-RIB-In.",
    "FEATURE_CLOUD_SIGNAL_NOTIFICATIONS": "Notify on cloud-provider events.",
    "FEATURE_CONFIG_BACKUP": "Capture, store and diff device configurations.",
    "FEATURE_COPILOT": "Expose the assistant chat endpoint.",
    "FEATURE_DEVICE_SSH": "Proxy an interactive SSH session to a device.",
    "FEATURE_EMAIL_NOTIFICATIONS": "Deliver notifications over SMTP.",
    "FEATURE_ITSM_INBOUND": "Accept ticket updates back from the ITSM system.",
    "FEATURE_ITSM_RECONCILE": "Reconcile ticket state that drifted.",
    "FEATURE_JIRA_NOTIFICATIONS": "File Jira issues.",
    "FEATURE_LEGACY_ALERT_ITSM": "Keep the pre-policy alert-to-ticket path.",
    "FEATURE_NMS_INTEGRATIONS": "Import inventory from a vendor NMS.",
    "FEATURE_NTFY_NOTIFICATIONS": "Push notifications through ntfy.",
    "FEATURE_PACKET_CAPTURE": "Run bounded on-device packet captures.",
    "FEATURE_PAGERDUTY_NOTIFICATIONS": "Page through PagerDuty.",
    "FEATURE_PATH_BASELINES": "Baseline path latency and loss.",
    "FEATURE_PATH_GRAPH": "Resolve hop-by-hop path graphs.",
    "FEATURE_PORT_DOM": "Read optical transceiver diagnostics.",
    "FEATURE_PROCESSORS": "Expose the ingest processor admin surface.",
    "FEATURE_PROTOCOL_DIAG_COLLECT": "Run a diagnostic command bundle against a "
                                     "live device over SSH.",
    "FEATURE_RCA_TICKETING": "Open a ticket automatically from an RCA case.",
    "FEATURE_SEALED_FIELDS": "Seal reversible secrets at rest under the tenant key.",
    "FEATURE_SECURITY_LANE": "Run the security producer lane and scans.",
    "FEATURE_SERVICENOW_NOTIFICATIONS": "File ServiceNow incidents.",
    "FEATURE_SLACK_NOTIFICATIONS": "Post to Slack.",
    "FEATURE_SNMP_TRAPS": "Receive SNMP traps on UDP/162.",
    "FEATURE_SNS_NOTIFICATIONS": "Publish to Amazon SNS.",
    "FEATURE_STAMP_REFLECTOR": "Answer STAMP probes as a reflector.",
    "FEATURE_SVC_FLOW_ROLLUP": "Roll flows up to services.",
    "FEATURE_SYNTHETICS": "Run synthetic HTTP and DNS checks.",
    "FEATURE_TEAMS_NOTIFICATIONS": "Post to Microsoft Teams.",
    "FEATURE_TRACEROUTE": "Run the traceroute collector (needs CAP_NET_RAW).",
    "FEATURE_TWILIO_NOTIFICATIONS": "Send SMS through Twilio.",
    "FEATURE_UNIFI": "Collect from a UniFi controller.",
    "FEATURE_WAN_ECHO": "Measure WAN circuits with echo probes.",
    "FEATURE_WIRELESS_ACTIONS": "Allow guarded wireless remediation actions.",
}


def gen_flags(flags, defaults) -> str:
    out = ["---", "title: Feature flags",
           "description: Every FEATURE_ and ENABLE_ switch Correlix reads, with "
           "the default the shipped compose file sets.",
           "page_type: reference",
           "sidebar_position: 30", "---", "", BANNER, "",
           "# Feature flags", "",
           "Correlix reads every optional capability from an environment "
           "variable. Set them in `deployment/docker/.env` and restart the "
           "affected service.", "",
           "Two rules hold for all of them:", "",
           "- A flag is read as the exact string `true`. Any other value, "
           "including `TRUE` and `1`, leaves the feature off.",
           "- An optional MODULE whose flag is off registers no routes at "
           "all, so its API paths answer `404` and the feature is not "
           "enumerable from outside. This holds for the security lane, "
           "configuration backup, packet capture, the BMP receiver and the "
           "protocol-diagnostics collector. It does not hold for every flag: "
           "some gate a collector or a worker while their read routes stay "
           "registered and answer honestly that the capability is off.", "",
           "| Flag | Default | What it turns on |", "|---|---|---|"]
    for f in flags:
        d = defaults.get(f, "not set")
        note = FLAG_NOTES.get(f, "")
        out.append(f"| `{f}` | `{d}` | {note} |")
    out += ["",
            "## Related", "",
            "- [Optional modules](/deploy/optional-modules): the flags that "
            "need more than a `true`, and what each one needs.",
            "- [REST API reference](/reference/api): which routes each module "
            "registers."]
    return "\n".join(out).rstrip() + "\n"


# ────────────────────────────── Alert rules ─────────────────────────────────

def read_rules():
    rows = []
    for path in RULES:
        if not path.exists():
            continue
        name = None
        labels = {}
        summary = ""
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            m = re.match(r'\s*-\s*alert:\s*(\S+)', line)
            if m:
                if name:
                    rows.append((name, labels, summary, path.name))
                name, labels, summary = m.group(1), {}, ""
                continue
            if name is None:
                continue
            m = re.match(r'\s*labels:\s*\{(.+)\}', line)
            if m:
                for pair in m.group(1).split(","):
                    if ":" in pair:
                        k, v = pair.split(":", 1)
                        labels[k.strip()] = v.strip().strip('"')
                continue
            m = re.match(r'\s*(severity|layer|tier):\s*(\S+)', line)
            if m:
                labels[m.group(1)] = m.group(2).strip('"')
                continue
            m = re.match(r'\s*summary:\s*"(.*)"\s*$', line)
            if m:
                summary = m.group(1)
        if name:
            rows.append((name, labels, summary, path.name))
    return rows


def gen_rules(rows) -> str:
    paging = [r for r in rows if r[1].get("tier") == "page"]
    out = ["---", "title: Built-in alert rules",
           "description: The alert rules Correlix ships and evaluates out of the "
           "box, with the severity and delivery tier of each.",
           "page_type: reference",
           "sidebar_position: 40", "---", "", BANNER, "",
           "# Built-in alert rules", "",
           f"Correlix ships {len(rows)} alert rules and evaluates them "
           "continuously against the metric store. They are defined in "
           "`src/config/rules.yaml` (device and interface conditions) and "
           "`src/config/rules-scale-slo.yaml` (platform self-health). Edit "
           "either file and restart `vmalert` to change them.", "",
           "## Delivery tiers", "",
           "A rule's `tier` label decides where a firing alert goes:", "",
           "| Tier | Meaning | Delivery |", "|---|---|---|",
           "| `page` | The platform has stopped doing its job. | Pushed to the "
           "host-monitoring channel at high priority. |",
           "| (none) | Every other firing rule. | Pushed at default priority. |",
           "| `heartbeat` | A synthetic always-firing rule that proves the "
           "delivery path works. | Never routed to a person. |", "",
           f"### The {len(paging)} paging conditions", "",
           "These are the conditions that wake somebody up. Each one means "
           "telemetry is being produced and is not arriving, or is arriving and "
           "not being processed.", "",
           "| Alert | Layer | What it means |", "|---|---|---|"]
    for name, labels, summary, _ in paging:
        out.append(f"| `{name}` | {labels.get('layer','')} | {md_cell(summary)} |")
    out += ["", "## Every rule", "",
            "| Alert | Severity | Layer | Summary |", "|---|---|---|---|"]
    for name, labels, summary, _ in rows:
        out.append(f"| `{name}` | {labels.get('severity','')} | "
                   f"{labels.get('layer','')} | {md_cell(summary)} |")
    return "\n".join(out).rstrip() + "\n"


# ───────────────────────────────── driver ───────────────────────────────────

def write(path: pathlib.Path, text: str) -> None:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == text:
        print(f"unchanged  {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"{'updated' if old else 'created'}    {path.relative_to(ROOT)}")


def main() -> int:
    routes = read_routes()
    write(PORTAL / "api.md", gen_api(routes))
    flags = read_flags()
    write(PORTAL / "feature-flags.md", gen_flags(flags, compose_defaults()))
    rules = read_rules()
    write(PORTAL / "alert-rules.md", gen_rules(rules))
    print(f"\n{len(routes)} routes · {len(flags)} flags · {len(rules)} alert rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
