// voice.test.js — the mechanical half of docs-portal/STYLE.md.
//
// STYLE.md is the prose rulebook; this file enforces the parts a machine can
// check, so a page that reads like a language model wrote it cannot merge.
// Run it with `npm test` in docs-portal (node:test, no new dependencies).
//
// Every rule here exists because a real vendor documentation set (Fortinet,
// Palo Alto Networks, CrowdStrike) does not break it. When a rule fires, fix
// the prose — do not widen the rule. Adding an allowance is a STYLE.md change.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const DOCS = path.join(__dirname, '..', 'docs');

// ── page collection ─────────────────────────────────────────────────────────

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith('.md') || entry.name.endsWith('.mdx')) out.push(full);
  }
  return out;
}

function parse(file) {
  const raw = fs.readFileSync(file, 'utf8');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?/);
  const front = {};
  if (m) {
    for (const line of m[1].split('\n')) {
      const kv = line.match(/^([a-z_]+):\s*(.*)$/);
      if (kv) front[kv[1]] = kv[2].replace(/^['"]|['"]$/g, '').trim();
    }
  }
  const body = m ? raw.slice(m[0].length) : raw;
  const offset = m ? raw.slice(0, m[0].length).split('\n').length - 1 : 0;
  return { file, raw, front, body, offset, rel: path.relative(DOCS, file) };
}

const PAGES = walk(DOCS).map(parse);

// A generated page quotes the source verbatim: alert-rule summaries, route
// summaries, error strings. Rewriting a quotation to satisfy a house rule
// would make it a lie, so generated pages are exempt from the rules that
// govern prose. They are NOT exempt from front matter, links or placeholders.
const GENERATED = /GENERATED by docs-portal\/scripts\//;
const AUTHORED = PAGES.filter(p => !GENERATED.test(p.raw));

// Prose only: strip fenced code, inline code, HTML comments, link targets and
// front matter, so a rule never fires on a command, an identifier, or a URL.
function prose(page) {
  return page.body
    .replace(/```[\s\S]*?```/g, '\n')
    .replace(/^ {4}.*$/gm, '')
    .replace(/`[^`]*`/g, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/\]\([^)]*\)/g, '] ')
    .replace(/^\s*import .*$/gm, '');
}

function lineOf(page, index) {
  return page.raw.slice(0, index).split('\n').length;
}

// The cap keeps a normal failure readable. Set VOICE_FULL=1 to print every hit
// when you are working through a backlog.
const CAP = process.env.VOICE_FULL ? Infinity : 40;

function report(hits, what) {
  const lines = hits.slice(0, CAP).map(h => `  ${h.rel}:${h.line}  ${h.detail}`);
  const more = hits.length > CAP ? `\n  … and ${hits.length - CAP} more` : '';
  return `${hits.length} ${what}\n${lines.join('\n')}${more}`;
}

// ── 1. the AI-tell denylist ─────────────────────────────────────────────────

// Words and phrases that mark machine-written marketing prose. None of them
// appear in a Fortinet, Palo Alto or CrowdStrike administration guide.
const DENY = [
  // filler adjectives
  [/\brobust\b/gi, 'say what it actually does'],
  [/\bseamless(ly)?\b/gi, 'name the thing that does not require work'],
  [/\bcomprehensive\b/gi, 'say what is covered'],
  [/\bpowerful\b/gi, 'say what it does'],
  [/\bintuitive\b/gi, 'show the procedure instead'],
  [/\brich\b(?=\s+(set|data|history|context))/gi, 'say how much'],
  [/\bcutting[- ]edge\b/gi, 'drop it'],
  [/\bstate[- ]of[- ]the[- ]art\b/gi, 'drop it'],
  [/\bbest[- ]in[- ]class\b/gi, 'drop it'],
  [/\bworld[- ]class\b/gi, 'drop it'],
  [/\bunparalleled\b/gi, 'drop it'],
  [/\bgame[- ]chang\w*/gi, 'drop it'],
  [/\brevolutionary\b/gi, 'drop it'],
  [/\beffortless(ly)?\b/gi, 'drop it'],
  [/\bturnkey\b/gi, 'drop it'],
  // filler verbs
  [/\bleverage[sd]?\b/gi, 'use "use"'],
  [/\bdelv(e|es|ing)\b/gi, 'use "read" or "open"'],
  [/\bempower(s|ed|ing)?\b/gi, 'say what the reader can now do'],
  [/\bstreamline[sd]?\b/gi, 'say which step disappears'],
  [/\bsupercharge[sd]?\b/gi, 'drop it'],
  [/\bunlocks?\s+(the\s+|your\s+)?(full\s+|real\s+|true\s+)?(power|potential|value|insight)/gi, 'say what becomes available'],
  [/\belevat(e|es|ing)\b/gi, 'drop it'],
  [/\bharness(es|ing)?\b/gi, 'use "use"'],
  [/\bfoster(s|ing)?\b/gi, 'drop it'],
  [/\bnavigat\w+ the complexit\w+/gi, 'drop it'],
  // filler connectives and hedges
  [/\bit'?s worth noting\b/gi, 'state the fact'],
  [/\bit'?s important to note\b/gi, 'state the fact'],
  [/\bplease note that\b/gi, 'state the fact'],
  [/\bin today'?s\b/gi, 'drop it'],
  [/\bfast[- ]paced\b/gi, 'drop it'],
  [/\bever[- ](evolving|changing)\b/gi, 'drop it'],
  [/\bat the end of the day\b/gi, 'drop it'],
  [/\bin conclusion\b/gi, 'drop it'],
  [/\bmoreover\b/gi, 'start a new sentence'],
  [/\bfurthermore\b/gi, 'start a new sentence'],
  [/\badditionally,/gi, 'start a new sentence'],
  [/\bwhen it comes to\b/gi, 'name the subject'],
  [/\bthat being said\b/gi, 'drop it'],
  [/\bdive (in|into|deep)\b/gi, 'use "open" or "read"'],
  [/\bdeep dive\b/gi, 'use "detail"'],
  [/\bin the realm of\b/gi, 'drop it'],
  [/\ba myriad of\b/gi, 'say how many'],
  [/\ba plethora of\b/gi, 'say how many'],
  [/\btapestry\b/gi, 'drop it'],
  [/\bjourney\b(?!\s*(map|-))/gi, 'name the task'],
  [/\bis a testament to\b/gi, 'drop it'],
  [/\bwhether you'?re\b/gi, 'address one reader'],
  [/\bsimply\b/gi, 'drop it — nothing is simple to a reader who is stuck'],
  [/\beasily\b/gi, 'drop it'],
  [/\bjust\b(?=\s+(click|run|open|add|set|type|enter))/gi, 'drop it'],
  // the meta-voice opener: writing about the documentation instead of about
  // the product. The reader already knows they are on a page.
  [/\bthis (page|document|guide|section|article) (explains|describes|covers|shows|walks|provides|outlines|details)\b/gi,
   'open with the product or the reader, not with the page'],
  [/\bthe documentation (explains|describes|provides|covers)\b/gi, 'write in product voice'],
  [/\bin this (guide|article|section|document)\b/gi, 'drop it'],
  [/\bwill be (covered|discussed|explained)\b/gi, 'cover it or drop it'],
];

test('no AI-tell words or marketing filler', () => {
  const hits = [];
  for (const page of AUTHORED) {
    const text = prose(page);
    for (const [re, fix] of DENY) {
      for (const m of text.matchAll(re)) {
        hits.push({
          rel: page.rel,
          line: lineOf(page, page.raw.indexOf(m[0])),
          detail: `"${m[0]}" — ${fix}`,
        });
      }
    }
  }
  assert.equal(hits.length, 0, report(hits, 'banned phrases'));
});

// ── 2. second person, never first person plural ─────────────────────────────

test('addresses the reader as "you", never as "we"', () => {
  const hits = [];
  // The apostrophe is REQUIRED: an optional one turns this into a rule that
  // fires on "were" and "well".
  const FIRST = [/\bwe['\u2019](ll|ve|re|d)\b/gi, /\bwe\s/gi, /\bour\b/gi,
                 /\blet['\u2019]s\b/gi];
  for (const page of PAGES) {
    const text = prose(page);
    for (const re of FIRST) {
      for (const m of text.matchAll(re)) {
        hits.push({
          rel: page.rel,
          line: lineOf(page, page.raw.indexOf(m[0])),
          detail: `"${m[0].trim()}" — the documentation is not a person`,
        });
      }
    }
  }
  assert.equal(hits.length, 0, report(hits, 'first-person-plural uses'));
});

// ── 2b. product vocabulary ──────────────────────────────────────────────────

// The console says "observations", never "signals" — a vitest vocabulary
// scanner enforces it in the product, and the documentation matches. The
// exceptions are the engine's own terms: a skill's "chain signal" / "machine
// signal", and the `signal` evidence class (which is inline code and is
// stripped before this runs).
test('the product vocabulary is used', () => {
  const hits = [];
  const BANNED = [
    [/\bsignals?\b/gi, 'the product says "observations", not "signals"',
     /((chain|machine|correlation|evidence|no)\s+signals?|signals?\s+(selector|parameter|class))\b/i],
    [/\bthe NOC\b/g, 'name the seam and the party that owns it, not "the NOC"', null],
  ];
  for (const page of AUTHORED) {
    const text = prose(page);
    for (const [re, fix, allow] of BANNED) {
      for (const m of text.matchAll(re)) {
        // The window must reach BOTH ways: the qualifier can precede the word
        // ("chain signal") or follow it ("signal selector").
        const around = text.slice(Math.max(0, m.index - 24), m.index + m[0].length + 24);
        if (allow && allow.test(around)) continue;
        hits.push({
          rel: page.rel,
          line: lineOf(page, page.raw.indexOf(m[0])),
          detail: `"${m[0]}" — ${fix}`,
        });
      }
    }
  }
  assert.equal(hits.length, 0, report(hits, 'product-vocabulary problems'));
});

// ── 3. em-dash discipline ───────────────────────────────────────────────────

// One em dash can carry an aside. Three in a paragraph is the rhythm of
// generated prose. Vendor guides use commas, colons and full stops.
test('em dashes stay rare', () => {
  const hits = [];
  for (const page of PAGES) {
    // A bold span is a quoted product string — a console label such as
    // **OSPF — IGP health**. Quoting the product is not a prose habit, so its
    // punctuation does not count against the budget.
    // A bold span is a quoted product string and a heading is structure —
    // STYLE.md sanctions the `### Step 1 — …` form. Neither is prose rhythm,
    // so neither counts against the budget.
    const text = prose(page)
      .replace(/^\s*#+ .*$/gm, ' ')
      .replace(/^\s*\|.*$/gm, ' ')
      .replace(/\*\*[^*]*\*\*/g, ' ');
    const total = (text.match(/—/g) || []).length;
    const words = text.split(/\s+/).filter(Boolean).length;
    const budget = Math.max(3, Math.floor(words / 250));
    if (total > budget) {
      hits.push({
        rel: page.rel, line: 1,
        detail: `${total} em dashes in ${words} words (budget ${budget})`,
      });
    }
    for (const para of text.split(/\n\s*\n/)) {
      if ((para.match(/—/g) || []).length > 1) {
        hits.push({
          rel: page.rel,
          line: lineOf(page, page.raw.indexOf(para.trim().slice(0, 40))),
          detail: 'more than one em dash in a single paragraph',
        });
      }
    }
  }
  assert.equal(hits.length, 0, report(hits, 'em-dash problems'));
});

// ── 4. sentence length ──────────────────────────────────────────────────────

test('sentences stay under 45 words', () => {
  const hits = [];
  for (const page of AUTHORED) {
    const text = prose(page)
      .replace(/^\s*\|.*$/gm, '')      // tables
      .replace(/^\s*#+ .*$/gm, '');    // headings
    // Split on line breaks FIRST: a list item without a terminal full stop is
    // its own unit, not the opening clause of the next bullet.
    const units = text.split(/\n/).flatMap(line => line.split(/(?<=[.!?])\s+/));
    for (const sentence of units) {
      const words = sentence.trim().split(/\s+/).filter(Boolean);
      if (words.length > 45) {
        hits.push({
          rel: page.rel,
          line: lineOf(page, page.raw.indexOf(sentence.trim().slice(0, 40))),
          detail: `${words.length}-word sentence: "${words.slice(0, 8).join(' ')}…"`,
        });
      }
    }
  }
  assert.equal(hits.length, 0, report(hits, 'over-long sentences'));
});

// ── 5. no emoji in the body ─────────────────────────────────────────────────

test('no emoji', () => {
  const hits = [];
  const EMOJI = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE0F}]/gu;
  for (const page of PAGES) {
    for (const m of page.body.matchAll(EMOJI)) {
      hits.push({ rel: page.rel, line: lineOf(page, page.raw.indexOf(m[0])), detail: `emoji ${m[0]}` });
    }
  }
  assert.equal(hits.length, 0, report(hits, 'emoji'));
});

// ── 6. front matter ─────────────────────────────────────────────────────────

const PAGE_TYPES = new Set(['task', 'concept', 'reference', 'index', 'release']);

test('every page declares title, description and page_type', () => {
  const hits = [];
  for (const page of PAGES) {
    if (!page.front.title) hits.push({ rel: page.rel, line: 1, detail: 'no title' });
    if (!page.front.description) hits.push({ rel: page.rel, line: 1, detail: 'no description' });
    else if (page.front.description.length > 200) {
      hits.push({ rel: page.rel, line: 1, detail: `description is ${page.front.description.length} chars (max 200)` });
    }
    // A bare YAML scalar containing ": " is a parse error, and Docusaurus fails
    // the whole build on it. Cheaper to catch here, by name.
    const fm = page.raw.match(/^---\n([\s\S]*?)\n---/);
    if (fm) {
      for (const line of fm[1].split('\n')) {
        const kv = line.match(/^([a-z_]+):\s+(.*)$/);
        if (!kv) continue;
        const v = kv[2];
        if (/^["'\[{>|]/.test(v)) continue;
        if (v.includes(': ')) {
          hits.push({ rel: page.rel, line: 1, detail: `front matter "${kv[1]}" holds an unquoted colon — wrap the value in double quotes` });
        }
      }
    }
    if (!page.front.page_type) hits.push({ rel: page.rel, line: 1, detail: 'no page_type' });
    else if (!PAGE_TYPES.has(page.front.page_type)) {
      hits.push({ rel: page.rel, line: 1, detail: `page_type "${page.front.page_type}" is not one of ${[...PAGE_TYPES].join(', ')}` });
    }
  }
  assert.equal(hits.length, 0, report(hits, 'front-matter problems'));
});

// ── 7. task pages carry the task shape ──────────────────────────────────────

// The shape every vendor guide uses: say what the reader needs, give numbered
// steps, tell them how to know it worked, point at what is next.
const TASK_VERBS = [
  'Add', 'Assign', 'Back', 'Build', 'Capture', 'Change', 'Check', 'Choose',
  'Collect', 'Configure', 'Connect', 'Create', 'Delete', 'Deploy', 'Diagnose',
  'Disable', 'Discover', 'Download', 'Enable', 'Export', 'File', 'Find',
  'Generate', 'Grant', 'Import', 'Install', 'Investigate', 'Mint', 'Monitor',
  'Move', 'Onboard', 'Open', 'Plan', 'Point', 'Prepare', 'Publish', 'Query',
  'Read', 'Rebuild', 'Recover', 'Reduce', 'Remove', 'Rename', 'Replace',
  'Report', 'Reset', 'Resize', 'Restore', 'Review', 'Roll', 'Rotate', 'Route',
  'Run', 'Schedule', 'Scope', 'Search', 'Send', 'Set', 'Sign', 'Size', 'Start',
  'Stop', 'Store', 'Tag', 'Take', 'Test', 'Trace', 'Track', 'Tune', 'Turn',
  'Update', 'Upgrade', 'Verify', 'View', 'Watch', 'Work', 'Write',
  // Added as sections were written. Keep this list generous: its job is to
  // stop noun-phrase titles on task pages, not to narrow the English a
  // technical writer may use.
  'Acknowledge', 'Adjust', 'Analyse', 'Analyze', 'Apply', 'Assess', 'Compare',
  'Compose', 'Correct', 'Debug', 'Edit', 'Escalate', 'Follow', 'Inspect', 'Keep',
  'Manage', 'Map', 'Measure', 'Mute', 'Narrow', 'Pause', 'Place', 'Point',
  'Promote', 'Receive', 'Save', 'Shape', 'Silence', 'Split', 'Suppress',
  'Trigger', 'Tune', 'Use', 'Wire',
];

// A task page's description is its abstract, and it obeys the same grammar as
// the title: an imperative verb, then the benefit. Palo Alto keys the DITA
// shortdesc to the topic type this way, and it is why their guides scan.
test('task-page descriptions start with an imperative verb', () => {
  const hits = [];
  for (const page of PAGES) {
    if (page.front.page_type !== 'task') continue;
    const first = (page.front.description || '').split(/\s+/)[0].replace(/[^A-Za-z]/g, '');
    if (!TASK_VERBS.includes(first)) {
      hits.push({ rel: page.rel, line: 1, detail: `description starts "${first}" — use an imperative verb` });
    }
  }
  assert.equal(hits.length, 0, report(hits, 'task descriptions that do not lead with a verb'));
});

test('task pages are titled with a verb and follow Before you begin / Steps / Result / Related', () => {
  const hits = [];
  for (const page of PAGES) {
    if (page.front.page_type !== 'task') continue;
    const first = (page.front.title || '').split(/\s+/)[0].replace(/[^A-Za-z]/g, '');
    if (!TASK_VERBS.includes(first)) {
      hits.push({ rel: page.rel, line: 1, detail: `title "${page.front.title}" does not start with a task verb` });
    }
    const heads = [...page.body.matchAll(/^##\s+(.+)$/gm)].map(m => m[1].trim());
    for (const need of ['Before you begin', 'Steps']) {
      if (!heads.includes(need)) hits.push({ rel: page.rel, line: 1, detail: `missing "## ${need}"` });
    }
    if (!heads.includes('Result') && !heads.includes('What you see')) {
      hits.push({ rel: page.rel, line: 1, detail: 'missing "## Result" or "## What you see"' });
    }
    if (!heads.includes('Related')) hits.push({ rel: page.rel, line: 1, detail: 'missing "## Related"' });
    const order = heads.filter(h => ['Before you begin', 'Steps', 'Result', 'What you see', 'Related'].includes(h));
    const rank = { 'Before you begin': 0, 'Steps': 1, 'Result': 2, 'What you see': 2, 'Related': 3 };
    for (let i = 1; i < order.length; i++) {
      if (rank[order[i]] < rank[order[i - 1]]) {
        hits.push({ rel: page.rel, line: 1, detail: `"${order[i]}" comes after "${order[i - 1]}"` });
      }
    }
  }
  assert.equal(hits.length, 0, report(hits, 'task-page structure problems'));
});

// ── 8. concept pages are titled as concepts, not tasks ──────────────────────

test('concept pages are not titled like procedures', () => {
  const hits = [];
  for (const page of PAGES) {
    if (page.front.page_type !== 'concept') continue;
    const first = (page.front.title || '').split(/\s+/)[0].replace(/[^A-Za-z]/g, '');
    if (TASK_VERBS.includes(first)) {
      hits.push({ rel: page.rel, line: 1, detail: `concept page titled "${page.front.title}" — make it a task page or retitle it` });
    }
    const heads = [...page.body.matchAll(/^##\s+(.+)$/gm)].map(m => m[1].trim());
    if (!heads.includes('Related')) hits.push({ rel: page.rel, line: 1, detail: 'missing "## Related"' });
  }
  assert.equal(hits.length, 0, report(hits, 'concept-page problems'));
});

// ── 9. no unfinished pages ──────────────────────────────────────────────────

test('no placeholders', () => {
  const hits = [];
  const HOLES = [/\bTODO\b/g, /\bTBD\b/g, /\bcoming soon\b/gi, /\bLorem ipsum\b/gi,
                 /\bXXX\b/g, /\bFIXME\b/g, /<placeholder>/gi];
  for (const page of PAGES) {
    for (const re of HOLES) {
      for (const m of page.body.matchAll(re)) {
        hits.push({ rel: page.rel, line: lineOf(page, page.raw.indexOf(m[0])), detail: m[0] });
      }
    }
  }
  assert.equal(hits.length, 0, report(hits, 'placeholders'));
});

// ── 10. internal links resolve ──────────────────────────────────────────────

// Docusaurus builds with onBrokenLinks: 'throw', which catches this too — but a
// failing unit test names the file in a second, and the build takes a minute.
test('every internal link resolves to a page', () => {
  const slugs = new Set();
  for (const page of PAGES) {
    const rel = page.rel.replace(/\.mdx?$/, '');
    slugs.add('/' + rel);
    slugs.add('/' + rel.replace(/\/index$/, ''));
    if (page.front.slug) slugs.add(page.front.slug.replace(/\/$/, '') || '/');
  }
  slugs.add('/');
  const dirs = new Set(PAGES.map(p => '/' + path.dirname(p.rel)));

  const hits = [];
  for (const page of PAGES) {
    for (const m of page.body.matchAll(/\]\((\/[^)#\s]*)(#[^)\s]*)?\)/g)) {
      const target = m[1].replace(/\/$/, '') || '/';
      if (slugs.has(target) || dirs.has(target)) continue;
      hits.push({ rel: page.rel, line: lineOf(page, page.raw.indexOf(m[0])), detail: `dead link ${m[1]}` });
    }
  }
  assert.equal(hits.length, 0, report(hits, 'dead internal links'));
});

// ── 11. the corpus is not empty ─────────────────────────────────────────────

test('the portal has pages', () => {
  assert.ok(PAGES.length > 40, `only ${PAGES.length} pages found under docs/`);
});
