---
hostname:        P5
loopback:        10.0.0.5
isis_net:        "49.0001.0000.0000.0005.00"
interfaces:
  - { name: "TO-P1",  port: "1/1/1", ip: "10.1.2.1/31",  isis_metric: 10, mtu: 9000 }
  - { name: "TO-P6",  port: "1/1/2", ip: "10.1.1.6/31",  isis_metric: 10, mtu: 9000 }
  - { name: "TO-PE2", port: "1/1/3", ip: "10.2.1.3/31",  isis_metric: 10, mtu: 9000 }
