import { useId } from "react";

// BrandMark — the Correlix eye. A wide-open almond eye whose iris is deep
// space: a seeded constellation of device nodes joined by hairline links
// (denser toward the pupil, four bright hubs), behind a glowing observation
// ring. Lids + lashes keep the design-system indigo->cyan->emerald sweep.
// Generated by scripts/design/gen_brandmark.py — regenerate there, don't
// hand-edit the constellation.
export default function BrandMark({ size = 26 }: { size?: number }) {
  const uid = useId().replace(/:/g, "");
  return (
    <svg viewBox="0 0 512 512" width={size} height={size} fill="none" aria-hidden="true">
    <defs>
      <linearGradient id={uid + "Lid"} x1="37" y1="146" x2="475" y2="366" gradientUnits="userSpaceOnUse">
        <stop offset="0%" stopColor="#818cf8"/>
        <stop offset="50%" stopColor="#22d3ee"/>
        <stop offset="100%" stopColor="#34d399"/>
      </linearGradient>
      <radialGradient id={uid + "Space"} cx="0.5" cy="0.5" r="0.5">
        <stop offset="0%" stopColor="#05060f"/>
        <stop offset="45%" stopColor="#0b1026"/>
        <stop offset="78%" stopColor="#1e1b4b"/>
        <stop offset="92%" stopColor="#312e81"/>
        <stop offset="100%" stopColor="#4338ca"/>
      </radialGradient>
      <clipPath id={uid + "Clip"}><circle cx="256" cy="256" r="103.0"/></clipPath>
    </defs>
    <g fill={"url(#" + uid + "Lid)"}>
      <path d="M50.9 232.5 C46.6 212.7 31.1 201.0 12.1 202.9 C31.8 200.8 48.0 212.3 56.1 230.8 Z"/>
      <path d="M79.6 201.8 C76.0 179.4 61.4 164.1 42.4 161.2 C62.2 163.9 77.5 179.0 85.3 200.3 Z"/>
      <path d="M113.1 177.1 C110.1 150.7 96.6 130.7 78.0 122.3 C97.3 130.6 111.7 150.4 119.1 175.9 Z"/>
      <path d="M150.2 158.6 C148.8 131.7 139.0 109.8 125.0 97.3 C139.8 109.7 150.5 131.4 156.7 157.7 Z"/>
      <path d="M190.1 146.2 C190.0 116.3 183.6 90.9 174.1 73.9 C184.4 90.8 191.8 116.1 196.8 145.6 Z"/>
      <path d="M231.6 139.9 C233.2 109.8 231.3 83.6 228.4 65.0 C232.2 83.6 235.0 109.7 238.4 139.7 Z"/>
      <path d="M273.6 139.7 C277.0 110.8 279.7 85.5 283.4 67.6 C280.5 85.5 278.7 110.8 280.4 139.9 Z"/>
      <path d="M315.2 145.6 C320.2 116.2 327.5 90.9 337.9 74.2 C328.4 91.0 322.0 116.4 321.9 146.2 Z"/>
      <path d="M355.3 157.7 C361.5 131.5 372.1 109.9 386.9 97.5 C373.0 110.0 363.2 131.8 361.8 158.6 Z"/>
      <path d="M392.9 175.9 C400.2 151.0 414.2 131.6 433.1 123.6 C415.0 131.8 401.8 151.3 398.9 177.1 Z"/>
      <path d="M426.7 200.3 C434.5 179.2 449.6 164.3 469.2 161.6 C450.4 164.5 435.9 179.6 432.4 201.8 Z"/>
      <path d="M455.9 230.8 C463.9 212.8 479.6 201.6 498.9 203.6 C480.3 201.8 465.2 213.2 461.1 232.5 Z"/>
    </g>
    <circle cx="256" cy="256" r="103.0" fill={"url(#" + uid + "Space)"}/>
    <g clipPath={"url(#" + uid + "Clip)"}>
      <line x1="309.4" y1="328.4" x2="312.0" y2="316.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="309.4" y1="328.4" x2="299.9" y2="324.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="309.4" y1="328.4" x2="320.9" y2="322.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="301.7" y1="228.7" x2="290.9" y2="220.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="301.7" y1="228.7" x2="300.1" y2="219.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="187.6" y1="284.2" x2="198.6" y2="290.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="187.6" y1="284.2" x2="175.5" y2="279.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="271.3" y1="338.5" x2="272.2" y2="329.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="271.3" y1="338.5" x2="284.5" y2="341.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.1"/>
      <line x1="291.7" y1="309.8" x2="284.9" y2="297.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="291.7" y1="309.8" x2="286.9" y2="318.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.12"/>
      <line x1="239.1" y1="178.7" x2="246.5" y2="183.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="239.1" y1="178.7" x2="245.5" y2="167.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="242.1" y1="324.4" x2="230.3" y2="329.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="242.1" y1="324.4" x2="234.6" y2="315.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="169.3" y1="267.3" x2="183.3" y2="267.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="169.3" y1="267.3" x2="175.5" y2="279.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.26"/>
      <line x1="230.3" y1="329.6" x2="226.6" y2="321.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="230.3" y1="329.6" x2="220.3" y2="333.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="312.0" y1="316.7" x2="299.9" y2="324.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="312.0" y1="316.7" x2="306.6" y2="307.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="312.0" y1="316.7" x2="320.9" y2="322.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="210.5" y1="300.4" x2="202.6" y2="306.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.15"/>
      <line x1="210.5" y1="300.4" x2="205.6" y2="305.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.15"/>
      <line x1="284.9" y1="297.8" x2="277.0" y2="307.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="226.6" y1="321.0" x2="234.6" y2="315.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="226.6" y1="321.0" x2="215.6" y2="320.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.1"/>
      <line x1="234.6" y1="315.0" x2="225.7" y2="306.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.26"/>
      <line x1="234.6" y1="315.0" x2="238.4" y2="304.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.15"/>
      <line x1="193.0" y1="265.2" x2="202.1" y2="275.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="193.0" y1="265.2" x2="183.3" y2="267.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="193.0" y1="265.2" x2="190.7" y2="250.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="318.7" y1="207.4" x2="329.3" y2="196.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="318.7" y1="207.4" x2="317.6" y2="218.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="225.7" y1="306.8" x2="238.4" y2="304.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="169.6" y1="234.9" x2="180.2" y2="240.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="169.6" y1="234.9" x2="163.2" y2="245.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="346.1" y1="238.4" x2="328.9" y2="230.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="346.1" y1="238.4" x2="349.5" y2="254.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="332.8" y1="272.2" x2="346.8" y2="275.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.1"/>
      <line x1="332.8" y1="272.2" x2="323.4" y2="279.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.12"/>
      <line x1="289.6" y1="206.0" x2="283.2" y2="198.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="289.6" y1="206.0" x2="290.9" y2="220.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="263.5" y1="324.5" x2="272.1" y2="319.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="263.5" y1="324.5" x2="254.9" y2="319.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="263.5" y1="324.5" x2="255.0" y2="331.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="212.9" y1="311.5" x2="215.6" y2="320.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.15"/>
      <line x1="212.9" y1="311.5" x2="205.6" y2="305.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="246.5" y1="183.8" x2="252.8" y2="174.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="246.5" y1="183.8" x2="252.4" y2="193.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="202.2" y1="220.2" x2="194.7" y2="229.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="202.2" y1="220.2" x2="198.4" y2="211.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="202.2" y1="220.2" x2="207.0" y2="228.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="253.1" y1="298.6" x2="251.5" y2="310.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="253.1" y1="298.6" x2="263.9" y2="305.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.26"/>
      <line x1="296.4" y1="190.6" x2="298.5" y2="177.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="296.4" y1="190.6" x2="307.1" y2="196.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="304.8" y1="295.6" x2="300.3" y2="283.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="304.8" y1="295.6" x2="314.2" y2="293.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="304.8" y1="295.6" x2="310.7" y2="299.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="194.7" y1="229.8" x2="202.6" y2="236.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="238.4" y1="304.8" x2="237.0" y2="295.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="206.4" y1="329.4" x2="194.0" y2="327.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.26"/>
      <line x1="206.4" y1="329.4" x2="203.5" y2="319.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="318.1" y1="270.4" x2="321.7" y2="260.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="318.1" y1="270.4" x2="323.4" y2="279.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.26"/>
      <line x1="318.1" y1="270.4" x2="308.9" y2="269.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="264.7" y1="170.2" x2="252.8" y2="174.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="264.7" y1="170.2" x2="274.6" y2="177.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="268.7" y1="297.3" x2="277.0" y2="307.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="268.7" y1="297.3" x2="263.9" y2="305.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="314.4" y1="237.7" x2="325.0" y2="238.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="314.4" y1="237.7" x2="307.7" y2="248.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="314.4" y1="237.7" x2="315.1" y2="233.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="200.5" y1="201.6" x2="198.4" y2="211.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="200.5" y1="201.6" x2="208.6" y2="206.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="200.5" y1="201.6" x2="193.8" y2="194.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="200.5" y1="201.6" x2="205.2" y2="193.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="193.2" y1="312.3" x2="185.7" y2="317.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="193.2" y1="312.3" x2="202.6" y2="306.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="225.0" y1="196.5" x2="232.3" y2="190.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="225.0" y1="196.5" x2="222.6" y2="206.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="225.0" y1="196.5" x2="228.3" y2="198.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="329.3" y1="196.1" x2="334.8" y2="215.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="212.4" y1="274.8" x2="213.9" y2="286.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.12"/>
      <line x1="212.4" y1="274.8" x2="207.0" y2="263.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="212.4" y1="274.8" x2="202.1" y2="275.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="173.4" y1="251.7" x2="180.2" y2="240.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="173.4" y1="251.7" x2="163.2" y2="245.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="336.7" y1="289.3" x2="323.8" y2="289.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="336.7" y1="289.3" x2="346.8" y2="275.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="336.7" y1="289.3" x2="336.0" y2="299.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="245.5" y1="167.5" x2="252.8" y2="174.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="245.5" y1="167.5" x2="228.4" y2="165.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="283.2" y1="198.2" x2="279.1" y2="189.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="283.2" y1="198.2" x2="271.8" y2="196.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="171.1" y1="287.5" x2="178.8" y2="294.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="171.1" y1="287.5" x2="175.5" y2="279.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="232.3" y1="190.3" x2="228.3" y2="198.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="262.5" y1="187.7" x2="252.4" y2="193.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="262.5" y1="187.7" x2="271.8" y2="196.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="201.4" y1="180.4" x2="216.6" y2="180.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="201.4" y1="180.4" x2="205.2" y2="193.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="184.4" y1="210.1" x2="171.9" y2="214.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="184.4" y1="210.1" x2="183.7" y2="194.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="184.4" y1="210.1" x2="181.1" y2="219.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="330.9" y1="250.5" x2="325.0" y2="238.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="330.9" y1="250.5" x2="321.7" y2="260.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="330.9" y1="250.5" x2="349.5" y2="254.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="198.4" y1="211.0" x2="208.6" y2="206.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="207.0" y1="228.5" x2="215.0" y2="232.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="207.0" y1="228.5" x2="202.6" y2="236.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="328.9" y1="230.0" x2="325.0" y2="238.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="328.9" y1="230.0" x2="334.8" y2="215.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="328.9" y1="230.0" x2="327.7" y2="220.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="272.1" y1="319.7" x2="272.2" y2="329.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="235.2" y1="343.6" x2="247.7" y2="340.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="235.2" y1="343.6" x2="225.0" y2="344.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="325.0" y1="238.5" x2="315.1" y2="233.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="257.6" y1="340.5" x2="247.7" y2="340.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="257.6" y1="340.5" x2="255.0" y2="331.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="232.7" y1="206.6" x2="243.5" y2="198.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="232.7" y1="206.6" x2="222.6" y2="206.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="232.7" y1="206.6" x2="228.3" y2="198.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="317.6" y1="218.1" x2="327.7" y2="220.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="179.2" y1="305.5" x2="185.7" y2="317.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="179.2" y1="305.5" x2="178.8" y2="294.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="213.9" y1="286.9" x2="223.6" y2="288.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="254.9" y1="319.7" x2="251.5" y2="310.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="198.6" y1="290.5" x2="193.2" y2="298.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.12"/>
      <line x1="193.8" y1="194.8" x2="183.7" y2="194.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="193.8" y1="194.8" x2="205.2" y2="193.5" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="171.9" y1="214.5" x2="181.1" y2="219.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="267.1" y1="209.6" x2="279.4" y2="216.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.1"/>
      <line x1="267.1" y1="209.6" x2="257.4" y2="203.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="272.2" y1="329.4" x2="283.2" y2="329.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.23"/>
      <line x1="334.8" y1="215.1" x2="327.7" y2="220.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="323.8" y1="289.0" x2="323.4" y2="279.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="323.8" y1="289.0" x2="314.2" y2="293.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="306.6" y1="307.1" x2="310.7" y2="299.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="185.7" y1="317.8" x2="194.0" y2="327.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.21"/>
      <line x1="299.0" y1="260.0" x2="307.7" y2="248.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="299.0" y1="260.0" x2="308.9" y2="269.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="330.9" y1="308.7" x2="319.2" y2="307.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.15"/>
      <line x1="330.9" y1="308.7" x2="336.0" y2="299.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.26"/>
      <line x1="310.4" y1="184.6" x2="298.5" y2="177.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.25"/>
      <line x1="310.4" y1="184.6" x2="307.1" y2="196.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="247.7" y1="340.3" x2="255.0" y2="331.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="252.4" y1="193.6" x2="257.4" y2="203.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="252.4" y1="193.6" x2="243.5" y2="198.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="223.6" y1="288.8" x2="237.0" y2="295.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="289.2" y1="173.9" x2="298.5" y2="177.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="289.2" y1="173.9" x2="274.6" y2="177.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="286.9" y1="318.3" x2="283.2" y2="329.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="207.0" y1="263.7" x2="202.1" y2="275.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="207.0" y1="263.7" x2="214.1" y2="252.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="279.4" y1="216.0" x2="290.9" y2="220.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="216.6" y1="180.9" x2="223.0" y2="172.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="319.2" y1="307.0" x2="310.7" y2="299.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="279.1" y1="189.7" x2="274.6" y2="177.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="279.1" y1="189.7" x2="271.8" y2="196.1" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="290.9" y1="220.0" x2="300.1" y2="219.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="309.7" y1="283.4" x2="300.3" y2="283.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.11"/>
      <line x1="309.7" y1="283.4" x2="314.2" y2="293.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.13"/>
      <line x1="228.4" y1="165.1" x2="223.0" y2="172.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.22"/>
      <line x1="193.2" y1="298.2" x2="202.6" y2="306.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.15"/>
      <line x1="194.0" y1="327.6" x2="203.5" y2="319.8" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="220.3" y1="333.2" x2="225.0" y2="344.0" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="216.1" y1="215.2" x2="223.7" y2="221.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.24"/>
      <line x1="216.1" y1="215.2" x2="222.6" y2="206.2" stroke="#7dd3fc" strokeWidth="1" opacity="0.16"/>
      <line x1="214.1" y1="252.8" x2="201.6" y2="249.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.19"/>
      <line x1="203.5" y1="319.8" x2="215.6" y2="320.4" stroke="#7dd3fc" strokeWidth="1" opacity="0.18"/>
      <line x1="202.6" y1="306.9" x2="205.6" y2="305.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.14"/>
      <line x1="223.7" y1="221.3" x2="215.0" y2="232.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="215.0" y1="232.9" x2="202.6" y2="236.7" stroke="#7dd3fc" strokeWidth="1" opacity="0.1"/>
      <line x1="283.2" y1="329.1" x2="284.5" y2="341.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.17"/>
      <line x1="314.2" y1="293.8" x2="310.7" y2="299.6" stroke="#7dd3fc" strokeWidth="1" opacity="0.15"/>
      <line x1="190.7" y1="250.9" x2="201.6" y2="249.9" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <line x1="222.6" y1="206.2" x2="228.3" y2="198.3" stroke="#7dd3fc" strokeWidth="1" opacity="0.2"/>
      <circle cx="309.4" cy="328.4" r="2.9" fill="#67e8f9" opacity="0.61"/>
      <circle cx="301.7" cy="228.7" r="2.5" fill="#e0e7ff" opacity="0.44"/>
      <circle cx="187.6" cy="284.2" r="2.2" fill="#67e8f9" opacity="0.66"/>
      <circle cx="271.3" cy="338.5" r="2.9" fill="#67e8f9" opacity="0.82"/>
      <circle cx="291.7" cy="309.8" r="1.6" fill="#a5b4fc" opacity="0.81"/>
      <circle cx="239.1" cy="178.7" r="3.3" fill="#e0e7ff" opacity="0.47"/>
      <circle cx="242.1" cy="324.4" r="1.9" fill="#e0e7ff" opacity="0.38"/>
      <circle cx="169.3" cy="267.3" r="2.2" fill="#e0e7ff" opacity="0.69"/>
      <circle cx="230.3" cy="329.6" r="1.6" fill="#e0e7ff" opacity="0.58"/>
      <circle cx="312.0" cy="316.7" r="1.6" fill="#67e8f9" opacity="0.37"/>
      <circle cx="210.5" cy="300.4" r="1.6" fill="#a5b4fc" opacity="0.43"/>
      <circle cx="284.9" cy="297.8" r="2.5" fill="#e0e7ff" opacity="0.6"/>
      <circle cx="226.6" cy="321.0" r="1.9" fill="#e0e7ff" opacity="0.37"/>
      <circle cx="299.9" cy="324.5" r="1.6" fill="#e0e7ff" opacity="0.41"/>
      <circle cx="234.6" cy="315.0" r="2.5" fill="#67e8f9" opacity="0.79"/>
      <circle cx="193.0" cy="265.2" r="1.6" fill="#e0e7ff" opacity="0.56"/>
      <circle cx="318.7" cy="207.4" r="2.2" fill="#e0e7ff" opacity="0.36"/>
      <circle cx="225.7" cy="306.8" r="2.9" fill="#e0e7ff" opacity="0.87"/>
      <circle cx="169.6" cy="234.9" r="1.9" fill="#a5b4fc" opacity="0.49"/>
      <circle cx="346.1" cy="238.4" r="1.6" fill="#e0e7ff" opacity="0.74"/>
      <circle cx="332.8" cy="272.2" r="3.3" fill="#a5b4fc" opacity="0.91"/>
      <circle cx="289.6" cy="206.0" r="2.9" fill="#e0e7ff" opacity="0.7"/>
      <circle cx="263.5" cy="324.5" r="1.9" fill="#e0e7ff" opacity="0.85"/>
      <circle cx="212.9" cy="311.5" r="1.6" fill="#67e8f9" opacity="0.83"/>
      <circle cx="246.5" cy="183.8" r="1.6" fill="#a5b4fc" opacity="0.5"/>
      <circle cx="202.2" cy="220.2" r="1.9" fill="#e0e7ff" opacity="0.88"/>
      <circle cx="253.1" cy="298.6" r="3.3" fill="#a5b4fc" opacity="0.66"/>
      <circle cx="296.4" cy="190.6" r="2.9" fill="#e0e7ff" opacity="0.77"/>
      <circle cx="304.8" cy="295.6" r="2.2" fill="#67e8f9" opacity="0.75"/>
      <circle cx="194.7" cy="229.8" r="2.5" fill="#a5b4fc" opacity="0.55"/>
      <circle cx="238.4" cy="304.8" r="1.9" fill="#e0e7ff" opacity="0.63"/>
      <circle cx="206.4" cy="329.4" r="2.2" fill="#e0e7ff" opacity="0.43"/>
      <circle cx="318.1" cy="270.4" r="2.5" fill="#67e8f9" opacity="0.8"/>
      <circle cx="264.7" cy="170.2" r="2.2" fill="#67e8f9" opacity="0.37"/>
      <circle cx="268.7" cy="297.3" r="2.9" fill="#a5b4fc" opacity="0.76"/>
      <circle cx="314.4" cy="237.7" r="2.2" fill="#e0e7ff" opacity="0.74"/>
      <circle cx="200.5" cy="201.6" r="2.2" fill="#e0e7ff" opacity="0.5"/>
      <circle cx="193.2" cy="312.3" r="1.6" fill="#67e8f9" opacity="0.38"/>
      <circle cx="225.0" cy="196.5" r="3.3" fill="#a5b4fc" opacity="0.62"/>
      <circle cx="329.3" cy="196.1" r="3.3" fill="#e0e7ff" opacity="0.91"/>
      <circle cx="212.4" cy="274.8" r="2.9" fill="#67e8f9" opacity="0.58"/>
      <circle cx="173.4" cy="251.7" r="3.3" fill="#e0e7ff" opacity="0.59"/>
      <circle cx="336.7" cy="289.3" r="2.2" fill="#e0e7ff" opacity="0.71"/>
      <circle cx="245.5" cy="167.5" r="3.3" fill="#e0e7ff" opacity="0.56"/>
      <circle cx="283.2" cy="198.2" r="1.9" fill="#e0e7ff" opacity="0.72"/>
      <circle cx="171.1" cy="287.5" r="1.6" fill="#e0e7ff" opacity="0.4"/>
      <circle cx="232.3" cy="190.3" r="2.2" fill="#e0e7ff" opacity="0.8"/>
      <circle cx="262.5" cy="187.7" r="2.9" fill="#e0e7ff" opacity="0.9"/>
      <circle cx="201.4" cy="180.4" r="2.2" fill="#67e8f9" opacity="0.73"/>
      <circle cx="184.4" cy="210.1" r="2.2" fill="#e0e7ff" opacity="0.8"/>
      <circle cx="330.9" cy="250.5" r="2.5" fill="#67e8f9" opacity="0.5"/>
      <circle cx="198.4" cy="211.0" r="1.9" fill="#e0e7ff" opacity="0.82"/>
      <circle cx="207.0" cy="228.5" r="2.2" fill="#e0e7ff" opacity="0.77"/>
      <circle cx="328.9" cy="230.0" r="2.5" fill="#a5b4fc" opacity="0.89"/>
      <circle cx="272.1" cy="319.7" r="3.3" fill="#67e8f9" opacity="0.5"/>
      <circle cx="252.8" cy="174.0" r="3.3" fill="#67e8f9" opacity="0.79"/>
      <circle cx="235.2" cy="343.6" r="3.3" fill="#67e8f9" opacity="0.47"/>
      <circle cx="325.0" cy="238.5" r="2.2" fill="#e0e7ff" opacity="0.66"/>
      <circle cx="208.6" cy="206.6" r="2.5" fill="#a5b4fc" opacity="0.78"/>
      <circle cx="257.6" cy="340.5" r="2.5" fill="#a5b4fc" opacity="0.38"/>
      <circle cx="232.7" cy="206.6" r="1.6" fill="#67e8f9" opacity="0.83"/>
      <circle cx="317.6" cy="218.1" r="2.2" fill="#a5b4fc" opacity="0.71"/>
      <circle cx="179.2" cy="305.5" r="2.5" fill="#e0e7ff" opacity="0.63"/>
      <circle cx="213.9" cy="286.9" r="1.9" fill="#a5b4fc" opacity="0.37"/>
      <circle cx="254.9" cy="319.7" r="2.2" fill="#a5b4fc" opacity="0.48"/>
      <circle cx="198.6" cy="290.5" r="2.5" fill="#e0e7ff" opacity="0.82"/>
      <circle cx="193.8" cy="194.8" r="2.2" fill="#e0e7ff" opacity="0.51"/>
      <circle cx="171.9" cy="214.5" r="2.9" fill="#e0e7ff" opacity="0.42"/>
      <circle cx="267.1" cy="209.6" r="2.2" fill="#e0e7ff" opacity="0.91"/>
      <circle cx="272.2" cy="329.4" r="2.5" fill="#e0e7ff" opacity="0.75"/>
      <circle cx="334.8" cy="215.1" r="2.2" fill="#67e8f9" opacity="0.61"/>
      <circle cx="323.8" cy="289.0" r="2.5" fill="#e0e7ff" opacity="0.72"/>
      <circle cx="306.6" cy="307.1" r="2.9" fill="#e0e7ff" opacity="0.74"/>
      <circle cx="185.7" cy="317.8" r="1.6" fill="#a5b4fc" opacity="0.83"/>
      <circle cx="299.0" cy="260.0" r="2.9" fill="#67e8f9" opacity="0.83"/>
      <circle cx="330.9" cy="308.7" r="2.2" fill="#e0e7ff" opacity="0.81"/>
      <circle cx="310.4" cy="184.6" r="3.3" fill="#a5b4fc" opacity="0.94"/>
      <circle cx="247.7" cy="340.3" r="2.9" fill="#e0e7ff" opacity="0.94"/>
      <circle cx="252.4" cy="193.6" r="1.9" fill="#e0e7ff" opacity="0.39"/>
      <circle cx="307.7" cy="248.4" r="2.5" fill="#e0e7ff" opacity="0.42"/>
      <circle cx="223.6" cy="288.8" r="1.9" fill="#a5b4fc" opacity="0.66"/>
      <circle cx="289.2" cy="173.9" r="2.9" fill="#a5b4fc" opacity="0.47"/>
      <circle cx="286.9" cy="318.3" r="2.2" fill="#e0e7ff" opacity="0.64"/>
      <circle cx="207.0" cy="263.7" r="2.5" fill="#e0e7ff" opacity="0.78"/>
      <circle cx="279.4" cy="216.0" r="1.9" fill="#e0e7ff" opacity="0.74"/>
      <circle cx="216.6" cy="180.9" r="2.9" fill="#e0e7ff" opacity="0.79"/>
      <circle cx="321.7" cy="260.5" r="1.9" fill="#e0e7ff" opacity="0.92"/>
      <circle cx="319.2" cy="307.0" r="1.6" fill="#e0e7ff" opacity="0.66"/>
      <circle cx="279.1" cy="189.7" r="3.3" fill="#a5b4fc" opacity="0.37"/>
      <circle cx="237.0" cy="295.7" r="1.6" fill="#e0e7ff" opacity="0.57"/>
      <circle cx="183.7" cy="194.8" r="1.6" fill="#67e8f9" opacity="0.37"/>
      <circle cx="290.9" cy="220.0" r="1.6" fill="#e0e7ff" opacity="0.73"/>
      <circle cx="298.5" cy="177.8" r="1.6" fill="#e0e7ff" opacity="0.62"/>
      <circle cx="180.2" cy="240.1" r="1.6" fill="#e0e7ff" opacity="0.95"/>
      <circle cx="346.8" cy="275.5" r="3.3" fill="#e0e7ff" opacity="0.95"/>
      <circle cx="277.0" cy="307.3" r="2.5" fill="#e0e7ff" opacity="0.58"/>
      <circle cx="205.2" cy="193.5" r="2.9" fill="#67e8f9" opacity="0.47"/>
      <circle cx="257.4" cy="203.9" r="1.6" fill="#a5b4fc" opacity="0.73"/>
      <circle cx="320.9" cy="322.6" r="1.6" fill="#a5b4fc" opacity="0.72"/>
      <circle cx="309.7" cy="283.4" r="1.9" fill="#e0e7ff" opacity="0.6"/>
      <circle cx="307.1" cy="196.3" r="3.3" fill="#67e8f9" opacity="0.86"/>
      <circle cx="274.6" cy="177.2" r="1.6" fill="#e0e7ff" opacity="0.47"/>
      <circle cx="181.1" cy="219.7" r="1.9" fill="#e0e7ff" opacity="0.61"/>
      <circle cx="202.1" cy="275.7" r="2.9" fill="#e0e7ff" opacity="0.68"/>
      <circle cx="228.4" cy="165.1" r="1.6" fill="#e0e7ff" opacity="0.61"/>
      <circle cx="193.2" cy="298.2" r="2.9" fill="#a5b4fc" opacity="0.86"/>
      <circle cx="300.3" cy="283.4" r="1.9" fill="#e0e7ff" opacity="0.37"/>
      <circle cx="223.0" cy="172.8" r="1.6" fill="#e0e7ff" opacity="0.85"/>
      <circle cx="194.0" cy="327.6" r="1.9" fill="#e0e7ff" opacity="0.77"/>
      <circle cx="220.3" cy="333.2" r="2.5" fill="#e0e7ff" opacity="0.47"/>
      <circle cx="327.7" cy="220.9" r="2.9" fill="#67e8f9" opacity="0.78"/>
      <circle cx="216.1" cy="215.2" r="1.6" fill="#e0e7ff" opacity="0.35"/>
      <circle cx="214.1" cy="252.8" r="1.9" fill="#67e8f9" opacity="0.63"/>
      <circle cx="300.1" cy="219.0" r="2.9" fill="#e0e7ff" opacity="0.54"/>
      <circle cx="203.5" cy="319.8" r="1.6" fill="#a5b4fc" opacity="0.71"/>
      <circle cx="202.6" cy="306.9" r="3.3" fill="#e0e7ff" opacity="0.47"/>
      <circle cx="251.5" cy="310.0" r="1.9" fill="#a5b4fc" opacity="0.93"/>
      <circle cx="183.3" cy="267.8" r="2.9" fill="#67e8f9" opacity="0.67"/>
      <circle cx="223.7" cy="221.3" r="2.2" fill="#e0e7ff" opacity="0.47"/>
      <circle cx="323.4" cy="279.1" r="3.3" fill="#67e8f9" opacity="0.79"/>
      <circle cx="336.0" cy="299.8" r="1.6" fill="#e0e7ff" opacity="0.4"/>
      <circle cx="215.0" cy="232.9" r="2.2" fill="#e0e7ff" opacity="0.65"/>
      <circle cx="263.9" cy="305.6" r="2.5" fill="#e0e7ff" opacity="0.65"/>
      <circle cx="283.2" cy="329.1" r="3.3" fill="#a5b4fc" opacity="0.65"/>
      <circle cx="308.9" cy="269.4" r="2.5" fill="#e0e7ff" opacity="0.86"/>
      <circle cx="255.0" cy="331.2" r="2.5" fill="#67e8f9" opacity="0.95"/>
      <circle cx="314.2" cy="293.8" r="2.5" fill="#a5b4fc" opacity="0.63"/>
      <circle cx="271.8" cy="196.1" r="1.6" fill="#e0e7ff" opacity="0.5"/>
      <circle cx="190.7" cy="250.9" r="1.9" fill="#a5b4fc" opacity="0.94"/>
      <circle cx="284.5" cy="341.3" r="2.5" fill="#e0e7ff" opacity="0.61"/>
      <circle cx="225.0" cy="344.0" r="1.6" fill="#e0e7ff" opacity="0.8"/>
      <circle cx="201.6" cy="249.9" r="2.2" fill="#e0e7ff" opacity="0.72"/>
      <circle cx="243.5" cy="198.6" r="1.6" fill="#e0e7ff" opacity="0.64"/>
      <circle cx="178.8" cy="294.8" r="3.3" fill="#67e8f9" opacity="0.9"/>
      <circle cx="349.5" cy="254.9" r="2.5" fill="#e0e7ff" opacity="0.45"/>
      <circle cx="222.6" cy="206.2" r="3.3" fill="#67e8f9" opacity="0.43"/>
      <circle cx="202.6" cy="236.7" r="1.9" fill="#e0e7ff" opacity="0.72"/>
      <circle cx="215.6" cy="320.4" r="2.2" fill="#67e8f9" opacity="0.59"/>
      <circle cx="163.2" cy="245.3" r="1.9" fill="#e0e7ff" opacity="0.61"/>
      <circle cx="175.5" cy="279.7" r="1.6" fill="#e0e7ff" opacity="0.36"/>
      <circle cx="205.6" cy="305.7" r="8" fill="#22d3ee" opacity="0.16"/>
      <circle cx="205.6" cy="305.7" r="3.6" fill="#22d3ee" opacity="0.95"/>
      <circle cx="228.3" cy="198.3" r="8" fill="#22d3ee" opacity="0.16"/>
      <circle cx="228.3" cy="198.3" r="3.6" fill="#22d3ee" opacity="0.95"/>
      <circle cx="315.1" cy="233.9" r="8" fill="#22d3ee" opacity="0.16"/>
      <circle cx="315.1" cy="233.9" r="3.6" fill="#22d3ee" opacity="0.95"/>
      <circle cx="310.7" cy="299.6" r="8" fill="#22d3ee" opacity="0.16"/>
      <circle cx="310.7" cy="299.6" r="3.6" fill="#22d3ee" opacity="0.95"/>
    </g>
    <circle cx="256" cy="256" r="103.0" fill="none" stroke="#22d3ee" strokeWidth="2.5" opacity="0.55"/>
    <circle cx="256" cy="256" r="34.0" fill="#05060f"/>
    <circle cx="256" cy="256" r="34.0" fill="none" stroke="#67e8f9" strokeWidth="3" opacity="0.9"/>
    <circle cx="256" cy="256" r="27.0" fill="none" stroke="#22d3ee" strokeWidth="1.5" opacity="0.3"/>
    <path d="M37 256 C 128 100, 384 100, 475 256 C 384 412, 128 412, 37 256 Z"
      fill="none" stroke={"url(#" + uid + "Lid)"} strokeWidth="15" strokeLinejoin="round"/>
    </svg>
  );
}
