// Modern stroke icon set, inlined so there's no icon-font or external
// dependency. Icons inherit color via stroke="currentColor" and the size via
// the `size` prop, so they adapt to light/dark themes automatically.
//
// THIRD-PARTY ATTRIBUTION (required — do not delete)
// -------------------------------------------------
// Some glyphs below reproduce path data from the Feather and Lucide icon sets
// verbatim. Both licences require the notice be retained in redistributions,
// and this file is minified into the shipped JS bundle, so the notice ships
// with it (docs/security/LICENSE_AUDIT_2026-09-03.md §2.3):
//
//   Feather - Copyright (c) 2013-2023 Cole Bemis - MIT License
//             https://github.com/feathericons/feather
//   Lucide  - Copyright (c) for portions held by Cole Bemis 2013-2022 as part
//             of Feather (MIT); all other copyright held by Lucide
//             Contributors 2022 - ISC License
//             https://github.com/lucide-icons/lucide
//
//   MIT: Permission is hereby granted, free of charge, to any person obtaining
//   a copy of this software and associated documentation files (the
//   "Software"), to deal in the Software without restriction, including
//   without limitation the rights to use, copy, modify, merge, publish,
//   distribute, sublicense, and/or sell copies of the Software, and to permit
//   persons to whom the Software is furnished to do so, subject to the
//   following conditions: The above copyright notice and this permission
//   notice shall be included in all copies or substantial portions of the
//   Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
//
//   ISC: Permission to use, copy, modify, and/or distribute this software for
//   any purpose with or without fee is hereby granted, provided that the above
//   copyright notice and this permission notice appear in all copies. THE
//   SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
//   REGARD TO THIS SOFTWARE.
//
// The full licence texts ship with the product at
// /licenses/icons/feather-lucide-NOTICE.txt (generated by
// src/frontend/scripts/gen-licenses.mjs into public/licenses/) and are listed
// in docs/THIRD_PARTY_LICENSES.md. Entries whose upstream glyph the audit
// verified character-for-character carry an inline `upstream:` note below; the
// notice covers any other glyph that matches upstream, so ADD a note rather
// than removing one if you copy a new icon in.

type Props = { name: string; size?: number; className?: string; style?: React.CSSProperties };

const PATHS: Record<string, JSX.Element> = {
  // Automation — a workflow: two nodes wired through a junction.
  automation: (
    <>
      <rect x="3" y="3" width="6" height="6" rx="1" />
      <rect x="15" y="15" width="6" height="6" rx="1" />
      <path d="M9 6h5a4 4 0 0 1 4 4v5" />
      <circle cx="6" cy="18" r="3" />
    </>
  ),
  overview: (
    <>
      <rect x="3" y="3" width="7" height="9" rx="1" />
      <rect x="14" y="3" width="7" height="5" rx="1" />
      <rect x="14" y="12" width="7" height="9" rx="1" />
      <rect x="3" y="16" width="7" height="5" rx="1" />
    </>
  ),
  search: (
    <>
      <circle cx="11" cy="11" r="7" />
      <line x1="21" y1="21" x2="16.65" y2="16.65" />
    </>
  ),
  // Explore — a compass, the modern convention for ad-hoc/query-first views.
  // upstream: Feather `compass` (MIT) — verbatim path data.
  explore: (
    <>
      <circle cx="12" cy="12" r="10" />
      <polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88" />
    </>
  ),
  // Infrastructure — a server stack for the device fleet.
  infrastructure: (
    <>
      <rect x="2" y="3" width="20" height="8" rx="2" />
      <rect x="2" y="13" width="20" height="8" rx="2" />
      <line x1="6" y1="7" x2="6.01" y2="7" />
      <line x1="6" y1="17" x2="6.01" y2="17" />
    </>
  ),
  analytics: (
    <>
      <path d="M3 3v18h18" />
      <path d="m7 14 4-4 3 3 5-6" />
    </>
  ),
  datasets: (
    <>
      <ellipse cx="12" cy="5" rx="8" ry="3" />
      <path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5" />
      <path d="M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6" />
    </>
  ),
  // upstream: Feather `grid` (MIT) — verbatim path data.
  dashboards: (
    <>
      <rect x="3" y="3" width="7" height="7" rx="1" />
      <rect x="14" y="3" width="7" height="7" rx="1" />
      <rect x="14" y="14" width="7" height="7" rx="1" />
      <rect x="3" y="14" width="7" height="7" rx="1" />
    </>
  ),
  alerts: (
    <>
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </>
  ),
  // upstream: Feather `file-text` (MIT) — verbatim path data.
  reports: (
    <>
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <path d="M14 2v6h6" />
      <line x1="8" y1="13" x2="16" y2="13" />
      <line x1="8" y1="17" x2="16" y2="17" />
    </>
  ),
  topology: (
    <>
      <circle cx="18" cy="5" r="3" />
      <circle cx="6" cy="12" r="3" />
      <circle cx="18" cy="19" r="3" />
      <line x1="8.6" y1="10.7" x2="15.4" y2="6.3" />
      <line x1="8.6" y1="13.3" x2="15.4" y2="17.7" />
    </>
  ),
  copilot: <path d="m12 3 1.9 5.8L20 11l-6.1 2.2L12 19l-1.9-5.8L4 11l6.1-2.2z" />,
  // upstream: Feather `sliders` (MIT) — verbatim path data.
  settings: (
    <>
      <line x1="4" y1="21" x2="4" y2="14" />
      <line x1="4" y1="10" x2="4" y2="3" />
      <line x1="12" y1="21" x2="12" y2="12" />
      <line x1="12" y1="8" x2="12" y2="3" />
      <line x1="20" y1="21" x2="20" y2="16" />
      <line x1="20" y1="12" x2="20" y2="3" />
      <line x1="1" y1="14" x2="7" y2="14" />
      <line x1="9" y1="8" x2="15" y2="8" />
      <line x1="17" y1="16" x2="23" y2="16" />
    </>
  ),
  // Stack — layered planes, for the platform's own infra-stack section.
  stack: (
    <>
      <path d="m12 2 9 5-9 5-9-5 9-5z" />
      <path d="m3 12 9 5 9-5" />
      <path d="m3 17 9 5 9-5" />
    </>
  ),
  // upstream: Lucide `sliders-horizontal` (ISC) — verbatim path data.
  // Administration — horizontal control sliders (the "controls" mark; the
  // vertical-sliders glyph above stays as `settings` for its other usages).
  sliders: (
    <>
      <line x1="21" y1="5" x2="14" y2="5" />
      <line x1="10" y1="5" x2="3" y2="5" />
      <line x1="21" y1="12" x2="12" y2="12" />
      <line x1="8" y1="12" x2="3" y2="12" />
      <line x1="21" y1="19" x2="16" y2="19" />
      <line x1="12" y1="19" x2="3" y2="19" />
      <line x1="14" y1="3" x2="14" y2="7" />
      <line x1="8" y1="10" x2="8" y2="14" />
      <line x1="16" y1="17" x2="16" y2="21" />
    </>
  ),
  // upstream: Feather `activity` (MIT) — verbatim path data.
  logo: <path d="M2 12h4l3 8 4-16 3 8h6" />,
  // Monitoring — a gauge/speedometer (active health watching).
  monitoring: (
    <>
      <path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" />
      <path d="M12 3a9 9 0 0 0-9 9 9 9 0 0 0 1.5 5" />
      <path d="M12 3a9 9 0 0 1 9 9 9 9 0 0 1-1.5 5" />
      <line x1="13.5" y1="10.5" x2="17" y2="7" />
    </>
  ),
  // Incident Response — a siren/alert with response rays.
  incident: (
    <>
      <path d="M7 18a5 5 0 0 1 10 0z" />
      <line x1="5" y1="18" x2="19" y2="18" />
      <line x1="12" y1="6" x2="12" y2="3" />
      <line x1="6" y1="8" x2="4" y2="6" />
      <line x1="18" y1="8" x2="20" y2="6" />
    </>
  ),
  // Metrics — a line chart trend.
  metrics: (
    <>
      <path d="M3 3v18h18" />
      <path d="m6 15 4-5 3 3 5-7" />
    </>
  ),
  // Flows — directional flow arrows (traffic movement).
  flows: (
    <>
      <path d="M3 7h13l-3-3" />
      <path d="M16 7l-3 3" />
      <path d="M21 17H8l3 3" />
      <path d="M8 17l3-3" />
    </>
  ),
  // Logs — stacked log lines.
  logs: (
    <>
      <line x1="4" y1="6" x2="20" y2="6" />
      <line x1="4" y1="12" x2="20" y2="12" />
      <line x1="4" y1="18" x2="14" y2="18" />
    </>
  ),
  // Security policy affordances.
  // upstream: Feather `shield` (MIT) — verbatim path data.
  shield: <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />,
  // upstream: Feather `lock` (MIT) — verbatim path data.
  lock: (
    <>
      <rect x="3" y="11" width="18" height="11" rx="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </>
  ),
  // upstream: Feather `unlock` (MIT) — verbatim path data.
  unlock: (
    <>
      <rect x="3" y="11" width="18" height="11" rx="2" />
      <path d="M7 11V7a5 5 0 0 1 9.9-1" />
    </>
  ),
  // upstream: Feather `arrow-up` / `arrow-down` (MIT) — verbatim path data.
  "arrow-up": (
    <>
      <line x1="12" y1="19" x2="12" y2="5" />
      <polyline points="5 12 12 5 19 12" />
    </>
  ),
  "arrow-down": (
    <>
      <line x1="12" y1="5" x2="12" y2="19" />
      <polyline points="19 12 12 19 5 12" />
    </>
  ),
  "chevron-left": <path d="m15 18-6-6 6-6" />,
  "chevron-right": <path d="m9 18 6-6-6-6" />,
  "chevron-down": <path d="m6 9 6 6 6-6" />,
  // upstream: Feather `x` (MIT) — verbatim path data.
  close: (
    <>
      <line x1="18" y1="6" x2="6" y2="18" />
      <line x1="6" y1="6" x2="18" y2="18" />
    </>
  ),
  // pin — a thumbtack for the Inspector "keep open across selections" toggle.
  pin: (
    <>
      <line x1="12" y1="17" x2="12" y2="22" />
      <path d="M9 2h6l-1 7 3 3v2H7v-2l3-3-1-7z" />
    </>
  ),
  // Account / session + footer-utility icons (rail bottom cluster).
  user: (
    <>
      <circle cx="12" cy="8" r="4" />
      <path d="M4 21c0-4 3.6-6 8-6s8 2 8 6" />
    </>
  ),
  help: (
    <>
      <circle cx="12" cy="12" r="10" />
      <path d="M9.1 9a3 3 0 0 1 5.8 1c0 2-3 2.5-3 4" />
      <line x1="12" y1="17" x2="12.01" y2="17" />
    </>
  ),
  // info — an "i" in a circle, for hover-to-explain affordances.
  info: (
    <>
      <circle cx="12" cy="12" r="10" />
      <line x1="12" y1="16" x2="12" y2="11" />
      <line x1="12" y1="8" x2="12.01" y2="8" />
    </>
  ),
  // mail — envelope, for the Email (SMTP) channel.
  // upstream: Lucide `mail` (ISC) — verbatim path data.
  mail: (
    <>
      <rect x="2" y="4" width="20" height="16" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </>
  ),
  // smartphone — for the grouped SMS & Push (mobile) channel.
  smartphone: (
    <>
      <rect x="5" y="2" width="14" height="20" rx="2.5" />
      <line x1="12" y1="18" x2="12.01" y2="18" />
    </>
  ),
  // bell — push notifications (ntfy).
  bell: (
    <>
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </>
  ),
  // key — Single Sign-On (OIDC) / federated credentials.
  key: (
    <>
      <circle cx="7.5" cy="15.5" r="4.5" />
      <path d="m10.7 12.3 8.3-8.3" />
      <path d="m17 5 2.5 2.5" />
      <path d="m14 8 2.5 2.5" />
    </>
  ),
  // eye / eye-off — show/hide affordance for password fields.
  eye: (
    <>
      <path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </>
  ),
  "eye-off": (
    <>
      <path d="M9.9 4.24A9.1 9.1 0 0 1 12 4c6.5 0 10 7 10 7a13.2 13.2 0 0 1-2.16 2.83" />
      <path d="M6.06 6.06A13.2 13.2 0 0 0 2 11s3.5 7 10 7a9.1 9.1 0 0 0 3.94-.88" />
      <path d="M9.9 9.9a3 3 0 0 0 4.2 4.2" />
      <line x1="2" y1="2" x2="22" y2="22" />
    </>
  ),
  // check — requirement met / success.
  // upstream: Lucide `check` (ISC) — verbatim path data.
  check: <path d="M20 6 9 17l-5-5" />,
  // chevron — right-pointing disclosure; rotate 90° for expanded state.
  // upstream: Lucide `chevron-right` (ISC); the chevron-left/right/down
  // trio above is the same Lucide family — verbatim path data.
  chevron: <path d="m9 6 6 6-6 6" />,
  // arrow-up-right — "open detail / go to" affordance (internal navigation).
  "arrow-up-right": (
    <>
      <line x1="7" y1="17" x2="17" y2="7" />
      <polyline points="7 7 17 7 17 17" />
    </>
  ),
  // external — opens in a new tab.
  // upstream: Lucide `external-link` (ISC) — verbatim path data.
  external: (
    <>
      <path d="M15 3h6v6" />
      <path d="M10 14 21 3" />
      <path d="M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5" />
    </>
  ),
  // refresh — circular re-fetch / reload.
  refresh: (
    <>
      <path d="M21 12a9 9 0 1 1-2.64-6.36" />
      <path d="M21 3v5h-5" />
    </>
  ),
  // maximize — resize/expand a panel.
  // upstream: Feather `maximize` (MIT) — verbatim path data.
  maximize: (
    <>
      <path d="M8 3H5a2 2 0 0 0-2 2v3" />
      <path d="M16 3h3a2 2 0 0 1 2 2v3" />
      <path d="M8 21H5a2 2 0 0 1-2-2v-3" />
      <path d="M16 21h3a2 2 0 0 0 2-2v-3" />
    </>
  ),
  // directory — LDAP / Active Directory (a tree of nodes).
  directory: (
    <>
      <rect x="9" y="2" width="6" height="5" rx="1" />
      <rect x="3" y="17" width="6" height="5" rx="1" />
      <rect x="15" y="17" width="6" height="5" rx="1" />
      <path d="M12 7v5M6 17v-2a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v2" />
    </>
  ),
  // docs — a document with text lines, for the REST API reference.
  // upstream: Feather `file-text` (MIT) — verbatim path data plus one extra line.
  docs: (
    <>
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <path d="M14 2v6h6" />
      <line x1="8" y1="13" x2="16" y2="13" />
      <line x1="8" y1="17" x2="16" y2="17" />
      <line x1="8" y1="9" x2="10" y2="9" />
    </>
  ),
  // server — TACACS+ AAA host.
  server: (
    <>
      <rect x="3" y="4" width="18" height="7" rx="2" />
      <rect x="3" y="13" width="18" height="7" rx="2" />
      <line x1="7" y1="7.5" x2="7.01" y2="7.5" />
      <line x1="7" y1="16.5" x2="7.01" y2="16.5" />
    </>
  ),
  support: (
    <>
      <circle cx="12" cy="12" r="9" />
      <circle cx="12" cy="12" r="3.5" />
      <line x1="5" y1="5" x2="9.5" y2="9.5" />
      <line x1="14.5" y1="14.5" x2="19" y2="19" />
      <line x1="19" y1="5" x2="14.5" y2="9.5" />
      <line x1="9.5" y1="14.5" x2="5" y2="19" />
    </>
  ),
  // upstream: Feather `log-out` (MIT) — verbatim path data.
  logout: (
    <>
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" y1="12" x2="9" y2="12" />
    </>
  ),
};

export default function Icon({ name, size = 18, className, style }: Props) {
  return (
    <svg
      className={className}
      style={style}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.75"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      {PATHS[name] ?? PATHS.overview}
    </svg>
  );
}
