// @ts-check
// The docs sidebar is AUTOGENERATED from the ./docs folder tree: each folder is a
// category (labelled + ordered by its _category_.json), each Markdown file a page
// (ordered by sidebar_position in its frontmatter). Adding a page = dropping a
// file in the right folder; no edits here.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
