apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoria:8428
    editable: false

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    editable: false
    jsonData:
      defaultDatabase: netops
      protocol: http
      port: 8123
      server: clickhouse
      tlsSkipVerify: true
      username: ${CLICKHOUSE_USER}
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
