"""GENERATED — DO NOT EDIT. Baked from telemetry-catalog/events.yaml.

    cd telemetry-catalog && python3 bake_rules.py

`telemetry-catalog/` is NOT shipped inside the correlation image (the Dockerfile
copies `src/correlation/` only), so the parser rules are compiled into this
module at development time rather than read from YAML at runtime — a runtime
read would resolve to the real rules in tests and to NOTHING in production.

`test_bake_drift.py` re-bakes and compares, so this file cannot silently drift
from the catalog it was baked from. Edit `events.yaml`, then re-run the bake.
"""

from __future__ import annotations

from typing import Any

from rule_model import Rule, compile_rule, install_fidelity, rules_hash

#: The catalog file this module was baked from.
SOURCE = "telemetry-catalog/events.yaml"

#: HAND-BUMPED in events.yaml on any rule change; rides on every signal.
PARSER_REV = '2026-09-02-a9b'

#: The telemetry-catalog event-family fidelity ladder, as of PARSER_REV — the
#: families that declare a `fidelity_status`. A family the catalog knows but
#: leaves undeclared, and a rule with no family at all, both stamp "code": the
#: grammar exists only in the rule table and the catalog vouches for nothing.
CATALOG_EVENT_FIDELITY: dict[str, str] = {'bgp_route_churn': 'doc_claimed',
 'stp_topology_notification': 'doc_claimed',
 'mac_move': 'doc_claimed'}

install_fidelity(CATALOG_EVENT_FIDELITY)

#: The rule rows, in CLASSIFICATION ORDER. Order is behaviour: the interpreter
#: walks a lane's rules in sequence, first match wins.
_ROWS: tuple[dict[str, Any], ...] = (
    {'rule_id': 'syslog.isis.adjacency_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'isis_adjacency_change',
     'entity_type': 'device',
     'family': 'isis_adjacency_change',
     'vendors': ['nokia', 'cisco'],
     'markers': ['ISISADJACENCYCHANGE', 'CLNS'],
     'state_re': 'to state\\s+(\\w+)',
     'guard': {'any': [{'contains': ['msg_u', 'ISISADJACENCYCHANGE']}, {'all': [{'contains': ['ctoken', 'CLNS']}, {'contains': ['ctoken', 'ADJ']}]}]},
     'extract': {'peer': {'re': [['msg', '\\b([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\.[0-9a-fA-F]{4})\\b', 1, '']]},
                 'ifname': {'re': [['msg', '\\busing interface\\s+([A-Za-z][\\w/.\\-]*)', 1, 'i']]},
                 'tgt': {'re': [['msg', 'to state\\s+(\\w+)', 1, 'i']]},
                 'state': {'scan': {'target': 'tgt',
                                    'order': [['down', '\\b(?:down|idle|init|backward|failed)\\b', 'i'], ['up', '\\b(?:up|established|full)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'isis_adjacency_change',
              'metric': 'isis_adjacency',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|isis_adj|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'}, 'state': {'var': 'state'}, 'tag': {'alt': [{'var': 'tag'}, {'const': 'isisAdjacencyChange'}]}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.bgp.adjacency_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'bgp_adjacency_change',
     'entity_type': 'device',
     'family': 'bgp_adjacency_change',
     'vendors': ['cisco', 'arista', 'juniper'],
     'markers': ['ADJCHANGE', 'ADJCHG'],
     'guard': {'all': [{'any': [{'contains': ['ctoken', 'ADJCHANGE']}, {'contains': ['ctoken', 'ADJCHG']}]}, {'contains': ['ctoken', 'BGP']}]},
     'extract': {'peer': {'re': [['msg', '\\b(\\d{1,3}(?:\\.\\d{1,3}){3})\\b', 1, '']]},
                 'tgt_new': {'re': [['msg', '\\bnew state\\s+(\\w+)', 1, 'i']]},
                 'state': {'scan': {'target': 'tgt_new',
                                    'target_scope': 'catalog',
                                    'target_fallthrough': True,
                                    'order': [['down', '\\b(?:down|idle|init|backward|failed)\\b', 'i'], ['up', '\\b(?:up|established|full)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'bgp_adjacency_change',
              'metric': 'bgp_adjacency',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|bgp_adj|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'}, 'state': {'var': 'state'}, 'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.ospf.adjacency_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'ospf_adjacency_change',
     'entity_type': 'device',
     'family': 'ospf_adjacency_change',
     'vendors': ['cisco', 'arista'],
     'markers': ['ADJCHANGE', 'ADJCHG'],
     'guard': {'all': [{'any': [{'contains': ['ctoken', 'ADJCHANGE']}, {'contains': ['ctoken', 'ADJCHG']}]}, {'contains': ['ctoken', 'OSPF']}]},
     'extract': {'peer': {'re': [['msg', '\\b(\\d{1,3}(?:\\.\\d{1,3}){3})\\b', 1, '']]},
                 'ifname': {'re': [['msg', '\\bon\\s+([A-Za-z][\\w/.\\-]*)', 1, 'i']]},
                 'state': {'scan': {'order': [['down', '\\b(?:down|idle|init|backward|failed)\\b', 'i'], ['up', '\\b(?:up|established|full)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'ospf_adjacency_change',
              'metric': 'ospf_adjacency',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|ospf_adj|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'}, 'state': {'var': 'state'}, 'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.routing.adjacency_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'routing_adjacency_change',
     'entity_type': 'device',
     'family': None,
     'vendors': ['generic'],
     'markers': ['ADJCHANGE', 'ADJCHG'],
     'guard': {'any': [{'contains': ['ctoken', 'ADJCHANGE']}, {'contains': ['ctoken', 'ADJCHG']}]},
     'extract': {'peer': {'re': [['msg', '\\b(\\d{1,3}(?:\\.\\d{1,3}){3})\\b', 1, '']]},
                 'state': {'scan': {'order': [['down', '\\b(?:down|idle|init|backward|failed)\\b', 'i'], ['up', '\\b(?:up|established|full)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'routing_adjacency_change',
              'metric': 'routing_adjacency',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|routing_adj|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'}, 'state': {'var': 'state'}, 'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.bgp.notification',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'bgp_adjacency_change',
     'entity_type': 'device',
     'family': 'bgp_adjacency_change',
     'vendors': ['cisco', 'juniper'],
     'markers': ['NBR_RESET', 'MAXPFX', 'NOTIFICATION'],
     'pattern_src': '\\b(?:NOTIFICATION\\s+(?:sent\\s+to|received\\s+from)|maximum\\s+prefix-limit)\\b',
     'state': 'down',
     'severity': 'high',
     'guard': {'all': [{'any': [{'all': [{'contains': ['ctoken', 'BGP']},
                                         {'any': [{'contains': ['ctoken', 'NBR_RESET']},
                                                  {'contains': ['ctoken', 'MAXPFX']},
                                                  {'contains': ['ctoken', 'NOTIFICATION']}]}]},
                                {'re': ['msg', '\\b(?:NOTIFICATION\\s+(?:sent\\s+to|received\\s+from)|maximum\\s+prefix-limit)\\b', 'i']}]},
                       {'not': {'contains': ['ctoken', 'NBR_RESET']}},
                       {'not': {'contains': ['ctoken', 'MAXPFX']}},
                       {'any': [{'contains': ['ctoken', 'NOTIFICATION']}, {'not': {'re': ['msg', '\\bmaximum\\s+prefix-limit\\b', 'i']}}]}]},
     'extract': {'peer': {'re': [['msg', '\\b(\\d{1,3}(?:\\.\\d{1,3}){3})\\b', 1, '']]},
                 'subtype': {'case': [{'when': {'contains': ['ctoken', 'NBR_RESET']}, 'value': 'nbr_reset'},
                                      {'when': {'contains': ['ctoken', 'MAXPFX']}, 'value': 'maxpfx'},
                                      {'when': {'contains': ['ctoken', 'NOTIFICATION']}, 'value': 'notification'},
                                      {'when': {'re': ['msg', '\\bmaximum\\s+prefix-limit\\b', 'i']}, 'value': 'maxpfx'},
                                      {'when': {'always': True}, 'value': 'notification'}]},
                 'shut': {'bool': {'re': ['msg', '\\b(?:exceed(?:ed|s)?|shut\\s?down|shutdown|disabl\\w*)\\b', 'i']}},
                 'reason': {'pick': {'field': 'msg',
                                     'find': ['\\(([^)\\n]{1,64})\\)', ''],
                                     'reject': ['(?:afi|external\\s+as|internal\\s+as|instance|as)\\b|^[\\d.%\\s]+$', 'i']}},
                 'code_a': {'re': [['msg', '\\b(\\d{1,2})/(\\d{1,2})\\b', 1, ''],
                                   ['msg', '\\bcode\\s+(\\d{1,2})\\b[^\\n]{0,40}?\\bsubcode\\s+(\\d{1,3})\\b', 1, 'i']]},
                 'code_b': {'re': [['msg', '\\b(\\d{1,2})/(\\d{1,2})\\b', 2, ''],
                                   ['msg', '\\bcode\\s+(\\d{1,2})\\b[^\\n]{0,40}?\\bsubcode\\s+(\\d{1,3})\\b', 2, 'i']]},
                 'code': {'case': [{'when': {'truthy': '$code_a'}, 'value': '{code_a}/{code_b}'}]},
                 'pfx_count': {'re': [['msg', '\\breaches\\s+(\\d{1,10})\\b', 1, 'i'],
                                      ['msg', '\\bnlri:\\s*(\\d{1,10})\\b', 1, 'i'],
                                      ['msg', ':\\s*(\\d{1,10})\\s+exceed', 1, 'i']]},
                 'pfx_max': {'re': [['msg', '\\bmax(?:imum)?[\\s:]+(\\d{1,10})\\b', 1, 'i'], ['msg', '\\blimit\\s+(\\d{1,10})\\b', 1, 'i']]},
                 'state': {'const': 'down'}},
     'emit': {'kind': 'bgp_adjacency_change',
              'metric': 'bgp_adjacency',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'native_id': '{host}|bgp_adj|notify|{peer|?}|{code|-}|down|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'},
                        'state': {'var': 'state'},
                        'subtype': {'const': 'notification'},
                        'code': {'var': 'code'},
                        'reason': {'var': 'reason'},
                        'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.bgp.route_churn',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'bgp_route_churn',
     'entity_type': 'device',
     'family': 'bgp_route_churn',
     'vendors': ['cisco', 'juniper'],
     'markers': ['NBR_RESET', 'MAXPFX', 'NOTIFICATION'],
     'pattern_src': '\\b(?:NOTIFICATION\\s+(?:sent\\s+to|received\\s+from)|maximum\\s+prefix-limit)\\b',
     'state_re': '\\b(?:exceed(?:ed|s)?|shut\\s?down|shutdown|disabl\\w*)\\b',
     'guard': {'any': [{'all': [{'contains': ['ctoken', 'BGP']},
                                {'any': [{'contains': ['ctoken', 'NBR_RESET']},
                                         {'contains': ['ctoken', 'MAXPFX']},
                                         {'contains': ['ctoken', 'NOTIFICATION']}]}]},
                       {'re': ['msg', '\\b(?:NOTIFICATION\\s+(?:sent\\s+to|received\\s+from)|maximum\\s+prefix-limit)\\b', 'i']}]},
     'extract': {'peer': {'re': [['msg', '\\b(\\d{1,3}(?:\\.\\d{1,3}){3})\\b', 1, '']]},
                 'subtype': {'case': [{'when': {'contains': ['ctoken', 'NBR_RESET']}, 'value': 'nbr_reset'},
                                      {'when': {'contains': ['ctoken', 'MAXPFX']}, 'value': 'maxpfx'},
                                      {'when': {'contains': ['ctoken', 'NOTIFICATION']}, 'value': 'notification'},
                                      {'when': {'re': ['msg', '\\bmaximum\\s+prefix-limit\\b', 'i']}, 'value': 'maxpfx'},
                                      {'when': {'always': True}, 'value': 'notification'}]},
                 'shut': {'bool': {'re': ['msg', '\\b(?:exceed(?:ed|s)?|shut\\s?down|shutdown|disabl\\w*)\\b', 'i']}},
                 'reason': {'pick': {'field': 'msg',
                                     'find': ['\\(([^)\\n]{1,64})\\)', ''],
                                     'reject': ['(?:afi|external\\s+as|internal\\s+as|instance|as)\\b|^[\\d.%\\s]+$', 'i']}},
                 'code_a': {'re': [['msg', '\\b(\\d{1,2})/(\\d{1,2})\\b', 1, ''],
                                   ['msg', '\\bcode\\s+(\\d{1,2})\\b[^\\n]{0,40}?\\bsubcode\\s+(\\d{1,3})\\b', 1, 'i']]},
                 'code_b': {'re': [['msg', '\\b(\\d{1,2})/(\\d{1,2})\\b', 2, ''],
                                   ['msg', '\\bcode\\s+(\\d{1,2})\\b[^\\n]{0,40}?\\bsubcode\\s+(\\d{1,3})\\b', 2, 'i']]},
                 'code': {'case': [{'when': {'truthy': '$code_a'}, 'value': '{code_a}/{code_b}'}]},
                 'pfx_count': {'re': [['msg', '\\breaches\\s+(\\d{1,10})\\b', 1, 'i'],
                                      ['msg', '\\bnlri:\\s*(\\d{1,10})\\b', 1, 'i'],
                                      ['msg', ':\\s*(\\d{1,10})\\s+exceed', 1, 'i']]},
                 'pfx_max': {'re': [['msg', '\\bmax(?:imum)?[\\s:]+(\\d{1,10})\\b', 1, 'i'], ['msg', '\\blimit\\s+(\\d{1,10})\\b', 1, 'i']]},
                 'maxpfx': {'bool': {'eq': ['$subtype', 'maxpfx']}},
                 'state': {'case': [{'when': {'all': [{'var_true': 'maxpfx'}, {'var_true': 'shut'}]}, 'value': 'down'},
                                    {'when': {'always': True}, 'value': 'churn'}]}},
     'emit': {'kind': 'bgp_route_churn',
              'metric': 'bgp_route_churn',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|bgp_churn|{subtype}|{peer|?}|{pfx_count|-}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'},
                        'state': {'var': 'state'},
                        'subtype': {'var': 'subtype'},
                        'reason': {'var': 'reason'},
                        'prefix_count': {'var': 'pfx_count'},
                        'prefix_max': {'var': 'pfx_max'},
                        'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.link.state_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'link_state_change',
     'entity_type': 'interface',
     'family': 'link_state_change',
     'vendors': ['cisco', 'arista'],
     'markers': ['UPDOWN'],
     'guard': {'all': [{'any': [{'contains': ['ctoken', 'LINK']}, {'contains': ['ctoken', 'LINEPROTO']}]}, {'contains': ['ctoken', 'UPDOWN']}]},
     'extract': {'ifname': {'alt': [{'re': [['msg', '[Ii]nterface\\s+([A-Za-z][\\w/.\\-]*)', 1, '']]}, {'const': 'unknown'}]},
                 'state': {'scan': {'order': [['down', '\\b(?:down|idle|init|backward|failed)\\b', 'i'], ['up', '\\b(?:up|established|full)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'link_state_change',
              'metric': 'link_state',
              'modality': 'control_plane',
              'entity': {'type': 'interface', 'id': '{host}:{ifname}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|link|{ifname}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'ifname'}, 'state': {'var': 'state'}, 'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.lldp.neighbor_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'lldp_neighbor_change',
     'entity_type': 'interface',
     'family': 'lldp_neighbor_change',
     'vendors': ['arista', 'nokia'],
     'markers': ['LLDP', 'REMOTEPEER'],
     'state_re': '\\b(?:removed|deleted|aged)\\b',
     'guard': {'any': [{'all': [{'contains': ['ctoken', 'LLDP']}, {'contains': ['ctoken', 'NEIGHBOR']}]}, {'contains': ['msg_u', 'REMOTEPEER']}]},
     'extract': {'ifname': {'alt': [{'re': [['msg', 'on interface\\s+([A-Za-z][\\w/.\\-]*)', 1, 'i'],
                                            ['msg', '[Ii]nterface\\s+([A-Za-z][\\w/.\\-]*)', 1, '']]},
                                    {'const': 'unknown'}]},
                 'state': {'scan': {'order': [['down', '\\b(?:removed|deleted|aged)\\b', 'i'], ['up', '\\b(?:added|new)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'lldp_neighbor_change',
              'metric': 'lldp_neighbor',
              'modality': 'control_plane',
              'entity': {'type': 'interface', 'id': '{host}:{ifname}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|lldp|{ifname}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'ifname'}, 'state': {'var': 'state'}, 'tag': {'alt': [{'var': 'tag'}, {'const': 'remotePeer'}]}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.stp.topology_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'stp_topology_change',
     'entity_type': 'interface',
     'family': 'stp_topology_change',
     'vendors': ['cisco', 'arista'],
     'markers': ['SPANTREE'],
     'state_re': '\\bto\\s+(forwarding|learning|discarding|blocking)\\b',
     'guard': {'all': [{'contains': ['tag', 'SPANTREE']},
                       {'any': [{'re': ['msg', '[Ii]nterface\\s+([A-Za-z][\\w/.\\-]*)', '']},
                                {'re': ['msg', '\\b((?:Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*)\\b', '']}]}]},
     'extract': {'ifname': {'re': [['msg', '[Ii]nterface\\s+([A-Za-z][\\w/.\\-]*)', 1, ''],
                                   ['msg', '\\b((?:Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*)\\b', 1, '']]},
                 'inst_a': {'re': [['msg', '\\binstance\\s+([A-Za-z0-9_\\-]{1,32})\\b', 1, 'i']]},
                 'inst_b': {'re': [['msg', '\\bvlan\\s*(\\d{1,4})\\b', 1, 'i']]},
                 'inst_c': {'re': [['msg', '\\b(MST\\d{1,4})\\b', 1, '']]},
                 'instance': {'alt': [{'var': 'inst_a'}, {'var': 'inst_b'}, {'var': 'inst_c'}]},
                 'inst_a_low': {'var': 'inst_a', 'lower': True},
                 'inst_c_low': {'var': 'inst_c', 'lower': True},
                 'inst_tok': {'case': [{'when': {'truthy': '$inst_a'}, 'value': '{inst_a_low}'},
                                       {'when': {'truthy': '$inst_b'}, 'value': 'vlan{inst_b}'},
                                       {'when': {'always': True}, 'value': '{inst_c_low}'}]},
                 'tgt': {'re': [['msg', '\\bto\\s+(forwarding|learning|discarding|blocking)\\b', 1, 'i']]},
                 'state': {'scan': {'target': 'tgt',
                                    'target_order': [['up', '(?:forwarding|learning)', 'i'], ['down', '(?:discarding|blocking)', 'i']],
                                    'order': [['down', '\\b(?:removed|discarding|blocking)\\b', 'i'], ['up', '\\b(?:added|forwarding|learning)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'stp_topology_change',
              'metric': 'stp_state',
              'modality': 'control_plane',
              'entity': {'type': 'interface', 'id': '{host}:{ifname}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|stp|{ifname}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'ifname'}, 'instance': {'var': 'instance'}, 'state': {'var': 'state'}, 'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.stp.topology_notification',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'stp_topology_change',
     'entity_type': 'device',
     'family': 'stp_topology_notification',
     'vendors': ['cisco'],
     'markers': ['SPANTREE'],
     'state_re': '\\bto\\s+(forwarding|learning|discarding|blocking)\\b',
     'guard': {'contains': ['tag', 'SPANTREE']},
     'extract': {'ifname': {'re': [['msg', '[Ii]nterface\\s+([A-Za-z][\\w/.\\-]*)', 1, ''],
                                   ['msg', '\\b((?:Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*)\\b', 1, '']]},
                 'inst_a': {'re': [['msg', '\\binstance\\s+([A-Za-z0-9_\\-]{1,32})\\b', 1, 'i']]},
                 'inst_b': {'re': [['msg', '\\bvlan\\s*(\\d{1,4})\\b', 1, 'i']]},
                 'inst_c': {'re': [['msg', '\\b(MST\\d{1,4})\\b', 1, '']]},
                 'instance': {'alt': [{'var': 'inst_a'}, {'var': 'inst_b'}, {'var': 'inst_c'}]},
                 'inst_a_low': {'var': 'inst_a', 'lower': True},
                 'inst_c_low': {'var': 'inst_c', 'lower': True},
                 'inst_tok': {'case': [{'when': {'truthy': '$inst_a'}, 'value': '{inst_a_low}'},
                                       {'when': {'truthy': '$inst_b'}, 'value': 'vlan{inst_b}'},
                                       {'when': {'always': True}, 'value': '{inst_c_low}'}]},
                 'tgt': {'re': [['msg', '\\bto\\s+(forwarding|learning|discarding|blocking)\\b', 1, 'i']]},
                 'state': {'scan': {'target': 'tgt',
                                    'target_order': [['up', '(?:forwarding|learning)', 'i'], ['down', '(?:discarding|blocking)', 'i']],
                                    'order': [['down', '\\b(?:removed|discarding|blocking)\\b', 'i'], ['up', '\\b(?:added|forwarding|learning)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'stp_topology_change',
              'metric': 'stp_state',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|stp_tcn|{instance|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{inst_tok}', 'local': True}],
              'attrs': {'interface': {'var': 'ifname'}, 'instance': {'var': 'instance'}, 'state': {'var': 'state'}, 'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.vtep.state_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'vtep_state_change',
     'entity_type': 'device',
     'family': None,
     'vendors': ['cisco'],
     'markers': ['NVE', 'VTEP'],
     'guard': {'any': [{'contains': ['ctoken', 'NVE']}, {'all': [{'contains': ['ctoken', 'VTEP']}, {'contains': ['ctoken_msg_u', 'BFD']}]}]},
     'extract': {'peer': {'re': [['msg', '\\b(\\d{1,3}(?:\\.\\d{1,3}){3})\\b', 1, '']]},
                 'state': {'scan': {'order': [['down', '\\b(?:down|idle|init|backward|failed)\\b', 'i'], ['up', '\\b(?:up|established|full)\\b', 'i']],
                                    'field': 'msg',
                                    'default': 'unknown'}}},
     'emit': {'kind': 'vtep_state_change',
              'metric': 'vtep_state',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{host}|vtep|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{peer}'}],
              'attrs': {'vtep': {'var': 'peer'}, 'state': {'var': 'state'}, 'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.evpn.mac_move',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'evpn_mac_move',
     'entity_type': 'device',
     'family': None,
     'vendors': ['arista', 'cisco'],
     'markers': ['EVPN', 'HMM', 'DUP_HOST', 'VXLAN_MAC_MOVE'],
     'pattern_src': '\\b(?:blacklisted|duplicate host|between NVE and)\\b',
     'severity': 'high',
     'guard': {'any': [{'contains': ['ctoken', 'EVPN']},
                       {'contains': ['ctoken', 'HMM']},
                       {'contains': ['ctoken', 'DUP_HOST']},
                       {'contains': ['ctoken', 'VXLAN_MAC_MOVE']},
                       {'re': ['msg', '\\b(?:blacklisted|duplicate host|between NVE and)\\b', 'i']}]},
     'extract': {'mac': {'re': [['msg', '\\b([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}|(?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2})\\b', 1, '']]},
                 'vlan': {'re': [['msg', '\\bvlan\\s*(\\d+)\\b', 1, 'i']]},
                 'vni': {'re': [['msg', '\\bvni\\s*(\\d+)\\b', 1, 'i']]},
                 'vtep': {'re': [['msg', 'VTEP\\s+(\\d{1,3}(?:\\.\\d{1,3}){3})', 1, 'i']]},
                 'blacklisted': {'bool': {'re': ['msg', 'blacklist|frozen|disabl|port[\\s-]?down', 'i']}}},
     'emit': {'kind': 'evpn_mac_move',
              'metric': 'evpn_mac_move',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'native_id': '{host}|evpn_mac|{mac|?}|vlan{vlan|?}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{mac}'}, {'t': 'vlan{vlan}'}, {'t': 'vni{vni}'}, {'t': '{vtep}'}],
              'tokens_fallback': 'host',
              'attrs': {'mac': {'var': 'mac'},
                        'vlan': {'var': 'vlan'},
                        'vni': {'var': 'vni'},
                        'vtep': {'var': 'vtep'},
                        'blacklisted': {'var': 'blacklisted'},
                        'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.fhrp.state_change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'fhrp_state_change',
     'entity_type': 'device',
     'family': None,
     'vendors': ['cisco', 'arista'],
     'markers': ['HSRP', 'VRRP', 'STANDBY'],
     'state_re': '->\\s*(\\w+)',
     'guard': {'any': [{'contains': ['ctoken', 'HSRP']}, {'contains': ['ctoken', 'VRRP']}, {'contains': ['ctoken', 'STANDBY']}]},
     'extract': {'proto': {'case': [{'when': {'contains': ['ctoken', 'VRRP']}, 'value': 'vrrp'}, {'when': {'always': True}, 'value': 'hsrp'}]},
                 'group': {'re': [['msg', '\\b[Gg]r(?:ou)?p\\s+(\\d+)\\b', 1, '']]},
                 'ifname': {'alt': [{'re': [['msg', '[Ii]nterface\\s+([A-Za-z][\\w/.\\-]*)', 1, ''],
                                            ['msg',
                                             '\\b((?:Vl(?:an)?|Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*)\\b',
                                             1,
                                             '']]},
                                    {'const': 'unknown'}]},
                 'role': {'re': [['msg', '->\\s*(\\w+)', 1, ''], ['msg', '\\bstate\\s+(\\w+)\\s*$', 1, 'i']], 'lower': True},
                 'takeover': {'bool': {'equals_any': ['$role', ['active', 'master']]}}},
     'emit': {'kind': 'fhrp_state_change',
              'metric': 'fhrp_state',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'severity': {'case': [{'when': {'var_true': 'takeover'}, 'value': 'high'}], 'default': 'warn'},
              'native_id': '{host}|fhrp|{proto}|{ifname}|grp{group|?}|{role|?}|{ts_ms}',
              'tokens': [{'t': '{host}'}, {'t': '{ifname}', 'local': True}, {'t': 'grp{group}', 'local': True}],
              'tokens_fallback': 'host',
              'attrs': {'proto': {'var': 'proto'},
                        'group': {'var': 'group'},
                        'interface': {'var': 'ifname'},
                        'state': {'var': 'role'},
                        'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.mac.flap',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'mac_flap',
     'entity_type': 'device',
     'family': 'mac_move',
     'vendors': ['cisco', 'arista'],
     'markers': ['MACFLAP', 'MAC_MOVE'],
     'pattern_src': '\\b(?:is flapping between|has moved between|mac[\\s_-]?move|mac[\\s_-]?flap)\\b',
     'state_re': '\\bflap',
     'severity': 'high',
     'guard': {'any': [{'contains': ['ctoken', 'MACFLAP']},
                       {'contains': ['ctoken', 'MAC_MOVE']},
                       {'re': ['msg', '\\b(?:is flapping between|has moved between|mac[\\s_-]?move|mac[\\s_-]?flap)\\b', 'i']}]},
     'extract': {'mac': {'re': [['msg', '\\b([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}|(?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2})\\b', 1, '']]},
                 'vlan': {'re': [['msg', '\\bvlan\\s*(\\d+)\\b', 1, 'i']]},
                 'ports': {'findall': ['msg', '\\b(?:Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*', '']},
                 'port_a': {'nth': ['ports', 0]},
                 'port_b': {'nth': ['ports', 1]},
                 'flapping': {'bool': {'any': [{'re': ['msg', '\\bflap', 'i']}, {'contains': ['ctoken', 'MACFLAP']}]}},
                 'state': {'case': [{'when': {'var_true': 'flapping'}, 'value': 'flapping'}, {'when': {'always': True}, 'value': 'moved'}]},
                 'from_port': {'re': [['msg',
                                       '\\bfrom\\s+((?:Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*)\\s+to\\s+((?:Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*)',
                                       1,
                                       'i']]},
                 'to_port': {'re': [['msg',
                                     '\\bfrom\\s+((?:Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*)\\s+to\\s+((?:Gi|Te|Fa|Po|Port-channel|Eth\\w*|GigabitEthernet|TenGigE)[\\d][\\w/.\\-]*)',
                                     2,
                                     'i']]}},
     'emit': {'kind': 'mac_flap',
              'metric': 'mac_flap',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'native_id': '{host}|mac_flap|{mac|?}|vlan{vlan|?}|{ts_ms}',
              'tokens': [{'t': '{host}'},
                         {'t': '{mac}'},
                         {'t': 'vlan{vlan}', 'local': True},
                         {'t': '{port_a}', 'local': True},
                         {'t': '{port_b}', 'local': True}],
              'tokens_fallback': 'host',
              'attrs': {'mac': {'var': 'mac'},
                        'vlan': {'var': 'vlan'},
                        'state': {'var': 'state'},
                        'port_a': {'var': 'port_a'},
                        'port_b': {'var': 'port_b'},
                        'from_port': {'var': 'from_port'},
                        'to_port': {'var': 'to_port'},
                        'tag': {'var': 'tag'}}},
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.config.change',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'device_config_change',
     'entity_type': 'device',
     'family': None,
     'fidelity_status': 'doc_claimed',
     'vendors': ['cisco', 'arista', 'juniper'],
     'markers': ['CONFIG_I', 'UI_COMMIT'],
     'severity': 'info',
     'shadow': True,
     'guard': {'any': [{'contains': ['ctoken', 'CONFIG_I']},
                       {'contains': ['ctoken', 'UI_COMMIT']},
                       {'contains': ['msg', 'CONFIG_I']},
                       {'contains': ['msg', 'UI_COMMIT']}]},
     'extract': {'user': {'re': [['msg', '\\bby\\s+([\\w.\\-\\\\@]{1,64})', 1, 'i'], ['msg', "\\bUser\\s+'([^'\\n]{1,64})'", 1, 'i']]},
                 'source': {'re': [['msg', '\\bConfigured\\s+from\\s+([\\w./\\-]{1,32})', 1, 'i']]},
                 'line': {'re': [['msg', '\\bby\\s+[\\w.\\-\\\\@]{1,64}\\s+on\\s+([\\w.@/\\-]{1,48})', 1, 'i']]},
                 'method': {'case': [{'when': {'contains': ['ctoken_msg_u', 'UI_COMMIT_COMPLETED']}, 'value': 'commit_completed'},
                                     {'when': {'contains': ['ctoken_msg_u', 'UI_COMMIT']}, 'value': 'commit'},
                                     {'when': {'always': True}, 'value': 'config_i'}]},
                 'state': {'const': 'changed'}},
     'emit': {'kind': 'device_config_change',
              'metric': 'device_config_change',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{host}'},
              'native_id': '{host}|config_change|{method}|{source|?}|{user|?}|{line|?}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'user': {'var': 'user'},
                        'source': {'var': 'source'},
                        'line': {'var': 'line'},
                        'method': {'var': 'method'},
                        'state': {'var': 'state'},
                        'tag': {'var': 'tag'}}},
     'generic': False},
    {'rule_id': 'syslog.generic.device_alarm',
     'lane': 'syslog',
     'source': 'syslog',
     'kind': 'device_alarm',
     'entity_type': 'device_or_interface',
     'family': None,
     'vendors': ['any'],
     'generic': True,
     'guard': {'severity_floor': 'syslog'},
     'extract': {'ifname': {'re': [['msg', '[Ii]nterface\\s+([A-Za-z][\\w/.\\-]*)', 1, '']]},
                 'ev_facility': {'ev': ['facility']},
                 'tag_facility': {'re': [['tag', '^%*([^-]*)', 1, '']]},
                 'facility': {'case': [{'when': {'truthy': '$ev_facility'}, 'value': '{ev_facility}'},
                                       {'when': {'always': True}, 'value': '{tag_facility}'}]},
                 'tag_mnem': {'re': [['tag', '-([^-]*)$', 1, '']]},
                 'ev_etype': {'ev': ['event_type']},
                 'mnem': {'case': [{'when': {'contains': ['tag', '-']}, 'value': '{tag_mnem}'}, {'when': {'always': True}, 'value': '{ev_etype}'}]},
                 'sev_num': {'severity_num': True},
                 'text': {'var': 'msg', 'slice': 256}},
     'emit': {'kind': 'device_alarm',
              'metric': 'device_alarm',
              'modality': 'control_plane',
              'entity': {'when': {'truthy': '$ifname'}, 'type': 'interface', 'id': '{host}:{ifname}', 'else': {'type': 'device', 'id': '{host}'}},
              'severity': {'from_severity_num': True},
              'native_id': '{host}|alarm|{facility}|{mnem|?}|{ifname|-}|{ts_ms}',
              'content_tag': 'msg',
              'tokens': [{'t': '{host}'}],
              'attrs': {'facility': {'var': 'facility'},
                        'mnemonic': {'var': 'mnem'},
                        'severity': {'var': 'sev_num'},
                        'interface': {'var': 'ifname'},
                        'tag': {'var': 'tag'},
                        'text': {'var': 'text'}}},
     'markers': [],
     'shadow': False},
    {'rule_id': 'syslog.port.transceiver_unsupported',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'transceiver_unsupported',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['cisco', 'arista', 'fortinet'],
     'severity': 'high',
     'pattern_src': 'unsupported\\s+transceiver|unqualified\\s+(sfp|transceiver|optic)|not\\s+qualified|UNSUPPORTED_TRANSCEIVER|transceiver[^\\n]{0,80}not\\s+supported',
     'guard': {'re': ['pctoken',
                      'unsupported\\s+transceiver|unqualified\\s+(sfp|transceiver|optic)|not\\s+qualified|UNSUPPORTED_TRANSCEIVER|transceiver[^\\n]{0,80}not\\s+supported',
                      'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|transceiver_unsupported|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'transceiver_unsupported'}, 'message': {'var': 'message'}},
              'kind': 'transceiver_unsupported'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.dom_rx_power_low',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'dom_rx_power_low',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'high',
     'pattern_src': '(rx|receive)[^\\n]{0,80}power[^\\n]{0,80}(low|below)[^\\n]{0,80}(alarm|threshold)|RX_POWER_LOW|low\\s+rx\\s+power',
     'guard': {'re': ['pctoken',
                      '(rx|receive)[^\\n]{0,80}power[^\\n]{0,80}(low|below)[^\\n]{0,80}(alarm|threshold)|RX_POWER_LOW|low\\s+rx\\s+power',
                      'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|dom_rx_power_low|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'dom_rx_power_low'}, 'message': {'var': 'message'}},
              'kind': 'dom_rx_power_low'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.dom_temperature_high',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'dom_temperature_high',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'high',
     'pattern_src': '(temperature|temp)[^\\n]{0,80}(high|above)[^\\n]{0,80}(alarm|threshold|warning)|TEMP_HIGH|high\\s+temperature',
     'guard': {'re': ['pctoken', '(temperature|temp)[^\\n]{0,80}(high|above)[^\\n]{0,80}(alarm|threshold|warning)|TEMP_HIGH|high\\s+temperature', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|dom_temperature_high|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'dom_temperature_high'}, 'message': {'var': 'message'}},
              'kind': 'dom_temperature_high'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.dom_lane_bias_anomaly',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'dom_lane_bias_anomaly',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'warn',
     'pattern_src': '(tx\\s+)?bias[^\\n]{0,80}(high|current)[^\\n]{0,80}(alarm|threshold)|BIAS_HIGH',
     'guard': {'re': ['pctoken', '(tx\\s+)?bias[^\\n]{0,80}(high|current)[^\\n]{0,80}(alarm|threshold)|BIAS_HIGH', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|dom_lane_bias_anomaly|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'dom_lane_bias_anomaly'}, 'message': {'var': 'message'}},
              'kind': 'dom_lane_bias_anomaly'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.prefec_ber_rising',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'prefec_ber_rising',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'high',
     'pattern_src': 'uncorrectable[^\\n]{0,80}(fec|codeword|block)|FEC[^\\n]{0,80}UNCORRECTABLE|post[-_ ]?fec[^\\n]{0,80}(error|ber)',
     'guard': {'re': ['pctoken', 'uncorrectable[^\\n]{0,80}(fec|codeword|block)|FEC[^\\n]{0,80}UNCORRECTABLE|post[-_ ]?fec[^\\n]{0,80}(error|ber)', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|prefec_ber_rising|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'prefec_ber_rising'}, 'message': {'var': 'message'}},
              'kind': 'prefec_ber_rising'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.fec_corrected_rate_high',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'fec_corrected_rate_high',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'warn',
     'pattern_src': 'pre[-_ ]?fec\\s+ber|fec[^\\n]{0,80}corrected[^\\n]{0,80}(rate|high)|CORRECTED_FEC',
     'guard': {'re': ['pctoken', 'pre[-_ ]?fec\\s+ber|fec[^\\n]{0,80}corrected[^\\n]{0,80}(rate|high)|CORRECTED_FEC', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|fec_corrected_rate_high|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'fec_corrected_rate_high'}, 'message': {'var': 'message'}},
              'kind': 'fec_corrected_rate_high'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.pcs_local_fault',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'pcs_local_fault',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'high',
     'pattern_src': 'local\\s+fault|LOCAL_FAULT',
     'guard': {'re': ['pctoken', 'local\\s+fault|LOCAL_FAULT', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|pcs_local_fault|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'pcs_local_fault'}, 'message': {'var': 'message'}},
              'kind': 'pcs_local_fault'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.pcs_remote_fault',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'pcs_remote_fault',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'high',
     'pattern_src': 'remote\\s+fault|REMOTE_FAULT',
     'guard': {'re': ['pctoken', 'remote\\s+fault|REMOTE_FAULT', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|pcs_remote_fault|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'pcs_remote_fault'}, 'message': {'var': 'message'}},
              'kind': 'pcs_remote_fault'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.pcs_deskew_fault',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'pcs_deskew_fault',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'high',
     'pattern_src': 'deskew|align[^\\n]{0,80}(marker|lane)[^\\n]{0,80}(fail|lost)|PCS[^\\n]{0,80}DESKEW',
     'guard': {'re': ['pctoken', 'deskew|align[^\\n]{0,80}(marker|lane)[^\\n]{0,80}(fail|lost)|PCS[^\\n]{0,80}DESKEW', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|pcs_deskew_fault|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'pcs_deskew_fault'}, 'message': {'var': 'message'}},
              'kind': 'pcs_deskew_fault'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.hi_ber_indication',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'hi_ber_indication',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'high',
     'pattern_src': 'hi[-_ ]?ber|high\\s+bit\\s+error',
     'guard': {'re': ['pctoken', 'hi[-_ ]?ber|high\\s+bit\\s+error', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|hi_ber_indication|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'hi_ber_indication'}, 'message': {'var': 'message'}},
              'kind': 'hi_ber_indication'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.link_down_no_light',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'link_down_no_light',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'high',
     'pattern_src': 'no\\s+(light|signal)|loss\\s+of\\s+(light|signal)|LOS\\b|SIGNAL_LOSS',
     'guard': {'re': ['pctoken', 'no\\s+(light|signal)|loss\\s+of\\s+(light|signal)|LOS\\b|SIGNAL_LOSS', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|link_down_no_light|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'link_down_no_light'}, 'message': {'var': 'message'}},
              'kind': 'link_down_no_light'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'syslog.port.link_flap_on_insert',
     'lane': 'port',
     'source': 'syslog',
     'kind': 'link_flap_on_insert',
     'entity_type': 'interface',
     'family': None,
     'vendors': ['generic'],
     'severity': 'warn',
     'pattern_src': 'transceiver[^\\n]{0,80}(insert|remov)[^\\n]{0,80}(insert|remov)|SFP[^\\n]{0,80}flap|optic[^\\n]{0,80}flap',
     'guard': {'re': ['pctoken', 'transceiver[^\\n]{0,80}(insert|remov)[^\\n]{0,80}(insert|remov)|SFP[^\\n]{0,80}flap|optic[^\\n]{0,80}flap', 'i']},
     'extract': {'port': {'alt': [{'ev': ['interface', 'if_name', 'ifname', 'port']},
                                  {'re': [['msg', '\\b((?:Ethernet|Eth|Et|Gi|Te|Fo|Hu|xe-|ge-|et-)[\\w./:-]+)', 1, '']]}]},
                 'message': {'var': 'msg', 'slice': 240}},
     'emit': {'metric': 'port_event',
              'modality': 'device_telemetry',
              'entity': {'when': {'truthy': '$port'}, 'type': 'interface', 'id': '{host}:{port}', 'else': {'type': 'device', 'id': '{host}'}},
              'native_id': '{host}|portevt|link_flap_on_insert|{port|-}|{ts_ms}',
              'tokens': [{'t': '{host}'}],
              'attrs': {'interface': {'var': 'port'}, 'port_event': {'const': 'link_flap_on_insert'}, 'message': {'var': 'message'}},
              'kind': 'link_flap_on_insert'},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.link.state_change',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'link_state_change',
     'entity_type': 'interface',
     'family': 'link_state_change',
     'vendors': ['standard'],
     'guard': {'any': [{'equals_any': ['oid', ['1.3.6.1.6.3.1.1.5.3', '1.3.6.1.6.3.1.1.5.4']]}, {'equals_any': ['name', ['linkDown', 'linkUp']]}]},
     'extract': {'state': {'case': [{'when': {'any': [{'eq': ['oid', '1.3.6.1.6.3.1.1.5.3']}, {'eq': ['name', 'linkDown']}]}, 'value': 'down'},
                                    {'when': {'always': True}, 'value': 'up'}]},
                 'iface': {'alt': [{'vb': ['1.3.6.1.2.1.31.1.1.1.1']},
                                   {'vb': ['1.3.6.1.2.1.2.2.1.2']},
                                   {'vb': ['1.3.6.1.2.1.2.2.1.1']},
                                   {'vbname': ['ifname', 'ifdescr', 'interfacename', 'intfname']},
                                   {'const': 'unknown'}]}},
     'emit': {'kind': 'link_state_change',
              'metric': 'link_state',
              'modality': 'control_plane',
              'entity': {'type': 'interface', 'id': '{device}:{iface}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{device}|trap_link|{iface}|{state}|{ts_ms}',
              'tokens': [{'t': '{device}'}],
              'attrs': {'interface': {'var': 'iface'}, 'state': {'var': 'state'}, 'trap_oid': {'var': 'oid'}, 'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.device.restart',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'device_restart',
     'entity_type': 'device',
     'family': None,
     'vendors': ['standard'],
     'severity': 'high',
     'guard': {'any': [{'equals_any': ['oid', ['1.3.6.1.6.3.1.1.5.1', '1.3.6.1.6.3.1.1.5.2']]}, {'equals_any': ['name', ['coldStart', 'warmStart']]}]},
     'extract': {'restart': {'case': [{'when': {'any': [{'eq': ['oid', '1.3.6.1.6.3.1.1.5.1']}, {'eq': ['name', 'coldStart']}]}, 'value': 'cold'},
                                      {'when': {'always': True}, 'value': 'warm'}]}},
     'emit': {'kind': 'device_restart',
              'metric': 'device_restart',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{device}'},
              'native_id': '{device}|trap_restart|{restart}|{ts_ms}',
              'tokens': [{'t': '{device}'}],
              'attrs': {'restart': {'var': 'restart'}, 'trap_oid': {'var': 'oid'}, 'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.bgp.adjacency_change',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'bgp_adjacency_change',
     'entity_type': 'device',
     'family': 'bgp_adjacency_change',
     'vendors': ['standard'],
     'guard': {'equals_any': ['oid', ['1.3.6.1.2.1.15.7.2', '1.3.6.1.2.1.15.7.1', '1.3.6.1.2.1.0.2', '1.3.6.1.2.1.0.1']]},
     'extract': {'peer': {'vb': ['1.3.6.1.2.1.15.3.1.7']},
                 'established': {'bool': {'equals_any': ['oid', ['1.3.6.1.2.1.15.7.1', '1.3.6.1.2.1.0.1']]}},
                 'state': {'case': [{'when': {'var_true': 'established'}, 'value': 'up'}, {'when': {'always': True}, 'value': 'down'}]}},
     'emit': {'kind': 'bgp_adjacency_change',
              'metric': 'bgp_adjacency',
              'modality': 'control_plane',
              'entity': {'when': {'truthy': '$peer'}, 'type': 'device', 'id': '{device}:{peer}', 'else': {'type': 'device', 'id': '{device}'}},
              'severity': {'case': [{'when': {'var_true': 'established'}, 'value': 'warn'}], 'default': 'high'},
              'native_id': '{device}|trap_bgp|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{device}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'}, 'state': {'var': 'state'}, 'trap_oid': {'var': 'oid'}, 'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.bgp.adjacency_change.event_type',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'bgp_adjacency_change',
     'entity_type': 'device',
     'family': 'bgp_adjacency_change',
     'vendors': ['any'],
     'guard': {'all': [{'contains': ['etype', 'bgp']},
                       {'any': [{'contains': ['etype', 'backward']},
                                {'contains': ['etype', 'transition']},
                                {'contains': ['etype', 'established']},
                                {'contains': ['etype', 'neighbor']},
                                {'contains': ['etype', 'fsm']},
                                {'contains': ['etype', 'state']}]}]},
     'extract': {'established': {'bool': {'contains': ['etype', 'establish']}},
                 'state': {'case': [{'when': {'var_true': 'established'}, 'value': 'up'}, {'when': {'always': True}, 'value': 'down'}]},
                 'peer': {'alt': [{'vb': ['1.3.6.1.2.1.15.3.1.7']}, {'vbname': ['peerremoteaddr', 'peeraddr', 'remoteaddr', 'peer']}]}},
     'emit': {'kind': 'bgp_adjacency_change',
              'metric': 'bgp_adjacency',
              'modality': 'control_plane',
              'entity': {'when': {'truthy': '$peer'}, 'type': 'device', 'id': '{device}:{peer}', 'else': {'type': 'device', 'id': '{device}'}},
              'severity': {'case': [{'when': {'var_true': 'established'}, 'value': 'warn'}], 'default': 'high'},
              'native_id': '{device}|trap_bgp|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{device}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'},
                        'state': {'var': 'state'},
                        'trap_oid': {'var': 'oid'},
                        'event_type': {'var': 'etype'},
                        'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.link.state_change.event_type',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'link_state_change',
     'entity_type': 'interface',
     'family': 'link_state_change',
     'vendors': ['any'],
     'guard': {'all': [{'contains': ['etype', 'link']}, {'any': [{'contains': ['etype', 'down']}, {'contains': ['etype', 'up']}]}]},
     'extract': {'state': {'case': [{'when': {'contains': ['etype', 'down']}, 'value': 'down'}, {'when': {'always': True}, 'value': 'up'}]},
                 'iface': {'alt': [{'vb': ['1.3.6.1.2.1.31.1.1.1.1']},
                                   {'vb': ['1.3.6.1.2.1.2.2.1.2']},
                                   {'vb': ['1.3.6.1.2.1.2.2.1.1']},
                                   {'vbname': ['ifname', 'ifdescr', 'interfacename', 'intfname']},
                                   {'const': 'unknown'}]}},
     'emit': {'kind': 'link_state_change',
              'metric': 'link_state',
              'modality': 'control_plane',
              'entity': {'type': 'interface', 'id': '{device}:{iface}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{device}|trap_link|{iface}|{state}|{ts_ms}',
              'tokens': [{'t': '{device}'}],
              'attrs': {'interface': {'var': 'iface'},
                        'state': {'var': 'state'},
                        'trap_oid': {'var': 'oid'},
                        'event_type': {'var': 'etype'},
                        'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.device.restart.event_type',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'device_restart',
     'entity_type': 'device',
     'family': None,
     'vendors': ['any'],
     'severity': 'high',
     'guard': {'all': [{'contains': ['etype', 'start']}, {'any': [{'contains': ['etype', 'cold']}, {'contains': ['etype', 'warm']}]}]},
     'extract': {'restart': {'case': [{'when': {'contains': ['etype', 'cold']}, 'value': 'cold'}, {'when': {'always': True}, 'value': 'warm'}]}},
     'emit': {'kind': 'device_restart',
              'metric': 'device_restart',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{device}'},
              'native_id': '{device}|trap_restart|{restart}|{ts_ms}',
              'tokens': [{'t': '{device}'}],
              'attrs': {'restart': {'var': 'restart'}, 'trap_oid': {'var': 'oid'}, 'event_type': {'var': 'etype'}, 'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.ospf.adjacency_change',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'ospf_adjacency_change',
     'entity_type': 'device',
     'family': None,
     'fidelity_status': 'doc_claimed',
     'vendors': ['standard', 'cisco', 'arista', 'juniper'],
     'guard': {'any': [{'equals_any': ['oid', ['1.3.6.1.2.1.14.16.2.2', '1.3.6.1.2.1.14.16.2.3']]},
                       {'equals_any': ['name', ['ospfNbrStateChange', 'ospfVirtNbrStateChange']]},
                       {'all': [{'contains': ['etype', 'ospf']}, {'contains': ['etype', 'nbr']}, {'contains': ['etype', 'state']}]}]},
     'extract': {'peer': {'alt': [{'vb': ['1.3.6.1.2.1.14.10.1.1']},
                                  {'vb': ['1.3.6.1.2.1.14.10.1.3']},
                                  {'vbname': ['nbripaddr', 'nbrrtrid', 'nbraddress']}]},
                 'nbr_state': {'alt': [{'vb': ['1.3.6.1.2.1.14.10.1.6']}, {'vbname': ['nbrstate']}], 'lower': True},
                 'state': {'case': [{'when': {'re': ['$nbr_state', '\\b(?:down|attempt|init|exstart|exchange|loading|twoway|1|2|3|4|5|6|7)\\b', 'i']},
                                     'value': 'down'},
                                    {'when': {'re': ['$nbr_state', '\\b(?:full|8)\\b', 'i']}, 'value': 'up'},
                                    {'when': {'always': True}, 'value': 'unknown'}]}},
     'emit': {'kind': 'ospf_adjacency_change',
              'metric': 'ospf_adjacency',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{device}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{device}|trap_ospf_adj|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{device}'}, {'t': '{peer}'}],
              'attrs': {'peer': {'var': 'peer'},
                        'state': {'var': 'state'},
                        'trap_oid': {'var': 'oid'},
                        'event_type': {'var': 'etype'},
                        'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.isis.adjacency_change',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'isis_adjacency_change',
     'entity_type': 'device',
     'family': None,
     'fidelity_status': 'doc_claimed',
     'vendors': ['standard', 'cisco', 'juniper', 'nokia'],
     'guard': {'any': [{'eq': ['oid', '1.3.6.1.2.1.138.0.17']},
                       {'eq': ['name', 'isisAdjacencyChange']},
                       {'all': [{'contains': ['etype', 'isis']}, {'contains': ['etype', 'adjacency_change']}]}]},
     'extract': {'peer': {'alt': [{'vb': ['1.3.6.1.2.1.138.1.6.1.1.6']}, {'vbname': ['neighsysid', 'adjneighsysid', 'systemid']}]},
                 'peer_tok': {'re': [['$peer', '\\b([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\.[0-9a-fA-F]{4})\\b', 1, '']]},
                 'adj_state': {'alt': [{'vb': ['1.3.6.1.2.1.138.1.10.1.12']}, {'vbname': ['adjstate']}], 'lower': True},
                 'state': {'case': [{'when': {'re': ['$adj_state', '\\b(?:down|init\\w*|failed|1|2|4)\\b', 'i']}, 'value': 'down'},
                                    {'when': {'re': ['$adj_state', '\\b(?:up|3)\\b', 'i']}, 'value': 'up'},
                                    {'when': {'always': True}, 'value': 'unknown'}]}},
     'emit': {'kind': 'isis_adjacency_change',
              'metric': 'isis_adjacency',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{device}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{device}|trap_isis_adj|{peer|?}|{state}|{ts_ms}',
              'tokens': [{'t': '{device}'}, {'t': '{peer_tok}'}],
              'attrs': {'peer': {'var': 'peer'},
                        'state': {'var': 'state'},
                        'trap_oid': {'var': 'oid'},
                        'event_type': {'var': 'etype'},
                        'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.stp.topology_change',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'stp_topology_change',
     'entity_type': 'device',
     'family': None,
     'fidelity_status': 'doc_claimed',
     'vendors': ['standard', 'cisco', 'arista'],
     'guard': {'any': [{'equals_any': ['oid', ['1.3.6.1.2.1.17.0.1', '1.3.6.1.2.1.17.0.2']]},
                       {'equals_any': ['name', ['newRoot', 'topologyChange']]},
                       {'all': [{'contains': ['etype', 'topology']}, {'contains': ['etype', 'change']}]}]},
     'extract': {'subtype': {'case': [{'when': {'any': [{'eq': ['oid', '1.3.6.1.2.1.17.0.1']},
                                                        {'eq': ['name', 'newRoot']},
                                                        {'contains': ['etype', 'new_root']}]},
                                       'value': 'new_root'},
                                      {'when': {'always': True}, 'value': 'topology_change'}]},
                 'state': {'const': 'unknown'}},
     'emit': {'kind': 'stp_topology_change',
              'metric': 'stp_state',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{device}'},
              'severity': {'by_state': {'down': 'high'}, 'default': 'warn'},
              'native_id': '{device}|trap_stp_tcn|{subtype}|{state}|{ts_ms}',
              'tokens': [{'t': '{device}'}],
              'attrs': {'subtype': {'var': 'subtype'},
                        'state': {'var': 'state'},
                        'trap_oid': {'var': 'oid'},
                        'event_type': {'var': 'etype'},
                        'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.fhrp.state_change',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'fhrp_state_change',
     'entity_type': 'device',
     'family': None,
     'fidelity_status': 'doc_claimed',
     'vendors': ['standard', 'cisco', 'arista', 'juniper'],
     'guard': {'all': [{'any': [{'contains': ['etype', 'hsrp']}, {'contains': ['etype', 'vrrp']}]},
                       {'any': [{'contains': ['etype', 'state']},
                                {'contains': ['etype', 'master']},
                                {'contains': ['etype', 'switchover']},
                                {'contains': ['etype', 'standby']}]}]},
     'extract': {'proto': {'case': [{'when': {'contains': ['etype', 'vrrp']}, 'value': 'vrrp'}, {'when': {'always': True}, 'value': 'hsrp'}]},
                 'ifname': {'alt': [{'vb': ['1.3.6.1.2.1.31.1.1.1.1']},
                                    {'vb': ['1.3.6.1.2.1.2.2.1.2']},
                                    {'vb': ['1.3.6.1.2.1.2.2.1.1']},
                                    {'vbname': ['ifname', 'ifdescr', 'interfacename', 'intfname']},
                                    {'const': 'unknown'}]},
                 'group': {'vbname': ['grpnumber', 'groupnumber', 'vrid', 'grpindex', 'group']},
                 'role_raw': {'vbname': ['standbystate', 'grpstate', 'newstate', 'state', 'role'], 'lower': True},
                 'role_word': {'re': [['$role_raw', '([a-z]+)', 1, '']]},
                 'role': {'case': [{'when': {'truthy': '$role_word'}, 'value': '{role_word}'},
                                   {'when': {'contains': ['etype', 'master']}, 'value': 'master'},
                                   {'when': {'contains': ['etype', 'switchover']}, 'value': 'active'},
                                   {'when': {'always': True}, 'value': 'unknown'}]},
                 'takeover': {'bool': {'equals_any': ['$role', ['active', 'master']]}}},
     'emit': {'kind': 'fhrp_state_change',
              'metric': 'fhrp_state',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{device}'},
              'severity': {'case': [{'when': {'var_true': 'takeover'}, 'value': 'high'}], 'default': 'warn'},
              'native_id': '{device}|trap_fhrp|{proto}|{ifname}|grp{group|?}|{role|?}|{ts_ms}',
              'tokens': [{'t': '{device}'}, {'t': '{ifname}', 'local': True}, {'t': 'grp{group}', 'local': True}],
              'tokens_fallback': 'host',
              'attrs': {'proto': {'var': 'proto'},
                        'group': {'var': 'group'},
                        'interface': {'var': 'ifname'},
                        'state': {'var': 'role'},
                        'trap_oid': {'var': 'oid'},
                        'event_type': {'var': 'etype'},
                        'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.config.change',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'device_config_change',
     'entity_type': 'device',
     'family': None,
     'fidelity_status': 'doc_claimed',
     'vendors': ['standard', 'cisco', 'juniper', 'nokia'],
     'severity': 'info',
     'guard': {'any': [{'equals_any': ['oid',
                                       ['1.3.6.1.4.1.9.9.43.2.0.1', '1.3.6.1.4.1.9.9.43.2.0.2', '1.3.6.1.4.1.2636.4.5.0.1', '1.3.6.1.2.1.47.2.0.1']]},
                       {'equals_any': ['name', ['ciscoConfigManEvent', 'ccmCLIRunningConfigChanged', 'jnxCmCfgChange', 'entConfigChange']]},
                       {'all': [{'any': [{'contains': ['etype', 'config']}, {'contains': ['etype', 'cfg']}]},
                                {'any': [{'contains': ['etype', 'change']},
                                         {'contains': ['etype', 'commit']},
                                         {'contains': ['etype', 'modif']},
                                         {'contains': ['etype', 'create']},
                                         {'contains': ['etype', 'delete']}]}]}]},
     'extract': {'user': {'alt': [{'vb': ['1.3.6.1.4.1.9.9.43.1.1.6.1.8', '1.3.6.1.4.1.9.9.43.1.1.6.1.14', '1.3.6.1.4.1.2636.3.18.1.7.1.5']},
                                  {'vbname': ['terminaluser', 'rcpuser', 'cfgchgeventuser', 'chguser']}]},
                 'source_raw': {'alt': [{'vb': ['1.3.6.1.4.1.9.9.43.1.1.6.1.3', '1.3.6.1.4.1.9.9.43.1.1.6.1.4', '1.3.6.1.4.1.2636.3.18.1.7.1.4']},
                                        {'vbname': ['commandsource', 'configsource', 'cfgchgeventsource']}],
                                'lower': True},
                 'source_word': {'re': [['$source_raw', '([a-z]+)', 1, '']]},
                 'source': {'case': [{'when': {'truthy': '$source_word'}, 'value': '{source_word}'},
                                     {'when': {'always': True}, 'value': '{source_raw}'}]},
                 'dest_raw': {'alt': [{'vb': ['1.3.6.1.4.1.9.9.43.1.1.6.1.5']}, {'vbname': ['configdestination', 'cfgdestination']}], 'lower': True},
                 'dest_word': {'re': [['$dest_raw', '([a-z]+)', 1, '']]},
                 'dest': {'case': [{'when': {'truthy': '$dest_word'}, 'value': '{dest_word}'}, {'when': {'always': True}, 'value': '{dest_raw}'}]},
                 'state': {'const': 'changed'}},
     'emit': {'kind': 'device_config_change',
              'metric': 'device_config_change',
              'modality': 'control_plane',
              'entity': {'type': 'device', 'id': '{device}'},
              'native_id': '{device}|trap_config_change|{source|?}|{user|?}|{dest|?}|{ts_ms}',
              'tokens': [{'t': '{device}'}],
              'attrs': {'user': {'var': 'user'},
                        'source': {'var': 'source'},
                        'destination': {'var': 'dest'},
                        'state': {'var': 'state'},
                        'trap_oid': {'var': 'oid'},
                        'event_type': {'var': 'etype'},
                        'authenticated': {'var': 'authed'}}},
     'markers': [],
     'generic': False,
     'shadow': False},
    {'rule_id': 'trap.generic.device_alarm',
     'lane': 'trap',
     'source': 'trap',
     'kind': 'device_alarm',
     'entity_type': 'device_or_interface',
     'family': None,
     'vendors': ['any'],
     'generic': True,
     'guard': {'severity_floor': 'trap'},
     'extract': {'iface': {'alt': [{'vb': ['1.3.6.1.2.1.31.1.1.1.1']},
                                   {'vb': ['1.3.6.1.2.1.2.2.1.2']},
                                   {'vb': ['1.3.6.1.2.1.2.2.1.1']},
                                   {'vbname': ['ifname', 'ifdescr', 'interfacename', 'intfname']},
                                   {'const': 'unknown'}]},
                 'sev_num': {'severity_num': True},
                 'category': {'ev': ['category']},
                 'content': {'lane': 'trap_content'},
                 'interface_attr': {'case': [{'when': {'ne': ['$iface', 'unknown']}, 'value': '{iface}'}, {'when': {'always': True}, 'value': ''}]}},
     'emit': {'kind': 'device_alarm',
              'metric': 'device_alarm',
              'modality': 'control_plane',
              'entity': {'when': {'all': [{'truthy': '$iface'}, {'ne': ['$iface', 'unknown']}]},
                         'type': 'interface',
                         'id': '{device}:{iface}',
                         'else': {'type': 'device', 'id': '{device}'}},
              'severity': {'from_severity_num': True},
              'native_id': '{device}|alarm|{oid|?}|{ts_ms}',
              'content_tag': 'content',
              'tokens': [{'t': '{device}'}],
              'attrs': {'trap_oid': {'var': 'oid'},
                        'trap_name': {'var': 'name'},
                        'event_type': {'var': 'etype'},
                        'category': {'var': 'category'},
                        'severity': {'var': 'sev_num'},
                        'authenticated': {'var': 'authed'},
                        'interface': {'var': 'interface_attr'}}},
     'markers': [],
     'shadow': False},
)

RULES: tuple[Rule, ...] = tuple(compile_rule(row) for row in _ROWS)

#: The hash the BAKE computed. `RULES_HASH` recomputes it at import; they must
#: agree, which is what makes a hand-edit of this file impossible to hide.
BAKED_RULES_HASH = 'a0be9de50a0657bc8a8a029305b23909cf5a09d72179f294b96cec889426eade'
RULES_HASH: str = rules_hash(RULES)
