"""Rank-7 shared-token HUB CAP — Stage-2 Lever 1 quality regression (#168).

The correlation engine used to mesh a shared-token group ALL-PAIRS: a token
shared by N nodes produced O(N²) rank-7 candidate pairs (code-measured: "48
groups of 1,000 nodes → ~25.1M pairs"). A concentrated storm — one giant
shared-token group (a common interface name, a shared label) — exploded there.

`CORR_TOKEN_HUB_CAP` (default 64) caps the ONE rank-7 bare-shared-token
dimension: a token shared by more than the cap is a non-specific HUB, not a
relationship, so its all-pairs mesh is dropped from candidate generation and it
no longer grounds an edge. This is a DELIBERATE, owner-approved #168-class
correlation-QUALITY change (fewer spurious hub-welding edges), NOT a silent
optimization.

The whole correctness argument is SCOPE: the cap touches ONLY the token
dimension. Every rank-1–6 relationship (identity / seam / adjacency / path)
lives in a SEPARATE index dimension and is untouched — a pair that shares a hub
token AND a real relationship is still generated by that dimension and still
grounds at its real rank, byte-for-byte identical to before the cap. These tests
pin exactly that: hub meshes vanish, non-hub meshes and every rank-1–6 edge are
unchanged.
"""

from __future__ import annotations

import engine
from engine import (
    CORR_TOKEN_HUB_CAP,
    NO_ADJACENCY,
    EngineConfig,
    SeamView,
    TopologyAdjacency,
    _candidate_pairs,
    _CandidateIndex,
    _emit_candidates,
    build_edges,
    build_nodes,
    resolve_grounding,
)
from signals import EntityType
from test_engine_complexity import _hub_tokens, brute_force_edges, sig

CAP = CORR_TOKEN_HUB_CAP


def _views(nodes):
    toks = [nd.tokens() for nd in nodes]
    refs = [nd.identity_refs() for nd in nodes]
    devs = [nd.device_part() for nd in nodes]
    return toks, refs, devs


# ── 1. a hub token emits NO rank-7 mesh; a non-hub token keeps its FULL mesh ──


def test_hub_token_drops_mesh_nonhub_token_keeps_it():
    """One window, two token groups. The hub group (> cap unrelated devices)
    contributes ZERO candidate pairs and ZERO edges; the small group (≤ cap)
    keeps every pair and every rank-7 edge, unchanged."""
    sigs = []
    # HUB: cap+5 unrelated devices sharing one bare token, nothing else in common.
    for k in range(CAP + 5):
        sigs.append(sig("metric_anomaly", EntityType.DEVICE, f"hubdev-{k:04d}",
                        offset_s=float(k % 200), tokens=("shared-hub",)))
    # NON-HUB: 5 unrelated devices sharing a different bare token.
    for k in range(5):
        sigs.append(sig("metric_anomaly", EntityType.DEVICE, f"smalldev-{k}",
                        offset_s=float(k), tokens=("shared-small",)))
    nodes = build_nodes(tuple(sigs))
    toks, refs, devs = _views(nodes)

    hub = _hub_tokens(nodes)
    assert hub == frozenset({"shared-hub"}), "only the >cap token is a hub"

    cand = _candidate_pairs(len(nodes), toks, refs, [], devs, NO_ADJACENCY, None, None)
    # The ONLY candidates are the small group's full mesh — the hub contributes none.
    assert len(cand) == 5 * 4 // 2, "hub mesh dropped, small mesh intact"

    cfg = EngineConfig()
    edges, _ = build_edges(nodes, (), cfg)
    small_keys = {nd.key for nd in nodes if "smalldev" in nd.key}
    hub_keys = {nd.key for nd in nodes if "hubdev" in nd.key}
    # every admitted edge is a rank-7 shared:shared-small edge inside the small group
    assert edges, "the non-hub token must still form edges"
    for e in edges:
        assert e.grounding.ref == "shared:shared-small"
        assert e.grounding.relation.rank == 7
        assert e.from_node in small_keys and e.to_node in small_keys
    # not a single edge touches the hub group
    assert not any(e.from_node in hub_keys or e.to_node in hub_keys for e in edges)

    # and the engine still matches the (capped) brute-force reference exactly
    assert build_edges(nodes, (), cfg) == brute_force_edges(nodes, (), cfg)


# ── 2. a pair sharing a HUB token AND a rank-1–6 relationship is UNTOUCHED ─────
#
# The critical "we only dropped noise" proof: the real relationship still grounds
# at its real rank, byte-for-byte identical to grounding the SAME pair with the
# cap disabled (empty hub set == pre-#168 behavior).


def _grounds_identically_with_and_without_cap(a, b, seams, adjacency, hub):
    """resolve_grounding on (a,b) is byte-identical whether or not the hub set is
    applied — i.e. the cap changed nothing for this pair (its grounding is a real
    rank-1–6 relation, evaluated before the rank-7 token branch)."""
    capped = resolve_grounding(a, b, seams, adjacency, None, hub)
    uncapped = resolve_grounding(a, b, seams, adjacency, None, frozenset())
    assert capped == uncapped
    return capped


def test_shared_identity_survives_hub_token_rank1():
    """A device and its interface both carry a hub token, but they also share the
    device IDENTITY ref (rank 1). The edge survives and grounds to rank-1
    containment, identical to before the cap."""
    sigs = [
        sig("device_cpu_high", EntityType.DEVICE, "coreX", tokens=("shared-hub",)),
        sig("if_errors", EntityType.INTERFACE, "coreX:Et0", offset_s=2,
            tokens=("shared-hub",)),
    ]
    # make "shared-hub" a genuine hub with cap+ filler devices carrying it
    for k in range(CAP + 1):
        sigs.append(sig("metric_anomaly", EntityType.DEVICE, f"filler-{k:04d}",
                        offset_s=float(k % 100), tokens=("shared-hub",)))
    nodes = build_nodes(tuple(sigs))
    hub = _hub_tokens(nodes)
    assert "shared-hub" in hub

    a = next(nd for nd in nodes if nd.entity_id == "coreX")
    b = next(nd for nd in nodes if nd.entity_id == "coreX:Et0")
    g = _grounds_identically_with_and_without_cap(a, b, (), NO_ADJACENCY, hub)
    assert g is not None and g.ref == "shared:coreX", "rank-1 identity, not the hub token"
    assert g.relation.rank == 1

    # end-to-end: the containment edge is admitted; the fillers form no edges.
    cfg = EngineConfig()
    edges, _ = build_edges(nodes, (), cfg)
    keys = {frozenset((e.from_node, e.to_node)) for e in edges}
    assert frozenset((a.key, b.key)) in keys, "the rank-1 containment edge must survive"
    for e in edges:
        assert "filler-" not in e.from_node and "filler-" not in e.to_node
    assert build_edges(nodes, (), cfg) == brute_force_edges(nodes, (), cfg)


def test_shared_seam_survives_hub_token_rank2():
    """Two nodes on the same seam, both also carrying a hub token, still ground to
    the rank-2 seam — the token cap never touches the seam dimension."""
    seams = (SeamView(
        seam_id="dallas-dx-equinix", tenant_id="t1", seam_type="DX",
        endpoints=(("on_prem", "dallas-edge"), ("provider_edge", "equinix-pop")),
    ),)
    sigs = [
        sig("if_util_high", EntityType.INTERFACE, "dallas-edge:Gi0/1",
            tokens=("shared-hub",)),
        sig("probe_loss", EntityType.SEGMENT, "dallas-edge->equinix-pop", offset_s=20,
            observer="probe1", tokens=("shared-hub",)),
    ]
    for k in range(CAP + 1):
        sigs.append(sig("metric_anomaly", EntityType.DEVICE, f"filler-{k:04d}",
                        offset_s=float(k % 100), tokens=("shared-hub",)))
    nodes = build_nodes(tuple(sigs))
    hub = _hub_tokens(nodes)
    assert "shared-hub" in hub
    a = next(nd for nd in nodes if nd.entity_id == "dallas-edge:Gi0/1")
    b = next(nd for nd in nodes if nd.entity_id == "dallas-edge->equinix-pop")
    g = _grounds_identically_with_and_without_cap(a, b, seams, NO_ADJACENCY, hub)
    assert g is not None and g.kind == "seam" and g.relation.rank == 2
    cfg = EngineConfig()
    assert build_edges(nodes, seams, cfg) == brute_force_edges(nodes, seams, cfg)


def test_shared_adjacency_survives_hub_token_rank3():
    """Two different devices joined by an inventoried L2/L3 link, both carrying a
    hub token, still ground to rank-3 adjacency — the token cap never touches the
    adjacency dimension."""
    adjacency = TopologyAdjacency.from_links([{"a": "leafA", "b": "leafB"}])
    sigs = [
        sig("device_cpu_high", EntityType.DEVICE, "leafA", tokens=("shared-hub",)),
        sig("device_mem_high", EntityType.DEVICE, "leafB", offset_s=5,
            tokens=("shared-hub",)),
    ]
    for k in range(CAP + 1):
        sigs.append(sig("metric_anomaly", EntityType.DEVICE, f"filler-{k:04d}",
                        offset_s=float(k % 100), tokens=("shared-hub",)))
    nodes = build_nodes(tuple(sigs))
    hub = _hub_tokens(nodes)
    assert "shared-hub" in hub
    a = next(nd for nd in nodes if nd.entity_id == "leafA")
    b = next(nd for nd in nodes if nd.entity_id == "leafB")
    g = _grounds_identically_with_and_without_cap(a, b, (), adjacency, hub)
    assert g is not None and g.ref.startswith("adj:") and g.relation.rank == 3
    cfg = EngineConfig()
    assert build_edges(nodes, (), cfg, adjacency=adjacency) \
        == brute_force_edges(nodes, (), cfg, adjacency=adjacency)


# ── 3. a pair also sharing a NON-HUB token still grounds to it (min over non-hubs)


def test_pair_sharing_hub_and_nonhub_token_grounds_to_nonhub():
    """When a pair shares a hub token AND a non-hub token, the hub is ignored and
    the pair grounds to the (real) non-hub token — the mesh for the non-hub group
    is preserved."""
    sigs = [
        sig("metric_anomaly", EntityType.DEVICE, "pairA",
            tokens=("aaa-hub", "zzz-real")),
        sig("metric_anomaly", EntityType.DEVICE, "pairB", offset_s=3,
            tokens=("aaa-hub", "zzz-real")),
    ]
    # "aaa-hub" becomes a hub (and is lexicographically < "zzz-real", so pre-cap it
    # would have been the grounding token); "zzz-real" stays a 2-node non-hub group.
    for k in range(CAP + 1):
        sigs.append(sig("metric_anomaly", EntityType.DEVICE, f"filler-{k:04d}",
                        offset_s=float(k % 100), tokens=("aaa-hub",)))
    nodes = build_nodes(tuple(sigs))
    hub = _hub_tokens(nodes)
    assert hub == frozenset({"aaa-hub"})
    a = next(nd for nd in nodes if nd.entity_id == "pairA")
    b = next(nd for nd in nodes if nd.entity_id == "pairB")
    g = resolve_grounding(a, b, (), NO_ADJACENCY, None, hub)
    assert g is not None and g.ref == "shared:zzz-real", \
        "hub token ignored; grounds to the surviving non-hub token"
    assert g.relation.rank == 7
    cfg = EngineConfig()
    assert build_edges(nodes, (), cfg) == brute_force_edges(nodes, (), cfg)


# ── 4. concentrated-storm candidate count: O(N²) → O(N·cap) ────────────────────


def test_concentrated_storm_candidate_count_is_linear_not_quadratic():
    """A window of M disjoint hub groups, each cap*4 nodes: the naive all-pairs
    mesh is M·C(cap*4,2) (quadratic in group size); with the cap every group is a
    hub and generates ZERO candidates. Contrast a control window of the SAME node
    count split into ≤cap-sized groups, which keeps its full (linear-in-N) mesh."""
    group = CAP * 4
    M = 3
    # concentrated: M giant hub groups
    storm = []
    for c in range(M):
        for k in range(group):
            storm.append(sig("metric_anomaly", EntityType.DEVICE,
                             f"s{c}-m{k:05d}", offset_s=float(k % 300),
                             tokens=(f"hub-{c}",)))
    nodes = build_nodes(tuple(storm))
    toks, refs, devs = _views(nodes)
    cand = _candidate_pairs(len(nodes), toks, refs, [], devs, NO_ADJACENCY, None, None)
    assert cand == set(), "every hub group drops → zero candidates"

    # control: same N, but as groups of exactly `cap` (non-hub) → full linear mesh
    n_total = M * group
    per = CAP
    ctrl = []
    for c in range(n_total // per):
        for k in range(per):
            ctrl.append(sig("metric_anomaly", EntityType.DEVICE,
                            f"c{c}-m{k:05d}", offset_s=float(k),
                            tokens=(f"grp-{c}",)))
    cnodes = build_nodes(tuple(ctrl))
    ct, cr, cd = _views(cnodes)
    ccand = _candidate_pairs(len(cnodes), ct, cr, [], cd, NO_ADJACENCY, None, None)
    expected = (n_total // per) * (per * (per - 1) // 2)
    assert len(ccand) == expected, "non-hub groups keep their full mesh"
    # linear in N: total candidates == (N/per)·C(per,2) == N·(per-1)/2, not C(N,2)
    assert len(ccand) == n_total * (per - 1) // 2


# ── 5. GENERAL robustness backstop: the per-cycle candidate ceiling ───────────
#
# The hub cap handles the weak token dimension. The ceiling is the safety net for
# an AUTHORITATIVE dimension (identity/seam/observation/route) that forms a large
# all-pairs group — those are real relationships and are NEVER dropped, so the
# engine bounds the WORK deterministically and reports the offender loudly.


def _identity_hub_nodes(count):
    """`count` interfaces on ONE device: they all share the device IDENTITY ref
    (rank 1), so they form a single authoritative all-pairs group that the hub
    TOKEN cap does not (and must not) touch."""
    sigs = [sig("if_errors", EntityType.INTERFACE, f"bigsw:Et{k}", offset_s=float(k % 50))
            for k in range(count)]
    return build_nodes(tuple(sigs))


def test_authoritative_identity_group_is_never_capped():
    """A device with > cap interfaces keeps its FULL rank-1 containment mesh — the
    #168 token cap must not touch the identity dimension. Proves the audit
    attributes label it 'identity', not 'token'."""
    nodes = _identity_hub_nodes(CORR_TOKEN_HUB_CAP + 30)
    toks = [nd.tokens() for nd in nodes]
    refs = [nd.identity_refs() for nd in nodes]
    devs = [nd.device_part() for nd in nodes]
    idx = _CandidateIndex(len(nodes), toks, refs, [], devs, NO_ADJACENCY, None, None)
    n = len(nodes)
    # The device part 'bigsw' is BOTH a token and an identity ref. As a TOKEN it
    # is a hub (> cap interfaces carry it) and its token-dimension mesh is dropped;
    # but as an IDENTITY ref it is uncapped, so the full containment mesh survives.
    # This is the safety net exactly: capping the token dimension cannot lose a
    # rank-1 pair, because identity_refs carries it in a separate, uncapped bucket.
    assert "bigsw" in idx.hub_tokens, "device part is a hub TOKEN..."
    cand = _emit_candidates(idx)
    assert len(cand) == n * (n - 1) // 2, "...yet the authoritative identity mesh is intact"
    assert idx.largest_dim == "identity"
    assert idx.potential_pairs == n * (n - 1) // 2


def test_candidate_ceiling_bounds_work_deterministically_and_names_offender():
    """When an authoritative group would blow past the ceiling, emission stops in
    fixed group order (bounded work, never a stall) and records the offending
    dimension/group for the orchestration layer to log + metric."""
    n = 400
    nodes = _identity_hub_nodes(n)  # one identity group of 400 → C(400,2)=79_800 pairs
    toks = [nd.tokens() for nd in nodes]
    refs = [nd.identity_refs() for nd in nodes]
    devs = [nd.device_part() for nd in nodes]
    idx = _CandidateIndex(len(nodes), toks, refs, [], devs, NO_ADJACENCY, None, None)
    stats: dict = {}
    low_ceiling = 1000
    cand = _emit_candidates(idx, ceiling=low_ceiling, stats=stats)
    assert len(cand) >= low_ceiling
    assert len(cand) < n * (n - 1) // 2, "work was actually bounded below the full mesh"
    assert stats.get("ceiling_hit") is True
    assert stats.get("ceiling_dimension") == "identity", "the offender is named"
    assert stats.get("ceiling_group_size") == n
    # deterministic: same inputs → same bounded set
    assert _emit_candidates(idx, ceiling=low_ceiling) == cand


def test_ceiling_does_not_fire_at_the_high_default():
    """The default ceiling is high enough that realistic windows never trip it —
    the backstop is a safety net, not a routine limiter."""
    nodes = _identity_hub_nodes(200)
    toks = [nd.tokens() for nd in nodes]
    refs = [nd.identity_refs() for nd in nodes]
    idx = _CandidateIndex(len(nodes), toks, refs, [], [nd.device_part() for nd in nodes], NO_ADJACENCY, None, None)
    stats: dict = {}
    _emit_candidates(idx, ceiling=engine.CORR_CANDIDATE_CEILING, stats=stats)
    assert not stats.get("ceiling_hit")


def test_hub_cap_audit_attributes_are_populated():
    """The index exposes the hub-cap accounting the metrics read (§10)."""
    sigs = [sig("metric_anomaly", EntityType.DEVICE, f"d-{k:04d}",
                offset_s=float(k % 100), tokens=("hubtok",))
            for k in range(CORR_TOKEN_HUB_CAP + 10)]
    nodes = build_nodes(tuple(sigs))
    toks = [nd.tokens() for nd in nodes]
    refs = [nd.identity_refs() for nd in nodes]
    idx = _CandidateIndex(len(nodes), toks, refs, [], [nd.device_part() for nd in nodes], NO_ADJACENCY, None, None)
    m = CORR_TOKEN_HUB_CAP + 10
    assert idx.hub_tokens == frozenset({"hubtok"})
    assert idx.hub_pairs_skipped == m * (m - 1) // 2, "counts the mesh we DIDN'T emit"
    assert _emit_candidates(idx) == set(), "and it really wasn't emitted"
