// enterpriseScaleTopology.ts — a LARGE, deterministically-generated TopologyView
// (~400 nodes) for the Phase 4 Sigma/WebGL overview renderer. This is the dataset
// that proves the point of Phase 4: a graph React Flow should never try to draw
// node-by-node, but a WebGL renderer handles fluidly.
//
// Generated by code (not a literal) so the bundle cost is the small generator,
// not 400 node objects. DETERMINISTIC — a seeded LCG (no Math.random, which is
// also unavailable in workflow scripts) so the same picture renders every time
// and the generator is unit-testable. FLAT canonical contract; every edge carries
// evidence (never draw a link without it).

import type { TopologyView, TopologyNode, TopologyEdge, TopologyGroup, Health } from "../api/topologyTypes";

const SEEN = "2026-06-18T01:20:00Z";
const BORN = "2026-01-01T00:00:00Z";

/** Tiny deterministic PRNG (LCG) — stable across runs/builds. */
function lcg(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s / 0xffffffff;
  };
}

const SITES = ["nyc", "sfo", "lon", "fra", "sin", "syd", "tor", "par", "ams", "tok", "blr", "sao"];

function ev(source: TopologyEdge["evidence"][number]["source"], raw: string, detail: string) {
  return [{ source, confidence: 0.9, detail, observed_at: SEEN, raw_ref: raw, summary: detail }];
}

function dev(
  id: string,
  label: string,
  kind: TopologyNode["kind"],
  role: string,
  site: string,
  health: Health,
): TopologyNode {
  return {
    id,
    label,
    kind,
    role,
    vendor: "arista",
    site,
    group_id: `site-${site}`,
    health,
    confidence: 0.95,
    resolved: true,
    first_seen: BORN,
    last_seen: SEEN,
    change_state: "unchanged",
    metrics: { link_count: 0, alert_count: health === "ok" ? 0 : 1 },
    evidence: ev("lldp", `lldp:${id}:chassis`, `${label} discovered via LLDP`),
  };
}

function link(id: string, a: string, b: string, util: number, status: TopologyEdge["status"]): TopologyEdge {
  return {
    id,
    source: a,
    target: b,
    relationship: "connected_to",
    protocol: "lldp",
    status,
    confidence: 0.95,
    direction: "bi",
    utilization_pct: util,
    first_seen: BORN,
    last_seen: SEEN,
    change_state: "unchanged",
    evidence: ev("lldp", `lldp:${a}<->${b}`, `bidirectional LLDP ${a} ↔ ${b}`),
  };
}

/**
 * Build N sites, each a small Clos pod (2 spines · 4 leaves · 6–9 servers/leaf),
 * plus an inter-site WAN ring across the site spine1s. Deterministic given `seed`.
 */
export function makeEnterpriseScale(siteCount = SITES.length, seed = 42): TopologyView {
  const rnd = lcg(seed);
  const health = (): Health => {
    const r = rnd();
    return r > 0.975 ? "critical" : r > 0.91 ? "warning" : "ok";
  };
  const util = () => Math.round(rnd() * 80) + 5;

  const nodes: TopologyNode[] = [];
  const edges: TopologyEdge[] = [];
  const groups: TopologyGroup[] = [];

  for (let s = 0; s < siteCount; s++) {
    const site = SITES[s % SITES.length] + (s >= SITES.length ? String(s) : "");
    const children: string[] = [];

    const spines: string[] = [];
    for (let sp = 0; sp < 2; sp++) {
      const id = `${site}-spine${sp + 1}`;
      spines.push(id);
      children.push(id);
      nodes.push(dev(id, `${site}-spine${sp + 1}`, "switch", "spine", site, health()));
    }

    for (let lf = 0; lf < 4; lf++) {
      const leafId = `${site}-leaf${lf + 1}`;
      children.push(leafId);
      nodes.push(dev(leafId, `${site}-leaf${lf + 1}`, "switch", "leaf", site, health()));
      // leaf → each spine (ECMP uplinks)
      for (const sp of spines) {
        const u = util();
        edges.push(link(`e-${sp}-${leafId}`, sp, leafId, u, u >= 85 ? "warning" : "up"));
      }
      // leaf → servers
      const nsrv = 6 + Math.floor(rnd() * 4);
      for (let sv = 0; sv < nsrv; sv++) {
        const srvId = `${site}-l${lf + 1}-srv${sv + 1}`;
        children.push(srvId);
        nodes.push(dev(srvId, `${site}-l${lf + 1}-srv${sv + 1}`, "server", "compute", site, health()));
        const u = util();
        edges.push(link(`e-${leafId}-${srvId}`, leafId, srvId, u, "up"));
      }
    }

    groups.push({
      id: `site-${site}`,
      label: site.toUpperCase(),
      group_type: "site",
      children,
      health: "unknown",
      collapsed: false,
    });
  }

  // Inter-site WAN ring across site spine1s (routed adjacency).
  for (let s = 0; s < siteCount; s++) {
    const a = `${SITES[s % SITES.length]}${s >= SITES.length ? String(s) : ""}-spine1`;
    const ns = (s + 1) % siteCount;
    const b = `${SITES[ns % SITES.length]}${ns >= SITES.length ? String(ns) : ""}-spine1`;
    if (a === b) continue;
    const u = util();
    edges.push({
      id: `wan-${a}-${b}`,
      source: a,
      target: b,
      relationship: "routed_adjacency",
      protocol: "bgp_ls",
      status: u >= 85 ? "warning" : "up",
      confidence: 0.9,
      direction: "bi",
      utilization_pct: u,
      first_seen: BORN,
      last_seen: SEEN,
      change_state: "unchanged",
      evidence: ev("bgp_ls", `bgp_ls:${a}<->${b}`, `BGP-LS routed adjacency ${a} ↔ ${b}`),
    });
  }

  return {
    view_id: "view-enterprise-scale-001",
    topology_id: "topo-enterprise-scale",
    mode: "explore",
    scope: { tenant_id: "tenant-acme" },
    generated_at: SEEN,
    time_range: { from: "2026-06-18T00:20:00Z", to: SEEN },
    layout_type: "campus",
    nodes,
    edges,
    groups,
    overlays: ["health"],
    renderer_hints: { preferred: "sigma", max_detail_level: 1 },
  };
}

export const enterpriseScaleTopology: TopologyView = makeEnterpriseScale();
