"""Every compose service caps its container log — no exceptions.

WHY THIS EXISTS (2026-09-03). The lab host hit **94% disk**; OpenSearch's
flood-stage watermark — the point at which it silently flips every index
read-only and ingestion stops — is 95%. Two of the biggest single files on the
box were Docker json logs that nothing bounded:

    opensearch             1.1 GiB
    opensearch-dashboards  200 MiB

The `x-logging: &deflog` anchor (50 MB x 3) had been in docker-compose.yml
since the 2026-06 flow-volume outage, but it was applied to only **8 of the 35
services** — the ones known to be noisy at the time. Every service added since
inherited nothing, and "which containers are noisy" is not a property anybody
re-checks. So the cap is now an INVARIANT over every service in every compose
file, enforced here rather than by review.

THE CONTRACT

  1. docker-compose.yml defines `x-logging: &deflog` with a bounded
     `max-size` AND `max-file` (an unbounded max-file makes max-size a lie).
  2. EVERY service in docker-compose.yml carries `logging: *deflog` — the
     ALIAS, textually. A hand-rolled inline `logging:` block would pass a
     YAML-shape check while quietly drifting from the shared cap, so this test
     reads the raw text: one anchor, one definition, no per-service variants.
  3. Every other compose file that introduces a service of its OWN (one not
     defined in docker-compose.yml) must define its own `x-logging: &deflog`
     with the SAME options — YAML anchors do not cross files — and alias it on
     that service. Services an overlay merely PATCHES inherit the base file's
     `logging` key through compose's merge, so restating it there would be
     noise.
  4. No compose file may introduce a `logging:` key that is not the alias.

NOT COVERED, deliberately: per-host generated overlays
(`compose.offline-images.yml`, `compose.lab.yml`, `docker-compose.override.yml`)
are gitignored and absent from a fresh checkout; they are checked when present
and skipped when not.

OPERATIONAL NOTE — the cap applies on container RECREATE. Docker fixes a
container's log driver and options at create time, so `docker compose up -d`
(which recreates on config change) is what applies this; `docker restart` keeps
the old, unbounded file. The compose comment says so too.

Pure stdlib: the alias is the thing under test and every YAML parser resolves
aliases away, so this parses the files as indented text.

Run:  python3 -m pytest tests/test_compose_logging_bounded.py -v
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DOCKER_DIR = ROOT / "deployment" / "docker"
BASE = DOCKER_DIR / "docker-compose.yml"

ALIAS_LINE = "    logging: *deflog"
ANCHOR_KEY = "x-logging: &deflog"

# Gitignored, generated per host (see .gitignore) — legitimately absent in CI.
PER_HOST = frozenset(
    {
        "compose.offline-images.yml",
        "compose.lab.yml",
        "docker-compose.override.yml",
    }
)

_SERVICE_RE = re.compile(r"^  ([A-Za-z0-9_.-]+):\s*$")
_KEY_RE = re.compile(r"^    ([A-Za-z0-9_.-]+):")


def _compose_files() -> list[Path]:
    """Every TRACKED compose file, so the id set is identical in CI and on a host.

    The per-host overlays are generated by `install.py` from the tracked ones;
    guarding the sources is what keeps the generated copies honest.
    """
    files = sorted(p for p in DOCKER_DIR.glob("*.yml") if p.name not in PER_HOST)
    assert BASE in files, "docker-compose.yml missing"
    return files


def _service_blocks(text: str) -> dict[str, list[str]]:
    """service name -> its block's lines, by indentation (no YAML parser).

    The alias `*deflog` is exactly what must be asserted, and PyYAML resolves
    aliases into their value before any test can see them.
    """
    lines = text.split("\n")
    try:
        start = next(i for i, l in enumerate(lines) if l.rstrip() == "services:")
    except StopIteration:
        return {}
    ends = len(lines)
    for i in range(start + 1, len(lines)):
        if lines[i].strip() and not lines[i].startswith(" "):
            ends = i
            break
    marks: list[tuple[str, int]] = []
    for i in range(start + 1, ends):
        m = _SERVICE_RE.match(lines[i])
        if m:
            marks.append((m.group(1), i))
    blocks: dict[str, list[str]] = {}
    for n, (name, s) in enumerate(marks):
        e = marks[n + 1][1] if n + 1 < len(marks) else ends
        blocks[name] = lines[s:e]
    return blocks


def _anchor_options(text: str) -> dict[str, str]:
    """The `x-logging: &deflog` block's driver/max-size/max-file, or {}."""
    lines = text.split("\n")
    try:
        i = next(j for j, l in enumerate(lines) if l.strip() == ANCHOR_KEY)
    except StopIteration:
        return {}
    out: dict[str, str] = {}
    for l in lines[i + 1 :]:
        if l.strip() and not l.startswith(" "):
            break
        m = re.match(r"^\s+([a-z-]+):\s*(.+?)\s*$", l)
        if m and m.group(2) not in ("", "|", ">"):
            out[m.group(1)] = m.group(2).strip('"')
    return out


BASE_TEXT = BASE.read_text()
BASE_SERVICES = _service_blocks(BASE_TEXT)


def test_base_defines_a_bounded_logging_anchor() -> None:
    opts = _anchor_options(BASE_TEXT)
    assert opts.get("driver") == "json-file", f"x-logging anchor lost its driver: {opts}"
    assert re.fullmatch(r"\d+[kmg]", opts.get("max-size", "")), (
        f"x-logging max-size must be a bounded size, got {opts.get('max-size')!r}"
    )
    # max-file bounds the number of ROTATIONS. Without it (or at a huge value)
    # max-size caps one file while the total grows without limit.
    max_file = opts.get("max-file", "")
    assert max_file.isdigit() and 1 <= int(max_file) <= 5, (
        f"x-logging max-file must be a small bounded count, got {max_file!r}"
    )


def test_every_base_service_uses_the_logging_anchor() -> None:
    assert BASE_SERVICES, "no services parsed out of docker-compose.yml"
    missing = [
        name
        for name, block in BASE_SERVICES.items()
        if ALIAS_LINE not in block
    ]
    assert not missing, (
        "these docker-compose.yml services have no bounded container log "
        f"(add `{ALIAS_LINE.strip()}`): {sorted(missing)}"
    )


@pytest.mark.parametrize("path", _compose_files(), ids=lambda p: p.name)
def test_overlay_only_services_carry_their_own_bounded_logging(path: Path) -> None:
    """A service that exists ONLY in an overlay gets no base `logging` to merge."""
    if path == BASE:
        pytest.skip("covered by test_every_base_service_uses_the_logging_anchor")
    text = path.read_text()
    blocks = _service_blocks(text)
    own = {n: b for n, b in blocks.items() if n not in BASE_SERVICES}
    if not own:
        # Every service here patches a base service and inherits its logging.
        return
    missing = [n for n, b in own.items() if ALIAS_LINE not in b]
    assert not missing, (
        f"{path.name} introduces services that exist nowhere in "
        f"docker-compose.yml, so they inherit no log cap: {sorted(missing)}"
    )
    # The alias has to resolve INSIDE this file, with the same cap.
    opts = _anchor_options(text)
    base_opts = _anchor_options(BASE_TEXT)
    assert opts, (
        f"{path.name} aliases *deflog but never defines `{ANCHOR_KEY}` — YAML "
        "anchors do not cross files, so compose would reject this file"
    )
    assert opts == base_opts, (
        f"{path.name}'s logging anchor drifted from the base cap: "
        f"{opts} != {base_opts}"
    )


@pytest.mark.parametrize("path", _compose_files(), ids=lambda p: p.name)
def test_no_service_hand_rolls_its_own_logging_block(path: Path) -> None:
    """One cap, one definition — an inline block is how the cap silently drifts."""
    for name, block in _service_blocks(path.read_text()).items():
        for line in block:
            if _KEY_RE.match(line) and line.strip().startswith("logging:"):
                assert line.rstrip() == ALIAS_LINE, (
                    f"{path.name}:{name} sets logging to something other than "
                    f"the shared anchor: {line.rstrip()!r}"
                )
