"""Unit tests for `scripts/sbom.py` — the committed CycloneDX bill of materials.

The SBOM is a RELEASE ARTIFACT: it is what a customer or an auditor is handed
when they ask what is inside the appliance, and it is the inventory the Trivy
scan is run against. A wrong SBOM is worse than no SBOM, because it is believed.

What is asserted, and why it matters:

  determinism        The document is COMMITTED. If it churned on every run, the
                     diff would be noise, nobody would read it, and a real
                     component change would slip through unnoticed. Two renders
                     of the same tree must be byte-identical, and the ordering
                     of the input must not reach the output.
  direct vs indirect `correlix:direct` is how the CLAUDE.md §6 allowlist stays
                     legible in the SBOM. Misreading `// indirect` would make an
                     unreviewed transitive module look like an allowlisted one.
  hash fidelity      npm `integrity` is base64 and pip `--hash=` is hex; both
                     become CycloneDX hex. Getting the decode wrong yields a
                     document full of confident, wrong digests.
  image ref parsing  `registry:5000/team/app:tag@sha256:...` — the port colon and
                     the tag colon are the same character. A parser that splits
                     on the wrong one silently mislabels the registry, and the
                     digest-pinned audit built on top of it becomes fiction.
  --check            The CI gate. It must fail on a stale OR missing file, never
                     rewrite anything while checking, and — the subtle half —
                     must compare the COMPONENT SET, not the metadata. A gate
                     that failed merely because the file was regenerated at a
                     different commit would be red constantly, and a gate that
                     is constantly red is a gate that gets ignored.
  stable provenance  The document is keyed to the last commit that touched a
                     DEPENDENCY INPUT, and image origins name `file(service)`
                     rather than `file:line`. Both exist because the first draft
                     churned on every unrelated commit and on every compose edit
                     that shifted a line number.
  the committed tree The last test asserts `docs/sbom/` matches the current
                     dependencies. It is DESIGNED to fail when you bump a
                     dependency without regenerating — that failure is the
                     feature, and the fix is `python3 scripts/sbom.py`.

Run:  python3 -m pytest tests/test_sbom.py -q
"""

from __future__ import annotations

import base64
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "scripts" / "sbom.py"


def _load():
    spec = importlib.util.spec_from_file_location("correlix_sbom", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["correlix_sbom"] = module
    spec.loader.exec_module(module)
    return module


sbom = _load()


# --------------------------------------------------------------------------- #
# a minimal but realistic fake repo
# --------------------------------------------------------------------------- #

GO_MOD = """module netops/backend

go 1.26.0

toolchain go1.26.8

require (
\tgithub.com/jackc/pgx/v5 v5.9.2
\tgolang.org/x/crypto v0.56.0
\tgolang.org/x/net v0.57.0
)

require (
\tgithub.com/jackc/puddle/v2 v2.2.2 // indirect
\tgolang.org/x/sys v0.47.0 // indirect
)
"""

MODULES_TXT = """# github.com/jackc/pgx/v5 v5.9.2
## explicit; go 1.25.0
github.com/jackc/pgx/v5
# github.com/jackc/puddle/v2 v2.2.2
## explicit; go 1.19
github.com/jackc/puddle/v2
# golang.org/x/crypto v0.56.0
## explicit; go 1.26.0
golang.org/x/crypto/ssh
# golang.org/x/net v0.57.0
## explicit; go 1.25.0
golang.org/x/net/icmp
# golang.org/x/sys v0.47.0
## explicit; go 1.25.0
golang.org/x/sys/unix
"""

REQUIREMENTS = """#
# This file is autogenerated by pip-compile with Python 3.12
#
fastapi==0.133.1 \\
    --hash=sha256:1111111111111111111111111111111111111111111111111111111111111111 \\
    --hash=sha256:2222222222222222222222222222222222222222222222222222222222222222
    # via -r requirements.in
starlette==1.3.1 \\
    --hash=sha256:3333333333333333333333333333333333333333333333333333333333333333
    # via fastapi
"""

COMPOSE = """services:
  postgres:
    image: postgres:16-alpine@sha256:{d}
    restart: unless-stopped
  cloud-ingest:
    image: netops-cloud-ingest
  kafka:
    image: apache/kafka:4.1.1@sha256:{d}
  templated:
    image: ${{SOME_IMAGE}}
""".format(d="a" * 64)

OFFLINE_COMPOSE = """services:
  postgres:
    image: postgres:16-alpine
"""

DOCKERFILE = """FROM golang:1.26.8-alpine@sha256:{d} AS build
FROM scratch
FROM ubuntu:24.04
""".format(d="b" * 64)


def _npm_lock(entries: dict[str, dict]) -> str:
    packages = {"": {"name": "fake", "version": "0.1.0"}}
    packages.update(entries)
    return json.dumps({"name": "fake", "lockfileVersion": 3, "packages": packages})


@pytest.fixture()
def fake_repo(tmp_path: Path) -> Path:
    (tmp_path / "src" / "backend" / "vendor").mkdir(parents=True)
    (tmp_path / "src" / "backend" / "go.mod").write_text(GO_MOD)
    (tmp_path / "src" / "backend" / "vendor" / "modules.txt").write_text(MODULES_TXT)

    (tmp_path / "src" / "correlation").mkdir(parents=True)
    (tmp_path / "src" / "correlation" / "requirements.txt").write_text(REQUIREMENTS)

    (tmp_path / "src" / "frontend").mkdir(parents=True)
    (tmp_path / "src" / "frontend" / "package-lock.json").write_text(
        _npm_lock(
            {
                "node_modules/react": {
                    "version": "18.3.1",
                    "license": "MIT",
                    "integrity": "sha512-" + base64.b64encode(b"\xde\xad\xbe\xef").decode(),
                },
                "node_modules/@types/react": {"version": "18.3.29", "dev": True},
                "node_modules/linked": {"link": True},
            }
        )
    )
    (tmp_path / "docs-portal").mkdir(parents=True)
    (tmp_path / "docs-portal" / "package-lock.json").write_text(
        _npm_lock({"node_modules/clsx": {"version": "2.1.1"}})
    )

    docker = tmp_path / "deployment" / "docker"
    docker.mkdir(parents=True)
    (docker / "docker-compose.yml").write_text(COMPOSE)
    (docker / "compose.offline-images.yml").write_text(OFFLINE_COMPOSE)
    (docker / "Dockerfile.backend").write_text(DOCKERFILE)
    return tmp_path


# --------------------------------------------------------------------------- #
# the script's own parser selftest
# --------------------------------------------------------------------------- #


def test_selftest_passes_in_process():
    assert sbom.selftest() == 0


def test_selftest_passes_as_a_subprocess():
    """`--selftest` is what CI runs; it must exit 0 without touching the tree."""
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--selftest"],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    assert result.returncode == 0, result.stderr


# --------------------------------------------------------------------------- #
# go
# --------------------------------------------------------------------------- #


def test_go_marks_direct_and_indirect_from_go_mod(fake_repo: Path):
    components = sbom.collect_go(fake_repo)
    direct = {
        c["name"]
        for c in components
        if any(p["name"] == "correlix:direct" and p["value"] == "true" for p in c["properties"])
    }
    # Exactly the CLAUDE.md §6 allowlist surface — no more, no less.
    assert direct == {
        "github.com/jackc/pgx/v5",
        "golang.org/x/crypto",
        "golang.org/x/net",
    }


def test_go_emits_the_toolchain_as_a_component(fake_repo: Path):
    components = sbom.collect_go(fake_repo)
    toolchain = [c for c in components if c["name"] == "go"]
    assert len(toolchain) == 1
    assert toolchain[0]["version"] == "1.26.8"
    assert toolchain[0]["type"] == "platform"


def test_go_vendored_modules_all_appear(fake_repo: Path):
    names = {c["name"] for c in sbom.collect_go(fake_repo) if c["type"] == "library"}
    assert len(names) == 5
    assert "golang.org/x/sys" in names


def test_go_missing_input_raises_rather_than_emitting_an_empty_document(tmp_path: Path):
    with pytest.raises(sbom.SbomError):
        sbom.collect_go(tmp_path)


# --------------------------------------------------------------------------- #
# npm
# --------------------------------------------------------------------------- #


def test_npm_scoped_names_are_purl_encoded(fake_repo: Path):
    components = sbom.collect_npm(
        fake_repo / "src" / "frontend" / "package-lock.json", "npm-frontend"
    )
    scoped = next(c for c in components if c["name"] == "@types/react")
    assert scoped["purl"] == "pkg:npm/%40types/react@18.3.29"


def test_npm_integrity_becomes_a_hex_hash(fake_repo: Path):
    components = sbom.collect_npm(
        fake_repo / "src" / "frontend" / "package-lock.json", "npm-frontend"
    )
    react = next(c for c in components if c["name"] == "react")
    assert react["hashes"] == [{"alg": "SHA-512", "content": "deadbeef"}]
    assert react["licenses"] == [{"license": {"id": "MIT"}}]


def test_npm_dev_dependencies_are_scoped_optional(fake_repo: Path):
    components = sbom.collect_npm(
        fake_repo / "src" / "frontend" / "package-lock.json", "npm-frontend"
    )
    assert next(c for c in components if c["name"] == "@types/react")["scope"] == "optional"
    assert next(c for c in components if c["name"] == "react")["scope"] == "required"


def test_npm_versionless_link_entries_are_skipped(fake_repo: Path):
    """A `link:`/workspace entry has no version; emitting it would be a fake pin."""
    components = sbom.collect_npm(
        fake_repo / "src" / "frontend" / "package-lock.json", "npm-frontend"
    )
    assert "linked" not in {c["name"] for c in components}


# --------------------------------------------------------------------------- #
# pip
# --------------------------------------------------------------------------- #


def test_pip_pins_carry_every_generate_hashes_digest(fake_repo: Path):
    components = sbom.collect_pip(
        fake_repo / "src" / "correlation" / "requirements.txt", "pip-correlation"
    )
    assert [c["name"] for c in components] == ["fastapi", "starlette"]
    assert len(components[0]["hashes"]) == 2
    assert components[0]["hashes"][0]["alg"] == "SHA-256"
    assert components[0]["purl"] == "pkg:pypi/fastapi@0.133.1"


# --------------------------------------------------------------------------- #
# container images
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "ref,expected",
    [
        (
            "postgres:16-alpine@sha256:" + "a" * 64,
            {"repository": "postgres", "tag": "16-alpine", "digest": "sha256:" + "a" * 64},
        ),
        (
            "gcr.io/cadvisor/cadvisor:v0.52.1",
            {"repository": "gcr.io/cadvisor/cadvisor", "tag": "v0.52.1", "digest": ""},
        ),
        # The port colon and the tag colon are the same character — this is the
        # case a naive split() gets wrong.
        (
            "registry.local:5000/team/app",
            {"repository": "registry.local:5000/team/app", "tag": "", "digest": ""},
        ),
        (
            "registry.local:5000/team/app:v2",
            {"repository": "registry.local:5000/team/app", "tag": "v2", "digest": ""},
        ),
        ("netops-cloud-ingest", {"repository": "netops-cloud-ingest", "tag": "", "digest": ""}),
    ],
)
def test_image_reference_parsing(ref: str, expected: dict):
    assert sbom.parse_image_ref(ref) == expected


def test_images_flag_digest_pinning_honestly(fake_repo: Path):
    components = sbom.collect_images(fake_repo)
    pinned = {}
    for component in components:
        props = {p["name"]: p["value"] for p in component["properties"]}
        pinned[props["correlix:image:ref"]] = props["correlix:image:digest-pinned"]
    assert pinned["postgres:16-alpine@sha256:" + "a" * 64] == "true"
    assert pinned["netops-cloud-ingest"] == "false"
    # The offline-mirror list pins the same image by TAG ONLY. That divergence
    # from the digest-pinned compose entry is exactly what the SBOM must expose.
    assert pinned["postgres:16-alpine"] == "false"


def _git_init_and_add(root: Path, *paths: str) -> None:
    """A real git repo whose INDEX is the tracked set. No commit is needed —
    `git ls-files` reads the index, which is what `tracked_files` queries."""
    def run(*a: str) -> None:
        subprocess.run(
            ["git", "-C", str(root), *a], check=True, capture_output=True, text=True
        )

    run("init", "-q")
    run("config", "user.email", "t@t")
    run("config", "user.name", "t")
    run("add", "--", *paths)


def test_scan_ignores_an_untracked_compose_overlay(fake_repo: Path):
    """The regression that made CI red while `--check` passed locally.

    `compose.offline-images.yml`, `compose.lab.yml` and
    `docker-compose.override.yml` are all GITIGNORED in the real repo — generated
    or site-local files that exist on a developer's box and in no clean clone.
    Scanning them made the committed SBOM describe one working directory.
    """
    docker = fake_repo / "deployment" / "docker"
    (docker / "compose.offline-images.yml").write_text(
        "services:\n  ghost:\n    image: ghost/only-in-a-working-tree:v9\n"
    )
    _git_init_and_add(
        fake_repo,
        "deployment/docker/docker-compose.yml",
        "deployment/docker/Dockerfile.backend",
    )

    refs = {
        p["value"]
        for c in sbom.collect_images(fake_repo)
        for p in c["properties"]
        if p["name"] == "correlix:image:ref"
    }
    assert not any("only-in-a-working-tree" in r for r in refs), (
        "an untracked overlay reached the SBOM"
    )
    # The tracked files are still scanned.
    assert any(r.startswith("postgres:16-alpine@sha256:") for r in refs)
    assert any(r.startswith("apache/kafka:") for r in refs)


def test_tracked_files_returns_none_outside_a_git_checkout(tmp_path: Path):
    """A source tarball has no git. The scan must fall back, not crash."""
    assert sbom.tracked_files(tmp_path) is None


def test_scan_falls_back_to_the_walk_without_git(fake_repo: Path, capsys):
    """No git => every file is scanned, and the WARNING says so (§16.1: a
    silently different scan scope is the failure this guard exists to remove)."""
    assert sbom.tracked_files(fake_repo) is None
    components = sbom.collect_images(fake_repo)
    assert components
    assert "WARNING git unavailable" in capsys.readouterr().err


def test_images_skip_scratch_and_compose_variables(fake_repo: Path):
    refs = {
        p["value"]
        for c in sbom.collect_images(fake_repo)
        for p in c["properties"]
        if p["name"] == "correlix:image:ref"
    }
    assert not any("scratch" in r.lower() for r in refs)
    assert not any("${" in r for r in refs)


def test_images_record_every_origin_of_a_shared_pin(fake_repo: Path):
    """One image used by several services must list them all — a pin change has
    to be applied everywhere, and a single origin would hide the other sites."""
    (fake_repo / "deployment" / "docker" / "docker-compose.override.yml").write_text(
        "services:\n  other:\n    image: netops-cloud-ingest\n"
    )
    component = next(
        c
        for c in sbom.collect_images(fake_repo)
        if c["bom-ref"] == "container:netops-cloud-ingest"
    )
    origin = next(p["value"] for p in component["properties"] if p["name"] == "correlix:origin")
    assert "docker-compose.yml" in origin and "docker-compose.override.yml" in origin


# --------------------------------------------------------------------------- #
# document shape + determinism
# --------------------------------------------------------------------------- #


def test_document_is_valid_cyclonedx_shape():
    doc = sbom.build_document("t", [{"bom-ref": "x", "name": "x"}], "2026-01-01T00:00:00Z", "v1")
    assert doc["bomFormat"] == "CycloneDX"
    assert doc["specVersion"] == sbom.SPEC_VERSION
    assert doc["serialNumber"].startswith("urn:uuid:")
    assert doc["metadata"]["timestamp"] == "2026-01-01T00:00:00Z"
    assert doc["metadata"]["component"]["version"] == "v1"


def test_document_is_independent_of_input_order():
    a = sbom.build_document("t", [{"bom-ref": "b"}, {"bom-ref": "a"}], "T", "v")
    b = sbom.build_document("t", [{"bom-ref": "a"}, {"bom-ref": "b"}], "T", "v")
    assert json.dumps(a) == json.dumps(b)


def test_serial_number_changes_when_components_change():
    a = sbom.build_document("t", [{"bom-ref": "a"}], "T", "v")["serialNumber"]
    b = sbom.build_document("t", [{"bom-ref": "a"}, {"bom-ref": "b"}], "T", "v")["serialNumber"]
    assert a != b


def test_render_is_byte_stable_across_runs():
    first = sbom.render()
    second = sbom.render()
    assert first == second


def test_render_emits_every_class_plus_the_aggregate():
    documents = sbom.render()
    expected = {f"{c}.cdx.json" for c in sbom.CLASSES} | {f"{sbom.AGGREGATE}.cdx.json"}
    assert set(documents) == expected


def test_aggregate_is_the_deduplicated_union_of_the_classes():
    documents = sbom.render()
    union = set()
    for class_name in sbom.CLASSES:
        union |= {
            c["bom-ref"] for c in json.loads(documents[f"{class_name}.cdx.json"])["components"]
        }
    aggregate = json.loads(documents[f"{sbom.AGGREGATE}.cdx.json"])["components"]
    refs = [c["bom-ref"] for c in aggregate]
    assert set(refs) == union
    assert len(refs) == len(set(refs)), "aggregate contains duplicate bom-refs"


# --------------------------------------------------------------------------- #
# the --check gate
# --------------------------------------------------------------------------- #


def test_check_reports_missing_and_stale_without_writing(tmp_path: Path):
    out = tmp_path / "sbom"
    assert sbom.main(["--out", str(out)]) == 0
    assert sbom.main(["--check", "--out", str(out)]) == 0

    target = out / f"{sbom.CLASSES[0]}.cdx.json"
    target.write_text("{}\n")
    assert sbom.main(["--check", "--out", str(out)]) == 1
    assert target.read_text() == "{}\n", "--check must never rewrite the file it is checking"

    target.unlink()
    assert sbom.main(["--check", "--out", str(out)]) == 1


def test_print_writes_one_document_to_stdout(capsys):
    assert sbom.main(["--print", "go-backend"]) == 0
    doc = json.loads(capsys.readouterr().out)
    assert doc["metadata"]["properties"][0]["value"] == "go-backend"


def test_check_ignores_metadata_only_differences(tmp_path: Path):
    """A regeneration at a different commit changes the timestamp, version and
    serial. That is not drift, and it must not fail the gate."""
    out = tmp_path / "sbom"
    assert sbom.main(["--out", str(out)]) == 0

    target = out / f"{sbom.CLASSES[0]}.cdx.json"
    doc = json.loads(target.read_text())
    doc["metadata"]["timestamp"] = "1999-01-01T00:00:00Z"
    doc["metadata"]["component"]["version"] = "9.9.9-different"
    doc["serialNumber"] = "urn:uuid:00000000-0000-5000-8000-000000000000"
    target.write_text(json.dumps(doc, indent=2) + "\n")

    assert sbom.main(["--check", "--out", str(out)]) == 0


def test_check_fails_when_a_component_is_removed(tmp_path: Path):
    out = tmp_path / "sbom"
    assert sbom.main(["--out", str(out)]) == 0
    target = out / f"{sbom.CLASSES[0]}.cdx.json"
    doc = json.loads(target.read_text())
    doc["components"].pop()
    target.write_text(json.dumps(doc, indent=2) + "\n")
    assert sbom.main(["--check", "--out", str(out)]) == 1


def test_image_origins_carry_no_line_numbers(fake_repo: Path):
    """A line number moves when an unrelated service is edited above it, which
    made the committed SBOM churn on compose edits that changed no pin."""
    for component in sbom.collect_images(fake_repo):
        origin = next(
            p["value"] for p in component["properties"] if p["name"] == "correlix:origin"
        )
        assert not re.search(r"\.ya?ml:\d+", origin), origin
        assert not re.search(r"Dockerfile[^,]*:\d+", origin), origin


def test_provenance_is_keyed_to_the_dependency_inputs_not_head():
    """`inputs_revision()` must resolve to a commit that touched a manifest.

    If this ever falls back to HEAD, the committed SBOM starts churning on every
    unrelated commit and `--check` becomes noise.
    """
    rev = sbom.inputs_revision()
    if rev is None:
        pytest.skip("not a git checkout")
    sha, date = rev
    assert len(sha) == 40
    assert date.startswith("20")
    assert "deployment/docker" in sbom.INPUT_PATHS
    assert "src/backend/go.mod" in sbom.INPUT_PATHS


def test_source_date_epoch_overrides_the_timestamp(monkeypatch):
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "1700000000")
    assert sbom.build_timestamp() == "2023-11-14T22:13:20Z"


# --------------------------------------------------------------------------- #
# the committed artifact
# --------------------------------------------------------------------------- #


def test_committed_sbom_matches_the_current_dependency_tree():
    """`docs/sbom/` must be regenerated whenever a dependency moves.

    This test failing is not a bug in the test: it means a dependency changed and
    the committed bill of materials no longer describes the tree. Fix it with:

        python3 scripts/sbom.py
    """
    assert sbom.main(["--check"]) == 0, (
        "docs/sbom/ is stale — run `python3 scripts/sbom.py` and commit the result"
    )
