#!/usr/bin/env python3
"""
gen-licensing-map.py — render LICENSING.md from licensing-policy.json.

Why this exists
---------------
The directory-to-licence map is the document a customer, an auditor or a
contributor reads to answer "may I use this file, and on what terms". A
hand-maintained map drifts the moment someone adds a directory, and a licence
map that is wrong is worse than none: it makes a promise the repository does
not keep.

So the map is GENERATED. `licensing-policy.json` is the single source of truth;
this script renders it; `--check` fails when the rendered output and the
checked-in file disagree. Editing LICENSING.md by hand changes nothing that is
enforced and is reverted by the next run.

The map is written to BOTH repository roots, byte-identical, because the outer
repository root and the nested project directory are both places a reader
lands first.

Usage
    python3 scripts/gen-licensing-map.py            # print to stdout
    python3 scripts/gen-licensing-map.py --write    # write both LICENSING.md
    python3 scripts/gen-licensing-map.py --check    # exit 1 on drift

Pure standard library. No network, no running stack.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
REPO = os.path.dirname(PROJ)
POLICY = os.path.join(PROJ, "licensing-policy.json")
TARGETS = (os.path.join(REPO, "LICENSING.md"), os.path.join(PROJ, "LICENSING.md"))

BANNER = (
    "<!-- GENERATED by scripts/gen-licensing-map.py from licensing-policy.json.\n"
    "     Do not hand-edit: edit the policy and re-run with --write. -->"
)


def load_policy() -> dict:
    with open(POLICY, encoding="utf-8") as fh:
        return json.load(fh)


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    out = [_row(headers), _row(["---"] * len(headers))]
    out.extend(_row(r) for r in rows)
    return out


def render(policy: dict) -> str:
    core = policy["identifiers"]["core"]
    comm = policy["identifiers"]["commercial"]
    sentence = policy["canonical_sentence"]
    out: list[str] = [BANNER, "", "# Correlix licensing", "", sentence, ""]

    out += [
        "Correlix is **open core**. The engine, the pipeline, the isolation model and the",
        f"investigation surface are `{core}`. A named set of commercial add-on modules is",
        f"`{comm}`, a source-available licence: readable and buildable, not licensed for",
        "production use without a commercial agreement.",
        "",
        "**The default is open.** A file with no SPDX header, in a directory with no Enterprise",
        "notice file, is `" + core + "`. Nothing becomes commercial by omission.",
        "",
        f"- Decided {policy['decided']} by the {policy['decided_by']}.",
        f"- Design of record: [`{policy['design_of_record']}`]({policy['design_of_record']})",
        f"- What each tier gets: [`{policy['tiering_plan']}`]({policy['tiering_plan']})",
        "- Machine-readable policy: [`licensing-policy.json`](NetOps_Observability/licensing-policy.json)",
        "",
        "## The two licences",
        "",
    ]
    out += _table(
        ["SPDX identifier", "Text", "What it covers"],
        [
            [f"`{core}`", f"[`{policy['licence_texts'][core]}`]({policy['licence_texts'][core]})", "Correlix core. Use it, modify it, redistribute it, run it in production."],
            [f"`{comm}`", f"[`{policy['licence_texts'][comm]}`]({policy['licence_texts'][comm]})", "Commercial add-on modules. Source-available for inspection, development and evaluation; production use requires a commercial licence from Correlix."],
        ],
    )
    out.append("")

    blockers = policy["release_blockers"]["entries"]
    placeholder = [b for b in blockers if b["id"] == "enterprise-text-placeholder"]
    if placeholder:
        b = placeholder[0]
        out += [
            f"> **The Correlix Enterprise License text does not exist yet.** `{b['file']}` is a",
            "> placeholder. Files carrying that identifier are therefore licensed to nobody, and",
            "> all rights in them are reserved until the text lands. `scripts/licensing-gate.py",
            "> --release` fails while it is missing, so no artifact can ship in this state.",
            f"> Owner action: {b['owner_action']}",
            "",
        ]

    # ── core ────────────────────────────────────────────────────────────────
    out += ["## Apache-2.0 core", "", "The following are core and stay core:", ""]
    out += [f"- {item}" for item in policy["core_is_never_commercial"]["items"]]
    out += [
        "",
        "> **Isolation is core and is never a paywall.** Tenant and organisation isolation is a",
        "> safety property: every tier gets the same default-closed scoping, the same FORCE-RLS",
        "> policies and the same per-store filters. A cross-tenant leak is a defect in every",
        "> edition, so the code that prevents one is licensed to everybody.",
        "",
    ]

    # ── commercial ──────────────────────────────────────────────────────────
    locked = policy["locked_commercial_set"]
    out += [
        f"## Commercial add-ons (`{comm}`)",
        "",
        "The owner has locked exactly this set. A capability not listed here is **not** gated,",
        "whatever a draft tiering document proposes.",
        "",
    ]
    rows = []
    for tier in ("Team", "Enterprise"):
        for ent in locked.get(tier, []):
            rows.append([f"`{ent['id']}`", tier, ent["what"]])
    out += _table(["Entitlement", "Tier", "What it is"], rows)
    out += [
        "",
        "**MSP and org-hierarchy MANAGEMENT is commercial; tenant isolation is not.** Managing a",
        "fleet of tenants as one account is a commercial capability. Being isolated from another",
        "tenant is not, and never will be.",
        "",
    ]

    # ── the directory map ───────────────────────────────────────────────────
    tl = policy["project_top_level"]
    out += [
        "## Directory map",
        "",
        "### Project directory (`NetOps_Observability/`)",
        "",
        "Every top-level directory, exactly once. `tests/test_licensing_consistency.py` derives",
        "the real list from the filesystem and fails if one is missing, duplicated or unknown.",
        "",
    ]
    rows = []
    for e in tl["entries"]:
        state = "MIXED — pending `ee/` extraction" if e["state"] == "mixed" else e["licence"]
        rows.append([f"`{e['path']}/`", state, e["reason"]])
    out += _table(["Directory", "Licence", "Why"], rows)
    out.append("")

    ex = policy["excluded_paths"]
    out += [
        "#### Not classified, and why",
        "",
        "These directory names are excluded everywhere in the tree. None is Correlix source whose",
        "licence we are entitled to declare.",
        "",
    ]
    out += _table(["Name", "Why excluded"], [[f"`{x['name']}`", x["why"]] for x in ex["entries"]])
    out.append("")

    rr = policy["repo_root_entries"]
    out += ["### Repository root", "", rr["_why"], ""]
    rows = []
    for e in rr["entries"]:
        state = "MIXED — see above" if e["state"] == "mixed" else e["licence"]
        rows.append([f"`{e['path']}`", state, e["reason"]])
    out += _table(["Entry", "Licence", "Why"], rows)
    out += ["", "Not part of this project, and carrying no Correlix licence declaration:", ""]
    out += [f"- `{x['path']}` — {x['why']}" for x in rr["not_part_of_this_project"]]
    out.append("")

    # ── cleanly commercial ──────────────────────────────────────────────────
    cp = policy["commercial_paths"]
    out += [
        "## Directories that are commercial today",
        "",
        "These are cleanly separated: every file implements a locked commercial entitlement and",
        "nothing else. Each carries a `LICENSE` notice file and an SPDX header on every source file.",
        "",
    ]
    rows = [
        [f"`{e['path']}/`", f"`{e['entitlement']}`", e["tier"], e["reason"]]
        for e in cp["entries"]
    ]
    out += _table(["Directory", "Entitlement", "Tier", "Why it is cleanly commercial"], rows)
    out.append("")

    # ── removing the commercial modules ─────────────────────────────────────
    rm = policy["enterprise_removal_recipe"]
    out += [
        "### Removing them",
        "",
        rm["_why"],
        "",
    ]
    out += [f"{step}" if step.startswith(("1.", "2.", "3.", "4.", "5.", "6.", "7.", "8.", "9."))
            else f"- {step}" for step in rm["steps"]]
    out += ["", rm["guarantee"], ""]

    # ── still mixed ─────────────────────────────────────────────────────────
    md = policy["mixed_directories"]
    out += [
        "## Still mixed",
        "",
        "These directories contain BOTH Apache-2.0 core code and code implementing a commercial",
        f"entitlement. They stay **`{core}` in full** until the commercial part is extracted to",
        f"`{md['target_layout']}`: over-claiming commercial on a shared package would wrongly",
        "restrict core code, and the conservative direction is the open one.",
        "",
        f"Tracked as **TRACKER.md row {md['tracker_row']}** — the `enterprise/` extraction.",
        "",
    ]
    rows = [
        [f"`{e['path']}/`", e["tier"], e["commercial_part"], e["why_not_split_today"]]
        for e in md["entries"]
    ]
    out += _table(["Directory", "Tier", "What belongs in `enterprise/`", "Why it has not moved"], rows)
    out.append("")

    # ── how a file declares its licence ─────────────────────────────────────
    he = policy["header_enforcement"]
    out += [
        "## How a file declares its licence",
        "",
        "**1. An SPDX header comment**, the first comment line of the file:",
        "",
        "```go",
        f"// SPDX-License-Identifier: {core}",
        "```",
        "",
        "```go",
        f"// SPDX-License-Identifier: {comm}",
        "```",
        "",
        "**2. A per-directory `LICENSE` notice file.** Every directory listed as commercial above",
        "carries one naming its identifier, so a reader who lands in that directory — or an",
        "automated scanner that walks it — learns the terms without reading this map.",
        "",
        "**3. The default.** No header and no notice file means `" + core + "`.",
        "",
        "### What is enforced today",
        "",
        f"`scripts/licensing-gate.py` runs checks A-H. Header mode is `{he['mode']}`:",
        "",
    ]
    out += [f"- {r}" for r in he["rules"]]
    out += [
        "",
        (f"Repo-wide `{core}` headers on core source are **pending**, not skipped: "
         f"{he['pending']['why_deferred']} Tracked on row {he['pending']['tracker_row']}."),
        "",
    ]

    # ── container images ────────────────────────────────────────────────────
    ci = policy["container_images"]
    expr = ci["oci_licence_expressions"]
    out += [
        "## Container images",
        "",
        "A Dockerfile that builds a **Correlix** image declares the licence in OCI metadata",
        "(`org.opencontainers.image.licenses`). A Dockerfile that only repackages a third-party",
        "image declares nothing: labelling someone else's software with our licence would be a",
        "false claim.",
        "",
        "That label is an SPDX License **expression** for what the image CONTAINS, so exactly two",
        "values are canonical:",
        "",
        f"- `{expr['core_only']}` — the image contains core code only.",
        f"- `{expr['mixed']}` — the image also contains commercial code.",
        "",
        expr["rule"],
        "",
    ]
    rows = [[f"`{e['path']}`", f"`{e['licence']}`", e["why"]] for e in ci["ours"]]
    out += _table(["Dockerfile", "Label", "Why"], rows)
    out += ["", "Repackaged third-party images, deliberately unlabelled:", ""]
    out += [f"- `{e['path']}` — {e['why']}" for e in ci["third_party_repackage"]]
    out.append("")

    # ── third party ─────────────────────────────────────────────────────────
    out += [
        "## Third-party components",
        "",
        "The split above concerns Correlix's own code. Software Correlix redistributes keeps its",
        "own licence and its own obligations, inventoried in [`NOTICE`](NOTICE) and the generated",
        "[`docs/THIRD_PARTY_LICENSES.md`](docs/THIRD_PARTY_LICENSES.md).",
        "",
        "## Contributing",
        "",
        "Contributions require a signed Contributor License Agreement, because open core needs the",
        "right to relicense contributed code into the commercial edition. See",
        "[`CONTRIBUTING.md`](CONTRIBUTING.md).",
        "",
    ]
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="write LICENSING.md at both roots")
    ap.add_argument("--check", action="store_true", help="exit 1 if the checked-in map is stale")
    args = ap.parse_args(argv)

    body = render(load_policy())

    if args.write:
        for target in TARGETS:
            with open(target, "w", encoding="utf-8") as fh:
                fh.write(body)
            print(f"wrote {os.path.relpath(target, REPO)} ({len(body)} bytes)")
        return 0

    if args.check:
        stale = []
        for target in TARGETS:
            try:
                with open(target, encoding="utf-8") as fh:
                    have = fh.read()
            except OSError as err:
                print(f"MISSING: {target}: {err}", file=sys.stderr)
                stale.append(target)
                continue
            if have != body:
                print(f"STALE: {target} differs from the rendered policy", file=sys.stderr)
                stale.append(target)
        if stale:
            print("Run: python3 scripts/gen-licensing-map.py --write", file=sys.stderr)
            return 1
        print(f"LICENSING.md is current at both roots ({len(body)} bytes)")
        return 0

    sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
